### ISSUE TITLE
gs config editing problem 

### ISSUE THREAD

**Issue by smt287** [easy-wi/developer#1000]
please help me :)
https://www.youtube.com/watch?v=NtMexN-XfGI
my fpm-error.log https://hastebin.com/supoyibabu.pas
edit: add new video

**Comment by Lacrimosa99** [comment]
Hi,

As well as in the gritter chat is a faulty set system.

**Comment by smt287** [comment]
I learned that after a long time I did not support the Turkish (ç, ş, t, ü, ö etc.) letters. How can I solve this problem?

**Comment by ulrichblock** [comment]
This cannot be reproduced on Ubuntu 16.04 with PHP7, MySQL 5.7 and default locales which are installed during english setup. So at this point it is up to you to check your systems and add the language support to the OS itself. Cannot tell what you might have done and what is missing.
