### ISSUE TITLE
Startparameter

### ISSUE THREAD

**Issue by Headwipe** [easy-wi/developer#1001]
Gibt es eine Möglichkeit dem Kunden einen benutzerdefinierten Teil der Startparameter für Gameserver ändern oder bestimmen zu lassen?

Zum Beispiel bei einem Arma 3 Server werden die Mods die geladen werden in den Startparametern definiert. Ich habe jedoch noch keine Möglichkeit gefunden dies zu realisieren oder bin Ich einfach nur Blind?

Gruß

Headwipe :)

**Comment by Lacrimosa99** [comment]
Hi,
bitte solch Fragen in den Gitterchat da Github für Panel Requests sauber bleiben sollen.

Zu deiner Frage... dazu ist die Mod Funktion zuständig im Admin Teil... Gameserver (Admin Panel) -> Addons

Über das Addon Template kannst du auch die Parameter hinzufügen, welche beim Start mit eingebunden werden sollen (Startbefehl).
