### ISSUE TITLE
Cannot download screenlog from server/cstrike/screenlog.0

### ISSUE THREAD

**Issue by Raiz3n1312** [easy-wi/developer#1002]
"Hello! After Update 6.0.0 Easy-wi Cannot Access Screenlog.0
"Cannot download screenlog from server/cstrike/screenlog.0"
Tired to fix the problem please give some help for me :D

**Comment by ulrichblock** [comment]
Restart the server and try again.

**Comment by Raiz3n1312** [comment]
U are funny rly.  Restarted 1000 times and do not work... i have 20 server. And 20 of 20 not reading screenlog.0 Redtarted the vps restarted the dedicated server restarted webserver restarted game servers. And do not work again and again....

**Comment by ulrichblock** [comment]
For me it works 1001 times without any issue. That means it is not a bug. Instead a misconfigured setup is very likely the reason. In such a case a sufficient debug analysis is required to help. You did not provide anything decent with that regard.

Anyway the GitHub tickets are used for code issues and features and NOT for supporting an admin with the configuration of his system. Please use the Gitter channel instead https://gitter.im/easy-wi/Lobby
But be aware, that no help will follow there either in case you just write "it does not work"
