### ISSUE TITLE
ticket system failure on add category

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#1006]
When adding a category, the following error is output in the log: `Undefined variable: options in /home/easywi_web/htdocs/template/default/admin/admin_ticket_topic_add.tpl on line 28`

this is the line: `<?php foreach ($options as $option) { ?><?php echo $option;?><?php }?>`

Resulting failure: `Invalid argument supplied for foreach() in /var/www/easywi_web/htdocs/template/default/admin/admin_ticket_topic_md.tpl on line 29`

Probable error in SQL syntax since `subcategory of` and `priority` entries are missing.
Changes to the source code I could not determine what the ticket system concerns.

**Comment by ulrichblock** [comment]
Ubuntu 16.04 and newer have a MySQL default configuration, which breaks on certain cases silently if debugging is not active. 
The indicated not set error was not the cause.

**Comment by JanDevDE** [comment]
Workaround for Ubuntu 16.04.02: 

Create file in: /etc/mysql/conf.d/  (e.g disablestrictmode.cnf), and restart mysql afterwards.

[mysqld]
sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
