### ISSUE TITLE
Cvar überschreibt Konfiguration (ähnlich #908)

### ISSUE THREAD

**Issue by Alex130988** [easy-wi/developer#1008]
Guten tag,

die server.properties von meinen Minecraft servern wird bei jedem (re)starten des Server komplett von dem cvar überschrieben. Dies ist eher unpraktisch wenn der User was an der Konfiguration ändern möchte.

**Comment by guenniman** [comment]
Ich habe das gleiche Problem bei meinen Servern.

**Comment by ulrichblock** [comment]
Was ist "mit dem cvar"? Bitte vorher nacher Beispiele einfügen. Dazu das Template, das genutzt wird.

**Comment by Alex130988** [comment]
Hi, das standart cvar sieht ja so aus

[server.properties] ini
server-port=%port%
query.port=%port%
enable-query=true
rcon.port=%port2%
server-ip=%ip%
max-players=%slots%

und genau so hab ich es in mein neues themplate übernommen, nach dem der server neu gestartet wurde steht, in der server.properties:

**Comment by Knot3n** [comment]
Template fehlt.

**Comment by Alex130988** [comment]
"Das gesamte template wurde von dem "Minecraft" übernommen, bis auf den startbefehl den haben wir verändert"

**Comment by ulrichblock** [comment]
Ich habe das gerade versucht nachzustellen. Dabei ist mir aufgefallen, dass Minecraft selber die Datei bei jedem Server Start neu schreibt. Die vorangegangen Werte bleiben dabei aber bestehen. Sehen kann ich das an den ersten beiden Zeilen:
```
#Minecraft server properties
#Sat Jun 17 14:43:31 CEST 2017
```

Der Startbefehl, der hier genannt wird, ist übrigens exakt der, der auch im default Template steht. Habt ihr genau diesen, oder doch noch was anderes.

Ich habe gerade mal gegoogelt und konnte lesen, dass es immer dann passiert, wenn die Datei aus irgend einem Grund als beschädigt vom Server eingestuft wird. Das Warum im Zusammenhang mit Easy-Wi erschließt sich mir bisher noch nicht.

**Comment by Alex130988** [comment]
Das problem ist das er selbst wenn die datei von minecraft geschrieben wurde, beim Server start, beim (re)start oder stop und dan start wieder beim starten auf die  Werte gesätzt wird:

server-port=25597
query.port=25597
enable-query=true
server-ip=
max-players=24

und sonst erst nach dem der server kommplett gestartet wurden ist mit den extra daten von den Minecraft server gefüllt wurden ist.

Selbst wenn nichts vom user oder von uns editiert wurden ist wird sie beim (re)start oder stop und dan start auf 0 zurück gesätzt und dan wieder neu gefüllt.

Wegen dem startparameter.. ich habe den standart parameter für die test zwecke eingefügt unser startparameter würe die Beschreibung des ganzen nicht einfacher machen. zum abgleich unser normaler startparameter ist:

java -Xmx%maxram%M -Xms%minram%M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -jar %binary% nogui


aber er tut nix zur sache da es auch mit dem standart parameter passiert

MfG Alex130988

**Comment by ulrichblock** [comment]
Die Frage ist hier doch, wer diese Änderung macht. Ich versuche es nachzustellen und kann nur sehen. dass es vom Minecraft Server selber kommt. Wenn es Minecraft ist, kann ich nichts machen.
So lange nicht beschrieben wird, ob es bei dir Easy-Wi ist, kann ich nichts machen. Was ich nicht nachstellen kann, kann ich auch nicht beheben.

**Comment by Lacrimosa99** [comment]
Warscheinlich Datei Codierungsproblem ähnlich wie bei ARK.
Bearbeite die Datei mittels Notepad++ oder PSPad in UTF8 und lad dann hoch.
