### ISSUE TITLE
Minecraft server creates odd home directory

### ISSUE THREAD

**Issue by JanDevDE** [easy-wi/developer#1010]
If I install a minecraft server for e.g user2, there are too many directories being created.

Normal: 
user2/server/spigot/

Now: 
/home/user2/server/spigot/<All server content>
AND 
/home/user2/home/user2/server/spigot/server.properties (Only this file)

**Comment by Lacrimosa99** [comment]
than is your mountpoint in your masterserver template wrong.
check the mountpoint insode your WI Masterserver Settings.

**Comment by JanDevDE** [comment]
[home]
path = /home
mountpoint = /
size = 500GB
default = 1

**Comment by JanDevDE** [comment]
But wouldn't it then creating nothing at all ? It just creates 1 directory more than usual. CSGO works fine.

**Comment by JanDevDE** [comment]
@MrJoki007 hat das selbe Problem. Siehe gitter.

**Comment by JanDevDE** [comment]
Sollte bald gefixt sein -Closed-

**Comment by ulrichblock** [comment]
Bitte mehr Details. Wer hat wie wann wo was gefixt?

**Comment by Lacrimosa99** [comment]
Fix ist noch in Arbeit da ich noch verschiedene Tests mache.
