### ISSUE TITLE
CMS Pages & Settings

### ISSUE THREAD

**Issue by kopi120** [easy-wi/developer#1011]
Hello

Sorry my english is not good.
When I add a page, it is not visible in the admin area and in the website. (I'm find in database, and news work)
When I modify CMS settings, get an error message "Error: Updating the database failed, or no new data had been entered!"

Ubuntu 16.04 x64
Easy-Wi: 6.0.0
Mysql: 5.7.18
Apache: 2.4.18
PHP: 7.0.18

**Comment by kopi120** [comment]
Shared Host:
Easy-Wi: 6.0.0
PHP: 5.6.27
Apache: 2
Mysql: 5.6.34

Add/Edit/Del works
not visible in the website :(

**Comment by sscs12345** [comment]
This should do the trick:
https://pastebin.com/24cfCGGa
Welcome ;)
