### ISSUE TITLE
Ark Modupdater

### ISSUE THREAD

**Issue by Pfanni22** [easy-wi/developer#1012]
if [ ! $(locate htdocs/stuff/config.php) = "" ]; then
			DATABASE_CONFIG_PATH=$(locate htdocs/stuff/config.php)

ist nicht für manuelle installationen gedacht, daher trägt er sich nicht von selbst ins wi ein :(

**Comment by Lacrimosa99** [comment]
Falsches git.. Macht nix.. Ulrich kanns löschen.
Gruss
