### ISSUE TITLE
lendserver bug

### ISSUE THREAD

**Issue by MikkelDK** [easy-wi/developer#1014]
Hi,

I have try and setup lendserver module. (But the site mean it's deactivated.)
[Screenshot - where the module is enabled.](https://i.gyazo.com/7433b85293eca48b46bbe11a128e8910.png)

if i using: index.php?site=lendserver:

`Notice: Undefined index: lendserver in /var/www/html/panel/template/default/cms/page_lend_list.tpl on line 5`

source code:

` <li class="active"><?php echo $page_data->pages['lendserver']['linkname'];?></li>`

- if i using: index.php?site=lendserver&d=gs
Module deactivated (no errors from the page.)

- Does CMS needed to be enabled?

**Comment by ulrichblock** [comment]
Unfortunately I cannot follow the issue.

At /admin.php?w=le&d=se I can configure where lending is allowed, I don't know, what is set there.
Are there game and voice server marked for lending?

I assume you are trying it in combination with WHCMS. Can you check its logs? It is using an API in the background. This is provided by lend.php in XML format. If debugger is active you might see clues in the WHMCS action log.

**Comment by MikkelDK** [comment]
> Are there game and voice server marked for lending?
- Yes game server is marked for lending.

> If debugger is active you might see clues in the WHMCS action log.
- I cant see the errors (no posts about errors.)

i'm willing to give access on the machine. SSH + SFTP.

**Comment by MikkelDK** [comment]
@ulrichblock - any update about the screenshot?

**Comment by ulrichblock** [comment]
I guess this is at the WHMCS module? If yes the issue list would be here: https://github.com/easy-wi/whmcs/issues
