### ISSUE TITLE
Fix FTP Perm

### ISSUE THREAD

**Issue by FlashModz** [easy-wi/developer#1018]
Hello All,

I installed Easy-wi to try.
The installation is successful and the servers are operational.

But a major problem is present.
When I create a server for a client, its FTP access permits it to access the root folder of the server.

It can download and modify the files.

Could you help me ?

Spec Server:

- Ubuntu 16.04 LTS
- All package are Up2Date.
- No mistake

**Comment by FlashModz** [comment]
My Pro-FTP conf , https://pastebin.com/MuuYWeaW

**Comment by MikkelDK** [comment]
You need to use this:

wget https://github.com/easy-wi/server/blob/master/migrate.sh && chmod +x migrate.sh && ./migrate.sh

After that so try test about it works!

**Comment by FlashModz** [comment]
I'm one error : 


root@ns3030460:~# wget https://github.com/easy-wi/server/blob/master/migrate.sh && chmod +x migrate.sh && ./migrate.sh
--2017-08-09 22:47:26--  https://github.com/easy-wi/server/blob/master/migrate.sh
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘migrate.sh’

migrate.sh                                    [ <=>                                                                                 ]  63.23K   392KB/s    in 0.2s

2017-08-09 22:47:27 (392 KB/s) - ‘migrate.sh’ saved [64745]

./migrate.sh: line 7: syntax error near unexpected token `newline'
./migrate.sh: line 7: `<!DOCTYPE html>'

**Comment by FlashModz** [comment]
An FTP generate for the client to the same accesses as a Root.
I can not understand why their ftp access is not limited to their directories.

**Comment by MikkelDK** [comment]
Seems, you dont have installed easy-wi.conf ...

You need this:
`# Check if proftpd rules are installed
if [ -f /etc/proftpd/conf.d/easy-wi.conf -a "`grep '~/\*/\*/>' /etc/proftpd/conf.d/easy-wi.conf`" != "" ]; then

    echo "Creating backup of /etc/proftpd/conf.d/easy-wi.conf"
    cp /etc/proftpd/conf.d/easy-wi.conf /etc/proftpd/easy-wi.conf.pre_migration.backup

    # For each rule, check if still exist and migrate
    echo "Changing entries at /etc/proftpd/conf.d/easy-wi.conf"

    if [ "`grep '~/\*/\*/>' /etc/proftpd/conf.d/easy-wi.conf`" != "" ]; then
        echo "Changing entry '~/*/*/>' to '~/*/>'"
        sed -i 's/~\/\*\/\*\/>/~\/\*\/>/g' /etc/proftpd/conf.d/easy-wi.conf
    fi

    if [ "`grep '/home/\*/pserver/\*>' /etc/proftpd/conf.d/easy-wi.conf`" != "" ]; then
        echo "Changing entry '/home/*/pserver/*>' to '/home/*/pserver>'"
        sed -i 's/\/home\/\*\/pserver\/\*>/\/home\/\*\/pserver>/g' /etc/proftpd/conf.d/easy-wi.conf
    fi

    if [ "`grep '<Directory ~/server/\*/' /etc/proftpd/conf.d/easy-wi.conf`" != "" ]; then
        echo "Changing entries '<Directory ~/server/*/' to '<Directory ~/server/'"
        sed -i 's/<Directory ~\/server\/\*\//<Directory ~\/server\//g' /etc/proftpd/conf.d/easy-wi.conf
    fi

    if [ "`grep '~/\*/\*/\*/\*/' /etc/proftpd/conf.d/easy-wi.conf`" != "" ]; then
        echo "Changing entries '~/*/*/*/*/' to '~/*/*/'"
        sed -i 's/~\/\*\/\*\/\*\/\*\//~\/\*\/\*\//g' /etc/proftpd/conf.d/easy-wi.conf
    fi`

**Comment by FlashModz** [comment]
Yes i'm tested, this file is empty
