### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by cskarabela** [easy-wi/developer#1020]
This error occurs when redirecting to home page after logging out

**Please allow redirection settings**

server php version 5.6

**Comment by MikkelDK** [comment]
You are not alone, with the problem. I got same issues.

**Comment by XMGamingMaster** [comment]
It seems like you guys dont have output buffering configured on your webserver

**Comment by cskarabela** [comment]
It works in php 7 but it doesn't work in php 5.6

**Comment by MikkelDK** [comment]
Ah i see. 
i'm using php 5.6 > Debian 7.

**Comment by ulrichblock** [comment]
Can reproduce the same on Ubuntu 16.04.
