### ISSUE TITLE
E-Mails werden doppelt versendet

### ISSUE THREAD

**Issue by ghost** [easy-wi/developer#1032]
Bei meiner Easy-Wi installation werden sämtliche Mails doppelt versendet. An dem Mailserver selber kann es nicht liegen denn alleine schon in den Mail-Logs im Interface selbst werden die Mails doppelt angezeigt.

Woran könnte das liegen? Mich selber stört es nicht aber es muss ja nicht zwangsläufig sein das man seine Kunden mit "Ihr Server wurde hinzugefügt" Mails zuspammt :D

Das genutzte System läuft auf Debian 9 mit Postfix als Relayserver installiert. Apache2 mit php7.0 und der DB server ist MariaDB.

Ich hoffe mir kann jemand einen Rat geben.

**Comment by ulrichblock** [comment]
Gibt es bei dir Verteter mit der selben Mail, wie bei einem Useraccount? Geht die gleiche Mail im Log immer doppelt per userid raus?

**Comment by KDBFame** [comment]
Nein es gibt keine Vertreter mit der selben Mail und ja sie geht im Log doppelt raus für die selbe userid
