### ISSUE TITLE
Sicherheitsproblem: Zeigt passwörter

### ISSUE THREAD

**Issue by florian96** [easy-wi/developer#1033]
Wenn man die Einstellungen eines Master Servers aufruft, dann werden TS3 Passwort sowie SSH passwörter übertragen. Diese lassen sich recht einfach auslesen.

![image](https://user-images.githubusercontent.com/9999676/32260232-d1120652-bec6-11e7-8d22-a3883bcf2426.png)

**Comment by ulrichblock** [comment]
Dies ist nicht so kritisch, wie es zuerst scheinen mag:
- Das Interface sollte in Zeiten von Letsentcrypt usw. ausschließlich über https erreichbar sein
- Zugreifen darf nur derjenige, welche auch neue Passwörter eintragen kann
- Im Falle von Keys + Passwort (empfohlen!) kann man mit dem Passwort alleine nicht viel machen
- SSH2 Passwörter bzw. die Passwörter zu den Keys werden über AES128 verschlüsselt in den DB abgelegt

**Comment by chronicals** [comment]
Ich finde es sehr wohl kritisch. Das Passwort sollte zumindest nicht im Klartext auf dem Display angezeigt werden!

Erst vorgestern einem Kollegen den Aufbau des Interfaces gezeigt und Ihm dabei aus Versehen die Hälfte der Server Passwörter offenbart. 

Man könnte ja zumindest eine Passwort Anzeigen Checkbox neben den Klartext Feldern anzeigen und den Admin Gruppen vllt auch noch die Permission Show Passwords geben, sodass nur die Admins, welche die Passwörter auch wirklich sehen dürfen diese einsehen können!
