### ISSUE TITLE
Login loop.

### ISSUE THREAD

**Issue by MikkelDK** [easy-wi/developer#1035]
Login system is bugged, sometimes you trying to login on panel, (first time e.g.) but you will not be logged on the panel.

(Tested on Chrome, where the problem do - i need to login 2x before i will be on panel)
(Tested on Firefox/Edge: Works atm (will be updated!)

You need to enter username/password 2x before you will be logged on.

SSL using!

**Comment by Lacrimosa99** [comment]
Which OS, PHP Version and Webserver (Easy-WI) Logs.

**Comment by MikkelDK** [comment]
Debian 8.9, PHP Version: 5.6 - Webserver: Apache2 :)

**Comment by Lacrimosa99** [comment]
can i not confirm... show webserver logs from wi.

**Comment by MikkelDK** [comment]
Dunno about it's this, since i see some errors.

Undefined variable: pageurl in /home/easywi_web/htdocs/login.php on line 106
PHP Notice:  Undefined index: pubDate in /home/easywi_web/htdocs/stuff/user/userpanel_home.php on line 154

Example. ^^

**Comment by Bara20** [comment]
I've the same issue (Nginx (SSL)/PHP7.1/MariaDB). It's when you forget to logout and you try to log in a few minutes later.

**Comment by Lacrimosa99** [comment]
check php timezone...

**Comment by ulrichblock** [comment]
Please check if fix for #1020 also fixes this issue

**Comment by MikkelDK** [comment]
Update today: it works for me! :)
