### ISSUE TITLE
Update time Problem

### ISSUE THREAD

**Issue by florian96** [easy-wi/developer#1038]
Beim Server Status bleiben die Minuten immer auf 11 stehen. Die anderen werte ändern sich.

Webinterface: Status vom 03.11.2017 19:**11**:02
DB (lendsettings lastcheck) 2017-11-03 19:**15**:02

**Comment by ulrichblock** [comment]
IN welchem Modul an welcher Stelle findest du diese Zeilen?

**Comment by florian96** [comment]
Den Status finde ich im Gameserver bereich des Nutzer Accounts. Minecraft.
Der Wert aus der Datenbank hab ich aus der Lendsettings Tabelle.

**Comment by florian96** [comment]
Ich habe ganz sicher EasyWI.

**Comment by ulrichblock** [comment]
Der Status kommt nicht vom Easy-Wi, sondern vom Plugin in WHMCS.

**Comment by florian96** [comment]
Do you speak German? I USE EASY-WI. I DONT USE WHMCS.

I downloaded from https://github.com/easy-wi/developer and i have Installed from https://github.com/easy-wi/developer
