### ISSUE TITLE
MasterApp error

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/developer#1040]
If you add Master Apps to a server and klick save, you get logged out and throw back to login page.

Errorlogs none.
Easy-WI 6.0.3
MySQL 5.5.54
PHP 5.6.30

**Comment by ulrichblock** [comment]
I am sorry, I cannot reproduce with my install. So it is likely that it is something specific to your mix of versions. Tested on:
Ubuntu 16.04
Easy-Wi 6.0.3
MySQL 5.7.20
PHP 7.0.22

Are you running on Ubuntu 14.04 or Debian 8?

Can you open the developer tools of your browser, open the network tab, tick the "preserve log" option and retry? Which request is redirecting?

**Comment by DAThosting** [comment]
Yes I running debian 8.

This `admin.php?w=ma&d=ad&id=15&r=ma` is the call I'll thrown back to login.php.

**Comment by DAThosting** [comment]
Bump

**Comment by MadMakz** [comment]
Can't confirm on current stable

**Comment by ulrichblock** [comment]
Maybe Cloudflare or similar in between and the combination was acting up.
