### ISSUE TITLE
BungeeCord kann keine Welten speichern ...

### ISSUE THREAD

**Issue by Tobi7889** [easy-wi/developer#1041]
... da die Nutzer nicht übergreifend agieren können.

Wäre es machbar, mehrere Server pro Systemnutzer ( usr3-16 ) zB. zu installieren und zu starten?

Dieses wäre für Minecraft Proxy Server sehr wichtig.

**Comment by ulrichblock** [comment]
Das müsste auf eine andere Art und Weise gehen. Erstelle eine neuen User und Gruppe.
Füge die betroffenen User wie usr3-16 dieser Gruppe hinzu.
Achte dabei darauf, dass es nicht die Primäre, sondern Sekundäre ist.

Konfiguriere das Speicherverzeichnis von BungeeCord auf das alle User zugreifen müssen auf das Home Verzeichnis des neuen Users und Gruppe.

Zur Sicherheit könnte man dem neuen User auch noch die Login möglichkeit entziehen indem man seine Shell auf /bin/false setzt.

**Comment by DAThosting** [comment]
Ich verstehe das Problem hierbei nicht ganz.
Wir hosten verschiedene BungeeCord Netzwerke problemlos.
