### ISSUE TITLE
API verweigert Zugriff

### ISSUE THREAD

**Issue by HerrLevin** [easy-wi/developer#1043]
Ich habe mich an diesem Script orientiert: https://easy-wi.com/de/api/allgemeines/

lediglich angeglichen wurde der Port auf 443 im fsockopen und vor den host wurde ein "ssl://" gepackt.

Egal wie ich es versuche, wird nur ein **403 Forbidden: No valid access data. No API user given. Request IP is: xxx** zurückgegeben.

Gab es irgendeine Änderung bei den Variablen, die nicht dokumentiert sind?

**Comment by ulrichblock** [comment]
IN dem Code wurde länger nichts gemacht. Ist derzeit auch schwer für mich nachzuvollziehen. Wurde die IP, mit der die Requests gemacht werden, in die Whitelist im Panel aufgenommen?

**Comment by ulrichblock** [comment]
Ich schließe, weil wohl Anwenderfehler und keine Antwort.

**Comment by HerrLevin** [comment]
Sorry, ich hatte keine Benachrichtigung bekommen. 

Ja, die IP wurde mit in die Whitelist aufgenommen. Ich habe es auch als localhost ausprobiert und es klappte nicht.
