### ISSUE TITLE
ProFTPD Fehler

### ISSUE THREAD

**Issue by PostAlone** [easy-wi/developer#1044]
Siehe Bild, was kann ich tun ?

![111111](https://user-images.githubusercontent.com/33464394/34069241-c236b78c-e24c-11e7-9734-2897ed9df5ba.PNG)

**Comment by PostAlone** [comment]
Help pls :S

**Comment by MadMakz** [comment]
check syslog oder proftp.log in /var/log

**Comment by PostAlone** [comment]
`2017-12-16 10:21:36,852 root601754.kms4.cc proftpd[20912] 2a01:367:c1f2::72: ProFTPD 1.3.5 (stable) (built Wed Jun 14 2017 09:03:26 UTC) standalone mode STARTUP
2017-12-16 10:21:40,053 root601754.kms4.cc proftpd[20912] 2a01:367:c1f2::72: ProFTPD killed (signal 15)
2017-12-16 10:21:40,054 root601754.kms4.cc proftpd[20912] 2a01:367:c1f2::72: ProFTPD 1.3.5 standalone mode SHUTDOWN
`

**Comment by PostAlone** [comment]
@MadMakz help me pls :)

**Comment by ulrichblock** [comment]
Du hast einen Fehler in der proftpd.conf . Welchen kann man aus der Ferne nicht sagen.
