### ISSUE TITLE
Steamcmd installer bug

### ISSUE THREAD

**Issue by ice123123123** [easy-wi/developer#1045]
Hallo,
ich habe heute versuch einen Ark Server zu installieren. 
Der Ordner wurde im masterserver erstellt. Diese bleibt jedoch leer nach der installation bzw Update des Servers,

Via htop konnte ich beobachten welche befehl ausgeführt wurde.:
"/home/easy-wi/masterserver/steamCMD/linux32/steamcmd +login anonymous +force_install_dir /home/easy-wi/masterserver/arkse/ +app_update 376030 validate +quit" über den User easy-wi.

Wenn ich diesen von Hand starte erhalte ich folgende Fehlermeldung:
"Redirecting stderr to '/home/easy-wi/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
[----] !!! Fatal Error: Failed to load steamconsole.so"

Daraufhin habe ich etwas im Internet geforscht und heraus gefunden das folgende Datei eigentlich gestartet werden müsste.:

"sudo -u easy-wi /home/easy-wi/masterserver/steamCMD/steamcmd.sh +login anonymous +force_install_dir /home/easy-wi/masterserver/arkse/ +app_update 376030 validate +quit"

Bitte um Hilfe dies im Interface zu Implementieren bzw um einen Fix. 

Vielen Dank

**Comment by MadMakz** [comment]
steamcmd.sh ist nur ein wrapper für linux32/steamcmd

i386 (aka 32bit) libraries müssen installiert sein. Bei debian ist das lib32gcc1, bei ubuntu lib32stdc++6

**Comment by ice123123123** [comment]
Hallo,

root@xxx ~ # apt install lib32gcc1
Reading package lists... Done
Building dependency tree
Reading state information... Done
lib32gcc1 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ice123123123** [comment]
Hallo,
root@Verteiler02 ~ # apt install lib32gcc1
Reading package lists... Done
Building dependency tree
Reading state information... Done
lib32gcc1 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ulrichblock** [comment]
Welches OS und Version?

**Comment by ice123123123** [comment]
Linux xxx 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

Easy-wi version: 6.0.3

**Comment by ulrichblock** [comment]
Der installer verwendet `steamcmd.sh`: https://github.com/easy-wi/developer/blob/master/stuff/methods/class_masterserver.php#L414

Bei dir hat die Installation vom Installer ggf. nicht funktioniert bzw. in deinem OS fehlen Binaries.
