### ISSUE TITLE
Update not possible

### ISSUE THREAD

**Issue by ferdl9999** [easy-wi/developer#1046]
Hello,

i wanted to update Easy-Wi from Version 5.30 to 6.0.0.
When i start the update, the following messages are appearing: 

Could not download the update.

Creating tempfolder tmp/
Downloading: 6.0.0.zip
Removed temporary files from tempfolder

![error](https://user-images.githubusercontent.com/6187784/34080006-00fcdabe-e338-11e7-9cfb-79785b12ac27.JPG)

Please help me, thanks

**Comment by ulrichblock** [comment]
If the download fails, update manually. Download the latest version, upload the files and execute `https://your-domain.tld/install/update.php`
