### ISSUE TITLE
Reseller bug

### ISSUE THREAD

**Issue by ice123123123** [easy-wi/developer#1047]
Hallo,
es ist derzeit möglich, dass ein Reseller auf alle normalen Benutzeraccounts Zugriff hat.
Dazu muss einfach der Link für den Switch durch die jeweilige Nutzerid ersetzt werden.

Bitte um Fix
Danke

**Comment by ice123123123** [comment]
Ich habe es behoben.
Ändere in der Switch.php Zeile 73 von
if ($row['accounttype'] == 'u') {

zu 

if ($row['accounttype'] == 'u' && $row['resellerid'] == $reseller_id) {

Mfg

**Comment by MadMakz** [comment]
Warum schließt du das ticket? Im code ist es nicht behoben! Das hier ist ein code tracker kein local-only support!

**Comment by MadMakz** [comment]
ty :)

**Comment by ice123123123** [comment]
pull request ist raus
