### ISSUE TITLE
Mobile CSS broken

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#1052]
EWI 6.0.0

The user dropdown is white on white and doesn't scroll makeing it impossible to reach the lower buttons (Profile, Logout) in case the underlying page isn' long enough.

![20171220_120714](https://user-images.githubusercontent.com/3930214/34204503-1ecd6ed4-e57f-11e7-8290-4ef407d182c7.png)

![20171220_120530](https://user-images.githubusercontent.com/3930214/34204509-2704a626-e57f-11e7-88ed-1dc71b069a1b.png)

**Comment by MadMakz** [comment]
_AdminLTE.css_ probably overwritten by

`.dropdown-menu li a{color:#fff}`

in _skin-<color>.css_

and

`<a href="login.php?w=lo" class="btn btn-default btn-danger" style="color:white;"><i class="fa fa-power-off"></i> Logout</a>`
should probably be `style="color:black;"` to make "Logout" readable?

![adminlte](https://user-images.githubusercontent.com/3930214/34217519-fdc7a83a-e5ab-11e7-960e-36392a443c06.jpg)

**Comment by MikkelDK** [comment]
Hi! - After updating of the Mobile CSS files.

**On the top - where "Language flags is located" - I can't click on it**
There is some lost "icons".

![screensh0t](https://user-images.githubusercontent.com/5301047/35186138-8483d4ea-fe0f-11e7-8ed4-7c4362e79fcc.png)

**Comment by ulrichblock** [comment]
Could be a caching issue. Font Awesome has been updated and you might have loaded a cached/invalid combination.
