### ISSUE TITLE
Serverstatus is in the future (or frozen?) 

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#1053]
6.0.0

Compare clock  top left, and in status line.

![20171220_120411](https://user-images.githubusercontent.com/3930214/34204569-69dd5948-e57f-11e7-8343-c00528028105.png)

**Comment by MadMakz** [comment]
Or the minutes are freezing?

Maybe Dublicate of #1038 (Definently NOT using WHMCS) 
![20171220_122310](https://user-images.githubusercontent.com/3930214/34204897-aefd041e-e580-11e7-8a59-0b69a019c85e.png)

**Comment by ulrichblock** [comment]
Not really frozen, but the converter into german format picked the month instead of the minutes.
