### ISSUE TITLE
Captcha setting missing

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#1055]
6.0.0

In `admin.php?w=se` gibt es keinen Menüpunkt für Captcha welches aber laut https://easy-wi.com/de/installation/web-interface/#captcha vorhanden sein sollte.

**Comment by ulrichblock** [comment]
Dann sollte ich die Doku mal anpassen. Den Menüpunkt sollte es nicht geben. Kannst auch du gerne mittels PR machen. Den Edit Button sollte es direkt in der Doku geben.

**Comment by MadMakz** [comment]
Oh okay, eventuell habe ich dies auch falsch interpretiert.

Allerdings wäre ein (nachträglich) konfigurierbares Captcha oder ReCaptcha ein nettes Feature

**Comment by gOOvER** [comment]
Bitte invidible reCaptch :blush:
