### ISSUE TITLE
Rust server startet nicht.

### ISSUE THREAD

**Issue by DenatorHD** [easy-wi/developer#1056]
Ich erhalte in der Konsole folgende Meldung:

Thread -> id: 7f11d578e700 -> priority: 1 
 EasyAntiCheat Scout Shutting Down

 (Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

 EasyAntiCheat Server Shutting Down

 (Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

 [Raknet] Server Shutting Down (Shutting Down)
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
 dlopen failed trying to load:
 steamclient.so
 with error:
 steamclient.so: cannot open shared object file: No such file or directory
 [S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
 InitServer: GameServer_Init returned false
eac_server.so [x64] :: OnUnload()

Was kann ich tun?

**Comment by ulrichblock** [comment]
Das scheint ein Problem mit Easy Anti Cheat zu sein. Was genau keine Ahnung, da ich selber kein Rust habe.
Am besten einmal in deren Forum mit dem Fehler nachfragen.
