### ISSUE TITLE
Game-/Voiceserver werden nicht angezeigt

### ISSUE THREAD

**Issue by Camby17** [easy-wi/developer#1059]
Ich habe sowohl einen Gameserver als auch einen Voiceserver hinzugefügt. Jedoch wird mir keiner von den beiden angezeigt. Es werden auch keine Benutzer angezeigt.

**Comment by Camby17** [comment]
Bzw auf dem Dashboard sehe ich diese, sie werden jedoch nicht als einträge in den einzelnen Sektionen aufgelistet

**Comment by ulrichblock** [comment]
Welche Easy-Wi Version wird benutzt? Welches OS mit welchem PHP und MySQL/MariaDB kommen zum EInsatz?

Was passiert, wenn der Debugger unter stuff/config.php aktiviert wird?

**Comment by Camby17** [comment]
Es lag scheinbar an meinem Webspace Anbieter
