### ISSUE TITLE
Kann Easy-Wi mit TSDNS für Versionen ab 3.1.x umgehen? 

### ISSUE THREAD

**Issue by tairogriz** [easy-wi/developer#1060]
Hallo, 
ich habe einige Probleme im Zusammenhang mit dem TSDNS System von Easy-Wi.
Ich habe als Fehler diese Änderung im Verdacht: https://support.teamspeakusa.com/index.php?/Knowledgebase/Article/View/332

LG 
tairogriz

**Comment by tairogriz** [comment]
Und wo werden die TSDNS Einträge von Easy-Wi überhaupt gespeichert?

**Comment by Lacrimosa99** [comment]
Hi,

ein TSDNS seitens Teamspeak gibt es nicht mehr... diese Funktion wurde mit der Version 3.1.x in das Hauptprogramm aufgenommen.
Möchtest du weiterhin dein TS mit einer Domain aufrufen, so musst du in deiner Domain/DNS Einstellung die nötigen Einträge setzen.
Dein Link schreibt alles nötige schon, was du dazu brauchst (Domain, PTR Records).

**Comment by gOOvER** [comment]
öhmmmmm   /ts-server/tsdns/ ??? Wenn das nicht läuft geht nichts mit TSDNS ;)  Ergo ist nicht nurt der Server von nöten. MIt 3.1 würde lediglich der aufruf via SRV Einträgen geändert ;) Aber nicht TSDNS  ;)

**Comment by tairogriz** [comment]
Erstmal Danke für die Antworten!
Ich habe beim überfliegen wohl irgendwie was falsch verstanden. 
Ich hatte es inzwischen auch selber hinbekommen, es steht ja auch ziemlich deutlich wie es gemacht werden soll.
@Lacrimosa99 Ich weiß zwar nicht woher deine Information stammt, aber sie scheint nicht korrekt zu sein.

**Comment by Lacrimosa99** [comment]
Meine Quelle: https://forum.teamspeak.com/threads/130464-TSDNS-Support

Hab TS3 Server laufen ohne dessen TSDNS Daemon ;)
Mit "PTR" ist eher die DNS Einträge gemeint...
