### ISSUE TITLE
Logout-Loop on "missing files" (favicon, gameicons)

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#1065]
**Getestet mit**
- Google Chrome (63.0.3239.132 (Offizieller Build) (64-Bit))
- EWI 6.0.4

**Es gibt 3 Auslöser zu einem Problem**

1.  Chrome sucht nach `/favicon.ico` wenn kein favicon definiert ist (das geschieht nach dem einloggen).

2. Auf der Loginseite (login.php) verweist Easy-Wi auf `images/favicon.png` dort existier aber nur .ico.

Daraus resultiert, auf Grund der .htaccess Limitierung, eine Logout-Loop da das favicon.ico via 302 auf login.php wirft, die login.php code-logik logt einen aber aus wenn man diese aufruft, ergo wird die gesamte Session ausgeloggt.

3. Desweiteren verhält es sich genau so bei anderen referenzierten aber nicht existierenden Dateien wie.z.B. fehlende Gameicons. Datei nicht gefunden -> 302 -> login.php = Session zerstört.

**Lösung**, images/favicon.png erstellen und global in allen templates definieren ggf. dazu /favicon.ico in .htaccess erlauben.
Letzteres wäre redundant aber ggf ein 403/404 zu erhalten ist eine sicherere Fallback alternative.

Generell ein 404 werfen bei allem das in erlaubten Verzeichnissen oder erwarteten Dateien nicht findbar ist wie bsp. bei images/games/icons/*.png

**Comment by ulrichblock** [comment]
Um welche Limits handelt es sich genau? Soweit ich das gerade überflogen habe, wird der Zugriff auf PHP Dateien beschränkt und der Zugriff auf die Ordner downloads|keys|languages|stuff|template|third_party|tmp

**Comment by MadMakz** [comment]
Problem wird hier `RewriteRule . /index.php [L]` sein denke ich.

**Comment by MadMakz** [comment]
Zeile 11 in `template/default/standalone/login.tpl` löschen, ist zwei Zeilen weiter dynamisch definiert.

Die Regel (in allen Templateheadern!)

`<link rel="shortcut icon" type="image/x-icon" href="<?php echo (isset($rSA['favicon'])) ? $rSA['favicon'] : 'images/favicon.ico';?>" />`

funktioniert nicht wenn das Feld favicon leer ist da _isset()_ nicht auf Inhalt _empty()_ prüft.
Hier ggf. `isset(` durch `!empty(` ersetzen oder mit _empty()_

**Comment by ulrichblock** [comment]
Danke für das komplexe Nachforschen. Ich habe die .htaccess angepasst und die Prüfung der Icons wie vorgeschlagen verbessert.
