### ISSUE TITLE
Gameserver abgestürzt

### ISSUE THREAD

**Issue by Camby17** [easy-wi/developer#1066]
Das Webinterface zeigt mir einen CSGO Server als abgestürtzt an, obwohl dieser läuft wenige Zeit später beendet er diesen automatisch.

**Comment by MadMakz** [comment]
Einen von mehreren CSGO?

**Comment by Camby17** [comment]
Nein ich habe nur einen csgo Server am laufen

**Comment by TechPandaIT** [comment]
Ist der Gameserver mit Branding konfiguriert, dieses aber nicht im Hostname angegeben?

**Comment by Camby17** [comment]
Nein Branding ist deaktiviert

**Comment by ulrichblock** [comment]
Dann gehe mal auf die Konsole, schaue nach der statuscheck.php und führe sie aus. Diese sollte dann Fehler anzeigen, sofern es sie gibt. Ggf. in der /stuff/config.php den debugger aktivieren.

Firewalls und fehlende PHP Funktionen sind die wahrscheinlichste Ursache.

**Comment by ManfredDoorstander** [comment]
Ich hab das selbe problem bloß ich weis nicht wie ich das fixe

![image](https://user-images.githubusercontent.com/63214527/180159484-898a2364-3204-4b4f-8782-7753219872ae.png)


Das sind die fehler, könnte mir da jemand helfen?
