### ISSUE TITLE
Abgestürzte Gameserver in % werden fehlerhaft berechnet

### ISSUE THREAD

**Issue by florian96** [easy-wi/developer#1067]
![image](https://user-images.githubusercontent.com/9999676/35122880-946c2800-fca0-11e7-8126-f9bd7b9b2aa1.png)

Sollte bei 66,67% sein.

**Comment by ulrichblock** [comment]
User oder Admin Bereich?

**Comment by florian96** [comment]
Admin Bereich. User hab ich nicht überprüft.

**Comment by fsedarkalex** [comment]
Ja der Bug ist auch schon lang da :D Ich hab den immer gekonnt ignoriert
