### ISSUE TITLE
Vorschlag: Dashboardoptimierung

### ISSUE THREAD

**Issue by fsedarkalex** [easy-wi/developer#1070]
Ich möchte vorschlagen, die Widgets im Dashboard nur rot/gelb zu färben, wenn auch Elemente betroffen sind.
Das würde das Dashboard übersichtlicher machen.

**Comment by GLITCH-Jan** [comment]
Ich guck mir das mal an ^^ dürfte nicht allzu schwer sein!

**Comment by AEon-Jan** [comment]
#done https://github.com/easy-wi/developer/commit/bddbbae8f1614743f08f791eac1bfff70febba94
