### ISSUE TITLE
Funktionsvorschlag: CPU Auslastung

### ISSUE THREAD

**Issue by florian96** [easy-wi/developer#1073]
Man könnte doch im WI die CPU Auslastung anzeigen lassen. Jetzt muss ich immer über SSH schauen.

**Comment by ulrichblock** [comment]
Das ist relativ viel Aufwand für nicht viel Nutzen. Typische Tools dafür sind Munin, oder gleiche eine Full Blown Monitoring Lösung wie Zabbix und Konsorten.
