### ISSUE TITLE
Voiceserver abgestürzt --> Neustart alle 10 Minuten

### ISSUE THREAD

**Issue by Barny93** [easy-wi/developer#1085]
Hiho!

Ich habe seit einiger Zeit das Problem, dass ein Voiceserver Master immer als abgestürzt deklariert wird und dann sämtliche virtuelle Server auf diesem Master neugestartet werden. Dies passiert aufgrund der Cronjobs alle 10 Minuten (?).

**Wann tritt der Fall ein:**
Habe ich auf einem Voiceserver Master lediglich einen Voiceserver am laufen, so läuft alles normal. Nun habe ich auf einem Voiceserver Master eine NPL-Lizenz eingespielt und einen zweiten virtuellen Voiceserver angelegt. Beide virtuellen Voiceserver werden angezeigt und laufen auch, jedoch werden sie nach 10 Minuten neugestartet. Nehme ich die Lizenz raus und lasse nur einen laufen, so verhält sich alles wie vorher (also normal).

**Was habe ich bereits versucht?**
Ich habe gehofft, dass sich das Problem mit dem Einspielen des aktuellen Updates behebt. Dies war aber leider ohne Erfolg, des Weiteren habe ich alles versucht was oben steht und konnte mir zusätzlich nun helfen, in dem ich eingestellt habe, dass die Server nicht neugestartet werden sollen. Ich habe die Funktion daher vollständig deaktiviert, aber das ist ja nicht Sinn der Sache, oder? Seitdem laufen die beiden Server aber ohne Neustart. 

Kann mir jemand bei dem Problem helfen und mir aufzeigen was ich falsch gemacht habe? Oder handelt es sich hierbei gar um einen Bug?

Viele Grüße,

Barny

**Comment by ulrichblock** [comment]
Das klingt sehr danach, dass der ts3 query überlastet ist. Whitelist geplegt? Cooldown beim Statuscheck ausprobiert?

**Comment by Barny93** [comment]
Vielen Dank für deine Antwort!

Der Teamspeakserver läuft auf dem selben Host wie Easy-Wi. Von daher bin ich jetzt nicht von einem Whitelistproblem ausgegangen. Dennoch hab ich die Liste kontrolliert und localhost ist definitiv eingetragen.
Was genau meinst du mit "ts3 query überlastet"? Ich konnte in den Logs nichts wirklich auffälliges finden.

Cooldown beim Statuscheck sagt mir leider auch nichts. Ich glaube, dass ich einer der kompliziertesten Fragesteller bin hier, sry! Freue mich aber über die Hilfe! Dankeschön!

**Comment by ulrichblock** [comment]
Mag sein, dass localhost eingetragen ist. Preisfrage ist, wie der TS3 angepingt wird. Wenn du nur eine IP und dann nur die externe angegeben hast, dann geht er über die Public IP ran. Dementsprechend muss diese dann auch in der Whitelist stehen.

**Comment by Barny93** [comment]
Das ist natürlich ein Argument, was ich erstmal so garnicht auf dem Schirm hatte. Ich habe die IP nun eingetragen, aber dennoch tritt der Fehler weiterhin auf.

Hast du vielleicht noch andere Vorschläge? Was ist mit dem anderen Punkt den du aufgezählt hattest? Ich kann leider immernoch nichts mit "Cooldown beim Statuscheck" anfangen, sry.

**Comment by ulrichblock** [comment]
https://easy-wi.com/de/installation/web-interface/#ts3-statuscheck-performance
