### ISSUE TITLE
Cronjobs funktionieren nicht

### ISSUE THREAD

**Issue by SenseiHiraku** [easy-wi/developer#1086]
Leider wird mir angezeigt, das alle Cronjobs von Easywi nicht funktionieren. Beim manuellen ausführen dieser, aktualisiert sich die Anzeige bei Statuscheck ebenfalls nicht. 
Und ja, die Cronjobs wurden richtig installiert.
Ich hoffe sie können mir weiter helfen.

MfG

**Comment by florian96** [comment]
Stimmen die Berechtigungen?

**Comment by ulrichblock** [comment]
stuff/config.php => $debug = 1; setzen und noch einmal manuell ausführen. Ggf. Fehler lesen, verstehen und beheben.
