### ISSUE TITLE
 Fehler beim Erstellen des Game Servers in SSH

### ISSUE THREAD

**Issue by patricknasci** [easy-wi/developer#1089]
Fehler beim Ausführen einer Gameserver-Erstellung. 
Server werden im Panel erstellt, aber nicht in SSH, es gibt .sh-Dateien im temporären Verzeichnis ssh

![08f7mge](https://user-images.githubusercontent.com/11508790/36305282-1732cea0-12fa-11e8-994f-85229e832e52.png)

![ajqfvrw](https://user-images.githubusercontent.com/11508790/36305280-15ac03da-12fa-11e8-9027-68028d5afa1c.png)

## Bewertung: 
Ausgezeichnetes Qualitäts-Panel nur dieser temporäre Fehler, bitte korrigieren Sie diesen Fehler.

**Extra:** Ich übersetze Easy-wi nach PT / BR. Es wäre möglich, dieses Flag im Flags-Ordner hinzuzufügen: https://gcp.cenathostbr.com/images/flags/pt.png

## Anfrage:
Es ist möglich, Hostnamen anstelle von IPs in Master-Servern mit dynamischer IP hinzuzufügen? also brauche ich diese Funktion.

**Comment by ulrichblock** [comment]
The first topic is likely a bug in your /etc/sudoers.

Dynamic IPs are not really an option. There are million ways to propagate the IPs. If the host remains the same and it should always listen, you might want to try using 0.0.0.0 which is normally the "any" case. I don't know how the individual Game Server will support it.

You could configure a fixed one for connection and as alternative use the 0.0.0.0. But if you SSH IP changes as well and you have N root server you are pretty much screwed.
