### ISSUE TITLE
Installing the old version (new files)

### ISSUE THREAD

**Issue by TaktischerSpeck** [easy-wi/developer#1091]
Hello,

i saw that when i install the webinterface it says:  Achtung Sie sind dabei eine veraltete Version von Easy-WI zu installieren. Die aktuelle ist: 6.0.4

but i did installed the newest version from github and the zip called 6.0.4 (installer thinks 6.0)

**Comment by TheCaptain97** [comment]
If you install the stable version you get version 6.0 but if you install the developer version you get version 6.04 which eliminates the error message
