### ISSUE TITLE
SSL für Webspaces

### ISSUE THREAD

**Issue by tairogriz** [easy-wi/developer#1092]
Hallo, hat jemand eine Idee, wie ich es dem Kunden ermögliche in Easy-Wi für seinen Webspace SSL optional zu aktivieren?
Danke

**Comment by florian96** [comment]
gar nicht. Easy-WI ist eher für Gameserver optimiert. Falls du vorhast, ein professionelles Hosting Unternehmen zu gründen, dann nutz auch ein Webinterface, dass dafür geeignet ist. Plesk z.b.

**Comment by tairogriz** [comment]
Ok danke.
