### ISSUE TITLE
Workshop problem with the panel

### ISSUE THREAD

**Issue by miniwinz78** [easy-wi/developer#1093]
Hello,

Since yesterday, I have a problem with downloading addons from the workshop, I look at a problem of permissions and user rights.
When starting a server, the server tries to download the addons, two or three get to download, the others have the same error message "download Failed! Input / Output Failure!".
I do not know how to solve this problem which is extremely annoying and which did not happen to me in the past with other panels.
Tell me what you need as information to find a solution to this problem, during this time, I remain at disposal.
[workshop_log.previous.txt](https://github.com/easy-wi/developer/files/1724124/workshop_log.previous.txt)
[configstore_log.txt](https://github.com/easy-wi/developer/files/1724135/configstore_log.txt)

**Comment by MikkelDK** [comment]
Do you have try and set this to be enable? `sv_debug_ugc_downloads 1`
