### ISSUE TITLE
Can´t use Easy-Wi with SSL Encription

### ISSUE THREAD

**Issue by TheCaptain97** [easy-wi/developer#1094]
Hi,
If I want to install Easy-Wi with a SSL Encription I can´t enter the website to continue the install process. If I use a not encrypted installation it works.

The error that I get while installing Easy-Wi and creating a SSL certificate is:
**problems making Certificate Request
139935399793920:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:../crypto/asn1/a_mbstr.c:1minsize=2**

Do you guys maybe know how I can fix this? I´m using a fresh installed VServer With Debian 8. Everything is up-to-date. And I dont really want to us a unsafe connection.

Kind regards

**Comment by TheCaptain97** [comment]
I tryed both versions btw. the stable and developers version. They both act the same.

**Comment by ulrichblock** [comment]
Self Signed certificates are **not** unsafe. The authority is unknown to the browser and thus it flags it as such. If you want a green browser use letsencrypt or a bought certificate manually.

**Comment by TheCaptain97** [comment]
That was never my question. I couldn't visit the website at all. But nevermind I fixed my problem already by myself. Thank you for closing this thread without a answer that's linked with my question...
