### ISSUE TITLE
SQL Problem

### ISSUE THREAD

**Issue by miniwinz78** [easy-wi/developer#1096]
overnight, I can not parametrer the panel, so I try a repair of the database, I enter the different sql request, but again repairing the database, nothing changes

Adding tables if needed.Repairing tables if needed.ALTER TABLE `api_import` CHANGE COLUMN `lastCheck` `lastCheck` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `badips` CHANGE COLUMN `bantime` `bantime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `easywi_statistics_current` CHANGE COLUMN `statDate` `statDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `feeds_news` CHANGE COLUMN `pubDate` `pubDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `feeds_settings` CHANGE COLUMN `lastUpdate` `lastUpdate` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `feeds_url` CHANGE COLUMN `modified` `modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `gsswitch` CHANGE COLUMN `port` `port` smallint(5) unsigned NULL DEFAULT NULL, CHANGE COLUMN `port2` `port2` smallint(5) unsigned NULL DEFAULT NULL, CHANGE COLUMN `port3` `port3` smallint(5) unsigned NULL DEFAULT NULL, CHANGE COLUMN `port4` `port4` smallint(5) unsigned NULL DEFAULT NULL, CHANGE COLUMN `port5` `port5` smallint(5) unsigned NULL DEFAULT NULL, CHANGE COLUMN `queryUpdatetime` `queryUpdatetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `jobs` CHANGE COLUMN `date` `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `lendedserver` CHANGE COLUMN `started` `started` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `lendsettings` CHANGE COLUMN `lastcheck` `lastcheck` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `lendstats` CHANGE COLUMN `lendDate` `lendDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `mail_log` CHANGE COLUMN `date` `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `page_comments` CHANGE COLUMN `date` `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `page_downloads` CHANGE COLUMN `date` `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `page_downloads_log` CHANGE COLUMN `date` `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `page_pages` CHANGE COLUMN `date` `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `rservermasterg` CHANGE COLUMN `installstarted` `installstarted` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `tickets` CHANGE COLUMN `writedate` `writedate` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `tickets_text` CHANGE COLUMN `writeDate` `writeDate` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `traffic_data` CHANGE COLUMN `day` `day` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `traffic_data_day` CHANGE COLUMN `day` `day` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `userdata` CHANGE COLUMN `updateTime` `updateTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `userdata_substitutes` CHANGE COLUMN `logintime` `logintime` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `userdata_value_log` CHANGE COLUMN `date` `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `userlog` CHANGE COLUMN `logdate` `logdate` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `voice_server` CHANGE COLUMN `queryUpdatetime` `queryUpdatetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP
ALTER TABLE `voice_server_backup` CHANGE COLUMN `date` `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP
Fixing data entries if needed.

**Comment by Lacrimosa99** [comment]
check your database config and sql entrys.
mysql error logs are also beneficial.

**Comment by miniwinz78** [comment]
new machine with default config and fresh install is same

**Comment by ulrichblock** [comment]
OS, MySQL or MariaDB? Versions?

**Comment by miniwinz78** [comment]
tested on debian 9 with mariadb 10.12.3 and ubuntu 16.04 with mariadb 10.12.3
