### ISSUE TITLE
Stoppen Gameserver *IP* not lended	

### ISSUE THREAD

**Issue by Gluheader** [easy-wi/developer#1097]
What should i do? When i lend a gameserver, its online with the right nummber of slots, the rcon password and gamepassword are good. everything work. But after a few minutes it is shutting down. 

Please Help!

**Comment by patricknasci** [comment]
I have the same problem  #1089

**Comment by patricknasci** [comment]
I have a problem similar to yours. #1089  
is not a folder on a server and after a few minutes with status off

**Comment by ulrichblock** [comment]
Well I guess there is no one on the server and thus it is shut down.

**Comment by Gluheader** [comment]
it goes down even if someone playing on server. I have turned off the option: "stop if emty" and it still goes down after 2 mins. don't know what to do

**Comment by ulrichblock** [comment]
Check the output of the execution of statuscheck.php . Probably there is the reaosn. Could be that you have visiblemaxplayers or similar configured in case fo HL2 games. Or you are trying a not supported game.
