### ISSUE TITLE
Avorion hinzufügen

### ISSUE THREAD

**Issue by Badeschlappen** [easy-wi/developer#1098]
Hallo,

wollte mal hier fragen ob es möglich ist ein SteamCMD spiel als Template zu laden und wenn ja wie, oder könnte es einer bereit stellen, für das Game Avorion ?

LG

**Comment by ulrichblock** [comment]
Schau dir ein Template wie css an und kopiere, was man braucht. Ändere den Rest.

Eine Erklärung der Parameter: https://easy-wi.com/de/admin/game-server/templates/
