### ISSUE TITLE
Minecraft Daten bitte upgraden/

### ISSUE THREAD

**Issue by xXjojojXx** [easy-wi/developer#1099]
und nach Möglichkeit bitte eine Anleitung für Neustart nach Absturz speichern
und die Cronjobs bitte die ich dafür benötige

**Comment by DAThosting** [comment]
> und nach Möglichkeit bitte eine Anleitung für Neustart nach Absturz speichern

Gameserver werden automatisch neu gestartet, sollten diese abgestürzt sein.
Dies geschieht über GameQ.

> und die Cronjobs bitte die ich dafür benötige

Einfach die nehmen, welche das Panel anzeigt?! Frage unlogisch...
