### ISSUE TITLE
könnte man bitte einen Button hinzufügen für Server Update + Mods

### ISSUE THREAD

**Issue by xXjojojXx** [easy-wi/developer#1100]
als Beispiel Ark Mods
und eine Möglichkeit bei Ark eine Domain als IP Adresse als hinterlegen
Cross Ark Möglichkeit das Webinterface einzuschalten und zu verbinden
und gemoddete Maps zu benutzen

**Comment by ulrichblock** [comment]
Ich verstehe das Deutsch hier nicht und werde mir die gleiche Mühe bei der Umsetzung geben, die beim Schreiben gegegeben wurde, also gar nicht.

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/developer/issues/1137
