### ISSUE TITLE
ARK map mods könnte mir einer dabei helfen

### ISSUE THREAD

**Issue by xXjojojXx** [easy-wi/developer#1103]
wie kriege ich das hin dass ich eine gemoddete Map benutzen kann
sprich wie man bei den Servern das so einstellt dass er eine ganz andere Map benutzt aus dem Shop

ich hätte eine Idee
wäre cool wenn man sowas integrieren könnte
würde das Bearbeiten deutlich einfacher machen
https://steamcommunity.com/sharedfiles/filedetails/?l=german&id=468312476

und Daumen hoch für das easy-wi ist echt nice

**Comment by Rustypredator** [comment]
Du kannst die map wie jede andere Ark Mod im "addons" bereich von easy-wi hinzufügen. Benutzer können dieses addon dann installieren. hier kannst du auch die map in den startparametern hinzufügen, also im addon template

**Comment by xXjojojXx** [comment]
startparametern hinzufügen, also im addon template
davon habe ich leider keine Ahnung wäre schön wenn mir jemand das erklären könnte

bitte nach Möglichkeit genau erklären da ich keine Ahnung habe gleich null Ahnung habe

**Comment by Rustypredator** [comment]
https://easy-wi.com/de/admin/game-server/addons/#startbefehl
https://ark.gamepedia.com/Server_Configuration

**Comment by xXjojojXx** [comment]
top thx

**Comment by Lacrimosa99** [comment]
Hatte es damals per Script gelöst... mehr dazu in meinem Github Channel "Ark Mod Manager".
