### ISSUE TITLE
Nach Ticket erstellung E-Mail an Panel Admin

### ISSUE THREAD

**Issue by Felix5566** [easy-wi/developer#1104]
Wie in der Überschrift beschrieben, das wenn ein Bentuzer ein Support Ticket schreibt das dann der Panel Admin eine E-Mail bekommt das der Admin schnell antworten kann.

Mit freundlichen Grüßen:
Felix5566

**Comment by florian96** [comment]
![image](https://user-images.githubusercontent.com/9999676/39436933-b9286ccc-4c9f-11e8-80bc-6791ad8ca95c.png)

Siehe Benutzerverwaltung des entsprechenden Admins
