### ISSUE TITLE
Webinterface kann keine User/Server mehr anlegen

### ISSUE THREAD

**Issue by Sheggymuh** [easy-wi/developer#1106]
Hallo,

Seit 2 Wochen hat mein Server oben genanntes Problem. Da ich diese Instanz nicht installiert habe, suche ich jetzt die Nadel im Heuhaufen. Ich gehe mal davon aus, dass der Systembenutzer des Webinterface keine Rechte mehr hat bzw. das Passwort falsch ist. Meine Frage ist, an welche Stelle das Passwort und der User festgelegt wird, damit ich dieses mal ändern kann.

**Comment by Lacrimosa99** [comment]
Schau ob der MasterUser sudo Rechte hat.
