### ISSUE TITLE
Unable to Add new apps to Game master & logout without error Message

### ISSUE THREAD

**Issue by Rustypredator** [easy-wi/developer#1107]
I am unable to add the Blightfall Modpack to my server.
I created the folder with the gamefiles in the /masterserver/ folder and added a new template.
but every time i try to add the blightfall template to my server, the panel just logs me out and redirects me to the login page. no error message, nothing. if there is any error happening, i would like to at least get a message and not just be logged out.
No templates work anymore, i cant add any template to the masterserver.

**Comment by MadMakz** [comment]
Might be #1065

Make sure there's a gameicon or patch manually (at last .htaccess)

**Comment by Rustypredator** [comment]
thanks... that seems to have done it. I could never have imagined, that it was the missing icon ^^
