### ISSUE TITLE
Minecraft (bungeecord addon Gameserver Template pls )

### ISSUE THREAD

**Issue by xXjojojXx** [easy-wi/developer#1113]
hat jemand Startparameter für mich für die aktuelle Version 1.12.2
Gameserver Template für  Minecraft bungeecord

nach Möglichkeit eine vorgefertigte da ich keine Ahnung von diesem Parameter 
vielen lieben Dank im voraus

**Comment by Rustypredator** [comment]
Ohne nachzuschauen, glaube ich, müssten die ganz normalen Startparameter für einen MC server funktionieren. Nimm einfach die vom Standard MC Template.

**Comment by xXjojojXx** [comment]
könnte mich jemand das eventuell anfertigen ich habe probiert ich bekomme es nicht hin
Gameserver Template  für  Minecraft bungeecord

**Comment by florian96** [comment]
Was klappt den nicht?

Die Standard Parameter reichen. Man kann es noch um " --nojline nogui" ergänzen, um die Farbcodes aus der Log zu entfernen.
