### ISSUE TITLE
Gameserver Template bitte alle mal Update

### ISSUE THREAD

**Issue by xXjojojXx** [easy-wi/developer#1114]
bitte alle mal Update
Minecraft 
Bukkit
spigot
ALLE

**Comment by MadMakz** [comment]
Für die nicht-minecraftler: Was muss geupdated werden? Haben sich Dateinamen / Ornerstrukturen geändert?

**Comment by PieKnu** [comment]
Wenn ich mich recht entsinne, wird Minecraft durch den Image Server mit aufgespielt. (Korrigiert mich wenn ich hier Falsch liege)

_Ansonsten liegt es nicht in den Händen der EasyWi Entwickler euren Content zu liefern. 
Mal im Ernst, ihr bezeichnet euch als "Server Administrator", seid aber nicht in der Lage mit eigenen Content umzugehen. 
Naja, dass soll jetzt hier kein "MiMiMi" sein, obwohl eigentlich ja doch._ 

Nein! Worauf ich hinaus möchte ist, dass du immer selber die Master Server auf dem Aktuellen stand halten kannst, indem du im Master Ordner "~/masterserver/spigot" Beispielsweise eine eigene Jar hoch lädst. Somit sind neue Server die erstellt oder Neuinstalliert werden, wieder auf dem Aktuellen stand. Zur Not kannst du ebenfalls andere Versionen als "Addon" einrichten, welche der Benutzer denn auswählt um die Gewünschte Version zu verwenden. (Sollten die Benutzer nicht in der Lage sein, die Symbolische Verknüpfung "Spigot.jar" in ihrem Ordner zu löschen bzw umzubenennen.)

**Comment by ulrichblock** [comment]
Wenn man eine Versionsauswahl will, bitte einen eigenen Imageserver bzw. Verzeichnis im Masterorder Pflegen. Dort dann alle Versionen in den Spigot, oder was auch immer Server packen. Im Folgenden Mod Befehle einrichten, die die Versionen starten und dem Anwender die Wahl im Panel geben.

Wir werden hier nicht tausende Versionen Pflegen, weil der nächste dann die 1001 haben will. Es gibt die aktuellste, sofern man automatisch bestimmen kann, dass es was neues gibt.
