### ISSUE TITLE
Nur 1 Gameserver?

### ISSUE THREAD

**Issue by Kastello1** [easy-wi/developer#1115]
Hey, ich habe easy - wi auf einem ubuntu server installiert.
Nun habe ich einen Gameserver angelegt, soweit so gut.
Möchte ich nun einen neuen Gameserver anlegen finde ich keinen Root Server mehr, auch wenn ich extra eingestellt habe, dass bis zu 10 Gameserver auf dem Root "verfügbar" sind.

Aktuelle Version: 6.0.4

**Comment by MadMakz** [comment]
Slots aufgebraucht?

**Comment by Kastello1** [comment]
Nope,
Slots 12/100
Ram 4GB von 12 GB

**Comment by Kastello1** [comment]
Okay Fehler gefunden ^^ 
Am Anfang nur 4GB dem "Master Server" vergeben.
Diese 4GB dem Gameserver zugewiesen, nachträglich beim Master Server aus den 4 Gb 12 gemacht und das hat er dann nicht geschnallt. Musste tatsächlich den Gameserver löschen damit es wieder geht.
