### ISSUE TITLE
Cronjobs Installationsart

### ISSUE THREAD

**Issue by cRUSHER-HLG** [easy-wi/developer#1116]
Hallo, 

Ich habe Easy-WI wie folgt installiert: 
1. Das Webinterface liegt auf unserem Webroot (gesonderter Server für Webseiten)
2. Der Gameroot wurde mit csgo als master installiert und es laufen erfolgreich 2 Gameserver (csgo) auf dem root. 

Das Problem besteht nun darin, dass er heute das Nacht wohl den csgo masterserver geupdatet hat aber die restarts der Server nicht geschafft hat. Die Cronjobs die benutzt wurden sind die lokalen und wurden auf dem Webroot installiert. Ich hoffe ihr könnt mir hier weiterhelfen.

**Comment by Bara** [comment]
Aktuell werden die Server (bei uns ebenfalls csgo) nicht restarted (bei uns der Fall), aber stelle doch zu einen bestimmten Zeitpunkt auto restart ein wie jeden morgen zu 6 Uhr.

**Comment by cRUSHER-HLG** [comment]
Kann man ja als Übergangslösung machen aber man sollte da dennoch nochmal nachschauen. Soll nicht Sinn der sache sein das mit dem Restart-Planer zu machen. Danke @Bara
