### ISSUE TITLE
EasyWi Bug

### ISSUE THREAD

**Issue by cRUSHER-HLG** [easy-wi/developer#1118]
Hallo, 

Ich versuche heute mehrmals einen csgo server zum laufen zu bekommen. 3 Stück laufen und die jeweiligen FTP Benutzer werden auch als Besitzer der Dateien angezeigt. Ich hatte einen 4 hinzugefügt und wieder entfernt. Diesen dann wieder hinzugefügt und als Besitzer der Dateien steht nun nicht mehr der selbe name wie der ftp benutzername sonder der ftp benuter von dem gelöschten Server. Diese Prozedur habe ich nun 4 Mal gemacht. mit user2-5 hats angefangen. Im Panel steht als Benutzer user2-9 aber im FTP-Client steht user2-5 als Besitzer. Das Problem hierbei ist, dass der Server permanent abstürzt. Die anderen 3 Server laufen stabil ohne abstürze.

MfG,
cRUSHERHLG

**Comment by florian96** [comment]
schau mal in der Log. Möglicherweise wird der Server durch Server Branding oder Slot Manipulation ausgeschaltet.

**Comment by cRUSHER-HLG** [comment]
Ja es handelt sich um Slot Manipulation da ich per sv_visivlemaxplayers mehr slots angezeigt hatte als in easy-wi eingestellt war.
