### ISSUE TITLE
User Create Error

### ISSUE THREAD

**Issue by Stendbay74** [easy-wi/developer#1119]
Hi, 
I have a problem with creating automatically users on game root server
I can update/add games on game master, the game master files are ok (in /home/server_user/masterserver/csgo/) 
but when i create user and create server to this user, server dont create the user folder in /home/userxx/ and dont copy master files to the new created server

OS: centos 7 (installer used for gameroot: "https://github.com/Lacrimosa99/installer") 

This installer work and install all requirements but i dotn know whats missing

I dont have this problem on Debian but i can't install Debian on my server because Debian dont support my network card. 

Sorry for my bad english :)
Please help, i can tell more info if you want

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/developer/pull/1130
