### ISSUE TITLE
How to get the SSH2 User and Password on Windows?

### ISSUE THREAD

**Issue by Feuerhamster** [easy-wi/developer#1121]
Hello,

i've installed EasyWi on Windows (Windows Server 2012 R2) in my Xampp Webserver.
The Webinterface running correctly. A Teamspeak 3 Server is already running on the same Server.
Now i will include the TS3 Server in EasyWi.
But i dont know the SSH2 IP.
How can i get there on Windows?

MfG Feuerhamster

**Comment by MikkelDK** [comment]
What i know, you can use Easy-Wi Controlpanel on windows => but you can't install "masterserver" on windows, only Linux. :)
