### ISSUE TITLE
Fehler - Beim löschen einer Datenbank wird der Benutzer nicht mitgelöscht.

### ISSUE THREAD

**Issue by PieKnu** [easy-wi/developer#1122]
Beim Löschen einer Datenbank wird lediglich die Datenbank gelöscht, nicht aber der Benutzer für die Datenbank.

**Comment by Bara** [comment]
Könnte man noch erweitern, die alten Benutzer für die privaten Server(?) mit ein "*-p" am Ende werden ebenfalls nicht gelöscht und existieren laut der passwd-Datei noch.

**Comment by florian96** [comment]
Das ist kein Bug sondern ein Feature.

Beim löschen kannst du einstellen, ob die Einträge nur aus der Datenbank gelöscht werden oder ob sie komplett entfernt werden. Nennt sich glaub ich "sicheres löschen"

**Comment by ulrichblock** [comment]
Welche Datenbank und Version wird denn verwendet? Welche Easy-Wi Version?

**Comment by PieKnu** [comment]
Ubuntu 14.04.5 LTS
Easy-Wi Version: 6.0.4
MySQL: 5.5.59
