### ISSUE TITLE
ARK SE Gameusersetting.ini Probleme

### ISSUE THREAD

**Issue by Alphascrypt** [easy-wi/developer#1123]
Moin Moin,
ich habe folgendes Problem unter Debian jessie.
Wenn ich änderungen in der gameusersetting.ini mache werden diese nach jedem neustart mit der standart config überschrieben. Ist das normal?

**Comment by Lacrimosa99** [comment]
Wie wurde die .ini bearbeitet?

**Comment by Alphascrypt** [comment]
Über easy-wi direkt und ftp. Die formatierung un UTF wude auch angepasst. Leider wird die ini immer wieder erneut überschrieben

**Comment by Alphascrypt** [comment]
Er überschreibt einfach ganz frech die gesamte ini.
Die defaultgameusersettings.ini wird nicht überschrieben.

**Comment by Lacrimosa99** [comment]
Wie ist der Pfad der Datei, welche überschrieben wird?
Bitte den gesamten Pfad ;)

**Comment by Alphascrypt** [comment]
/home/kd5-32/server/arkse/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

**Comment by Lacrimosa99** [comment]
Wie sieht dein ARK Template im WI aus?
Admin -> Gameserver -> Gameserver Template -> ARK

Das WI selbst überschreibt keine Dateien... das macht 99% ARK selbst.
Sprich... es ist irgendwo innerhalb der Datei ein Fehler.

**Comment by Alphascrypt** [comment]
<?xml version="1.0" encoding="utf-8"?>
<image>
  <steamgame>S</steamgame>
  <appID>376030</appID>
  <updates>1</updates>
  <shorten>arkse</shorten>
  <description>ARK: Survival Evolved</description>
  <type/>
  <gamebinary>ShooterGameServer</gamebinary>
  <gamebinaryWin/>
  <binarydir>ShooterGame/Binaries/Linux</binarydir>
  <modfolder/>
  <fps/>
  <slots>20</slots>
  <map>TheIsland</map>
  <mapGroup/>
  <cmd>./%binary% %map%?listen?MultiHome=%ip%?Port=%port%?QueryPort=%port2%?RCONPort=%port3%?MaxPlayers=%slots% -server -log</cmd>
  <modcmds/>
  <tic/>
  <gameq>arkse</gameq>
  <gamemod>N</gamemod>
  <gamemod2/>
  <configs>ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini full&#13;
ShooterGame/Saved/Config/LinuxServer/Game.ini full</configs>
  <configedit>[ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini] ini&#13;
MaxPlayers=%slots%</configedit>
  <iptables/>
  <protectedSaveCFGs/>
  <portStep>10</portStep>
  <portMax>3</portMax>
  <portOne>27015</portOne>
  <portTwo>27016</portTwo>
  <portThree>27017</portThree>
  <portFour/>
  <portFive/>
  <useQueryPort>2</useQueryPort>
  <protected>N</protected>
  <ramLimited>N</ramLimited>
  <ftpAccess>Y</ftpAccess>
  <workShop>N</workShop>
  <copyStartBinary>Y</copyStartBinary>
  <os>L</os>
  <liveConsole>Y</liveConsole>
  <steamGameserverToken>N</steamGameserverToken>
  <serverID>376030</serverID>
</image>

**Comment by Alphascrypt** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<image>
  <steamgame>S</steamgame>
  <appID>376030</appID>
  <updates>1</updates>
  <shorten>arkse</shorten>
  <description>ARK: Survival Evolved</description>
  <type/>
  <gamebinary>ShooterGameServer</gamebinary>
  <gamebinaryWin/>
  <binarydir>ShooterGame/Binaries/Linux</binarydir>
  <modfolder/>
  <fps/>
  <slots>20</slots>
  <map>TheIsland</map>
  <mapGroup/>
  <cmd>./%binary% %map%?listen?MultiHome=%ip%?Port=%port%?QueryPort=%port2%?RCONPort=%port3%?MaxPlayers=%slots% -server -log</cmd>
  <modcmds/>
  <tic/>
  <gameq>arkse</gameq>
  <gamemod>N</gamemod>
  <gamemod2/>
  <configs>ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini full&#13;
ShooterGame/Saved/Config/LinuxServer/Game.ini full</configs>
  <configedit>[ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini] ini&#13;
MaxPlayers=%slots%</configedit>
  <iptables/>
  <protectedSaveCFGs/>
  <portStep>10</portStep>
  <portMax>3</portMax>
  <portOne>27015</portOne>
  <portTwo>27016</portTwo>
  <portThree>27017</portThree>
  <portFour/>
  <portFive/>
  <useQueryPort>2</useQueryPort>
  <protected>N</protected>
  <ramLimited>N</ramLimited>
  <ftpAccess>Y</ftpAccess>
  <workShop>N</workShop>
  <copyStartBinary>Y</copyStartBinary>
  <os>L</os>
  <liveConsole>Y</liveConsole>
  <steamGameserverToken>N</steamGameserverToken>
  <serverID>376030</serverID>
</image>
`

**Comment by Alphascrypt** [comment]
https://pastebin.com/jX1mZL8B


`<?xml version="1.0" encoding="utf-8"?>
<image>
  <steamgame>S</steamgame>
  <appID>376030</appID>
  <updates>1</updates>
  <shorten>arkse</shorten>
  <description>ARK: Survival Evolved</description>
  <type/>
  <gamebinary>ShooterGameServer</gamebinary>
  <gamebinaryWin/>
  <binarydir>ShooterGame/Binaries/Linux</binarydir>
  <modfolder/>
  <fps/>
  <slots>20</slots>
  <map>TheIsland</map>
  <mapGroup/>
  <cmd>./%binary% %map%?listen?MultiHome=%ip%?Port=%port%?QueryPort=%port2%?RCONPort=%port3%?MaxPlayers=%slots% -server -log</cmd>
  <modcmds/>
  <tic/>
  <gameq>arkse</gameq>
  <gamemod>N</gamemod>
  <gamemod2/>
  <configs>ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini full&#13;
ShooterGame/Saved/Config/LinuxServer/Game.ini full</configs>
  <configedit>[ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini] ini&#13;
MaxPlayers=%slots%</configedit>
  <iptables/>
  <protectedSaveCFGs/>
  <portStep>10</portStep>
  <portMax>3</portMax>
  <portOne>27015</portOne>
  <portTwo>27016</portTwo>
  <portThree>27017</portThree>
  <portFour/>
  <portFive/>
  <useQueryPort>2</useQueryPort>
  <protected>N</protected>
  <ramLimited>N</ramLimited>
  <ftpAccess>Y</ftpAccess>
  <workShop>N</workShop>
  <copyStartBinary>Y</copyStartBinary>
  <os>L</os>
  <liveConsole>Y</liveConsole>
  <steamGameserverToken>N</steamGameserverToken>
  <serverID>376030</serverID>
</image>`

**Comment by Alphascrypt** [comment]
Er ändert die GUS ini immer noch ab in folgendes:
https://pastebin.com/AVyZpb9H

**Comment by Lacrimosa99** [comment]
Bitte auch mal die Änderungen zum Vergleich posten.

**Comment by Alphascrypt** [comment]
Das ist meine Standart GUS.ini bzw die die ich gerne nehmen würde :P 
https://pastebin.com/JBgSMRrM

**Comment by Lacrimosa99** [comment]
in deiner bearbeiteten Config passt die Formatierung nicht... deswegen wird diese immer wieder überschrieben.
