### ISSUE TITLE
[Gameserver] Fehler! Ihre Zugangsdaten sind nicht korrekt! 

### ISSUE THREAD

**Issue by D4rkD0me** [easy-wi/developer#1124]
Hallo,

seit geschätzt 6 Stunden bin ich nun dabei zu versuchen einen Gameserver zu installieren...
Ich habe proftpd von Easy-WI installieren lassen. Jedes mal wenn ich einen Gameserver installieren möchte, und starten möchte, passiert nix...
Sobald ich dann versuche die Konsole zu öffnen kommt folgendes:

Cannot download screenlog from server/spigot/screenlog.0

Ich bin ratlos und weiß nicht wohin mit mir...
Mit freundlichen Grüßen,
D4rkD0me

**Comment by Lacrimosa99** [comment]
OS + Version... Debug Log sowie Sys Logs.

**Comment by D4rkD0me** [comment]
Server: Ubuntu 16.04.1
System Log: https://hastebin.com/pisavifoyu.sql
Debug Log finde ich wo genau?

**Comment by Lacrimosa99** [comment]
Debug Log `../stuff/config.php` -> `debug = 1`.
Im Interface einen GS anlegen und dessen Output per Pastebin oder sowas mal schreiben.
Desweiteren mal die `/etc/sudoers` posten.
Wurde denn Java installiert (über den Installer)?

**Comment by D4rkD0me** [comment]
Log: https://hastebin.com/xawaqecosa.bash
Sudoers: https://hastebin.com/uwudevohun.nginx

Java wurde bei der Gameserver installation installiert, Jap.

**Comment by Lacrimosa99** [comment]
Sudoers sowie die Bash sieht gut aus und es sollte alles ausgeführt werden.
Log bitte löschen da PW´s und IP enthalten ist.
Was sagt die Prozessliste (top, htop, ps -aux) wenn du denn GS starten möchtest?
Es ist möglich, das der Ram entweder zu knapp bemessen ist oder im Masterserver die Datei für Spigot fehlt oder oder oder...

**Comment by D4rkD0me** [comment]
Wo genau kann ich die Prozessliste einsehen?
Die Server benötigten Datein sind im masterserver Ordner gespeichert (eula.txt, server.properties, spigot.jar).

**Comment by ulrichblock** [comment]
Frage 1: Wird der Nutzer vom Game Server auf dem System überhaupt angelegt?
Frage 2: Wenn der User existiert, kann er auf die Dateien im Master Order zugreifen?

**Comment by Sawndone** [comment]
Hallo,
ich klinke mich hier mal ein, da ich das selbe Problem habe.
Ich betreibe easy-wi auf CentOS 7 (64 Bit) welches mit dem Installer ohne Errors installiert wurde. Es sieht so aus, als ob der user nicht erstellt wird. Ich habe im systemlog geguckt und jedesmal wenn ein Server angelegt werden soll, kommt dieser Fehler (username des gamserver users ist user4): ` sudo[23422]: gameserver : unknown user: user4-6`
Ich habe auch schon versucht easy-wi auf Debian und Ubuntu zu installieren, jedesmal der selbe Fehler.
Mfg
Sawn

**Comment by Lacrimosa99** [comment]
@Sawndone bitte starte dazu ein neues Ticket da anderes Betriebssystem.

**Comment by nbhosting** [comment]
Moin hatte das Problem bist gestern auch, als ich für uns den Masterserver #2 einrichten wollte.
Bitte einmal unter App/Gamemaster -> Übersicht -> *Betreffenden Sever ->Ändern
 
Und dort in den Settings "UserIDs beginnend ab" in eine andere Zahl abändern.
Danach war es mir sofort möglich FTP User + Ordner + Server anzulegen.

MFG

**Comment by nbhosting** [comment]
Moin hatte das Problem bist gestern auch, als ich für uns den Masterserver #2 einrichten wollte.
Bitte einmal unter App/Gamemaster -> Übersicht -> *Betreffenden Sever ->Ändern

Und dort in den Settings "UserIDs beginnend ab" in eine andere Zahl abändern.
Danach war es mir sofort möglich FTP User + Ordner + Server anzulegen.

MFG
