### ISSUE TITLE
Voiceserver utf8

### ISSUE THREAD

**Issue by titi4242** [easy-wi/developer#1125]
Hallo,

Es gibt ein utf8-Codierungsproblem mit dem Voice-Server,
wie für mich mein, Hallo é, das Ergebnis in der Datenbank und auf dem ts3-Server ist Hallo &eacute;

herzlich

**Comment by Lacrimosa99** [comment]
Wahrscheinlich eher ein Datenbank Tabellen/Config Problem.
Wurde die Datenbank mit UTF-8 gestartet sowie dessen Datenbank konvertiert?
