### ISSUE TITLE
Help on my Panel.

### ISSUE THREAD

**Issue by David-1and1** [easy-wi/developer#1128]
Good morning, 
I am David from 2nd level hosting at 1&1 in zweibrucken, I use easywi for my team. Would it be possible to have a tutorial to install rootserver because when I click on the menu, I am returned to the home page. 
I'd also like to run the Network menu.

Good Day.

**Comment by Lacrimosa99** [comment]
A Manual has you here: https://easy-wi.com
Use the installer to install all required services.

**Comment by David-1and1** [comment]
It is possible to deprive each other of it for a commercial exchange ?
