### ISSUE TITLE
How to change floder list on fast dl 

### ISSUE THREAD

**Issue by flyer63** [easy-wi/developer#1131]
Hello everybody,
How do you change the list of folders synchronized for fast dl
Thank you for your help
Best regards

**Comment by Lacrimosa99** [comment]
All custom files will be synchronize... standard files will be ignored.

**Comment by RealNani** [comment]
It's only syncing for 1 file..

**Comment by flyer63** [comment]
You can't change ffile list ??

**Comment by Lacrimosa99** [comment]
what will you change and for what?
