### ISSUE TITLE
E-mail einstellung

### ISSUE THREAD

**Issue by MerlinBIOSMod** [easy-wi/developer#1133]
Und zwar sagt mir Easy wi das "X" bei den Email einstellungen obwohl alles eingestellt wurde. Könnte bitte mich jemand aufklären

**Comment by Lacrimosa99** [comment]
Hi,
zum einen was wird mit "X" gemeint?
Wo genau ist die Meldung?

**Comment by MerlinBIOSMod** [comment]
Mit dem X haben ich gemeint in den Email Einstellung wenn man den SMTP Testet und der Falsch ist.

Aber ich habe das Problem gelöst und bedanke mich trotzdem beim versuch mir zu helfen
