### ISSUE TITLE
EasyWi Webinterface Daten auf anderen Server übertragen

### ISSUE THREAD

**Issue by SenseiHiraku** [easy-wi/developer#1134]
Ich weiß, dies ist kein issue jedoch fand ich keine geeignete Stelle um meine Frage zu formulieren.
Und zwar wollten wir unseren V-Server wechseln, ich weiß jedoch nicht wie ich das ganze machen kann, ohne die ganzen Gameserver neu zu erstellen und das Webinterface neu zu machen.
Wir haben noch den AES Schlüssel, welcher am Anfang erstellt wurde. 
Wir benutzen Debian 8.

Ich danke für die Hilfe,
MfG

**Comment by Lacrimosa99** [comment]
Backup des alten Systems erstellen (/home, /var/www, Datenbank Dumps) und auf dem neuem System importieren.
Demnächst bitte im Gitter da es nichts mit dem Webinterface zutun hat.
Gruß
