### ISSUE TITLE
automatischer Logout nach Aktion

### ISSUE THREAD

**Issue by floder91** [easy-wi/developer#1135]
Hallo zusammen,

leider werde ich automatisch nach einer Aktion wie zb. Masterserver Update oder sonstige Dinge rausgeschmissen - zum Login fenster.

Woran kann das liegen und was kann ich ändern, damit das nicht mehr passiert.

Danke und MFG

**Comment by floder91** [comment]
Folgendes habe ich bereits gemacht.

Easy-Wi komplett neu installiert danach:
Updates eingespielt,
Datenbank vom alten System neu eingefügt,
Datenbank angepasst eingefügt (nur die Tabellen für Gameserver, Benutzer) eingefügt.

Alles ohne Erfolg.

**Comment by floder91** [comment]
Nochmal kurzes Update,

nachdem ich die .htaccess umgenannt habe scheint es zu laufen.
Aber das ist ja nicht Sinn und Zweck.
Was muss hier ggf. geändert werden?

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/developer/issues/1065

**Comment by floder91** [comment]
Darauf hätte man erstmal kommen müssen, danke dafür.
Ich habe die .htaccess angepasst (vom untern Verweis) bis jetzt scheint es zu gehen.

Die Frage ist nur warum ist das bei mir nicht mit im Update gewesen, oder wird allgemein sowas nicht mit geupdatet?
Danke :)

**Comment by Lacrimosa99** [comment]
Wird im nächsten Release mit kommen.
https://github.com/easy-wi/developer/compare/6.0.4...master
