### ISSUE TITLE
ARK - Cluster Server

### ISSUE THREAD

**Issue by floder91** [easy-wi/developer#1137]
Hallo zusammen,

ich weiß leider nicht ob das hier rein gehört.

Bei ARK gibt es die Möglichkeit ein Cluster Server zu erstellen wie kann ich das mit Easy-Wi realisieren?
_Habe auf meiner langen Suche auch nicht wirklich was gefunden jedoch weiß ich, dass die User des anderen Server dies nicht einlesen können. Beispiel: Server1 erstellt die Cluster Datei somit können Server2 und Server3 diese nicht lesen, da Sie nicht der Besitzer sind. Die Datei wird immer auf 700 geändert._

**Comment by floder91** [comment]
Hier noch ein Beispiel wie man das einrichten kann.

https://arkforum.de/thread/14862-einrichtung-eines-ark-clusters-cross-ark-3-varianten-linux-pc/

**Comment by floder91** [comment]
Ich glaub der Kollege in dieser Anfrage meinte genau das gleiche -> #1100

Es wäre schön wenn das irgendwie realisierbar ist.

Danke. :)

**Comment by Lacrimosa99** [comment]
https://arkforum.de/thread/14862-einrichtung-eines-ark-clusters-cross-ark-3-varianten-linux-pc/ - Variante 1 - mehrere ARK-Server im selben Server Verzeichnis

Startcommand anpassen.
Leider ist bei dieser Methode eine abfrage der restlichen Clusterserver nicht möglich, ob diese Online oder gestorben (offline) sind.

**Comment by adrijanb** [comment]
Gibt es hier was neues?

Also ist es möglich ein Cluster zu erstellen?

**Comment by sibbigali** [comment]
Hi , muss auch nochmal das Thema aufgreifen ,
is derzeit möglich mit Easy-Wi ein Cluster aufzusetzen mit mehreren Servern oder nur so das einer über die Seite gestartet wird und der Rest nicht sichtbar bleibt?

Mein Problem momentan is , das wenn ich ein Cluster einstelle , er die Daten nich laden kann wenn man den Server wechselt , wegen schreib Rechten etc.

Gibt es da nen Workaround ?

**Comment by AEon-Jan** [comment]
Hallo,

ich muss zugeben, dass ich in Bezug auf ARK nicht besonders erfahren bin.

Allerdings habe ich mir die Angelegenheit kurz angesehen. Ihr müsstet im Grunde das Gametemplate von ARK kopieren und es unter einem neuen Namen, wie zum Beispiel "CrossARK", wieder einfügen.

Anschließend sollten diese Kopien so modifiziert werden, dass der Startbefehl mit den Gängigen Tutorials übereinstimmt.

Ich habe mir das allerdings nicht im Detail angesehen und bin auch nicht tiefgehend mit der ARK-Thematik vertraut. Vielleicht findet sich jemand, der Zeit hat, dies zu testen oder mir dabei zu helfen, es einmal auszuprobieren.

Beste Grüße

**Comment by sibbigali** [comment]
Das Problem sind halt die Nutzerrechte , immer wenn der eine Server , zb. arkuser-1 etwas erstellt ,nimmt er der Gruppe die Rechte  , un damit kann arkuser-2 halt nix mehr mit der Cluster Datei anfangen , hab es schon mit mehreren Sachen rumprobiert , aber immer wenn der eine Server die wichtige Datei erstellt , kann der Rest nicht mehr drauf zugreifen.

Theoretisch müßte man eine möglichkeit haben, wenn ein Server User etwas erstellt , durfen Gruppenrichtlinien nicht entfernen werden.

Oder  anderes.

**Comment by sibbigali** [comment]
Andere Frage: is es möglich den User den man erstellt ,Hardcodet für die Restlichen als Besitzer fest zu legen also 

Server wird per Interface erstellt , danach sagt man aber zB MCUser 1 is auch der User für Server2 Server3 etc ?
