### ISSUE TITLE
Error: CSFR protection token timed out or does not match.

### ISSUE THREAD

**Issue by Ambrika** [easy-wi/developer#1141]
Hello all!

I install easy-wi (web&gamemaster) and my problem is:
i try update the master app (samp) and the error is:
Error: CSFR protection token timed out or does not match.

**Comment by Lacrimosa99** [comment]
Check Webserver Logs.

**Comment by Ambrika** [comment]
I have a lot of try and i buy new & new vps and i install with installer but same as error.
