### ISSUE TITLE
Minecraft Server Abgestürzt - Sind aber online

### ISSUE THREAD

**Issue by gaRt3n** [easy-wi/developer#1142]
Ja moin,

interessanterweise werden meine MinecraftServer als abgestürzt dargestellt. Diese sind jedoch online und arbeiten ohne Probleme.

Würde dort autoreboot eingeschaltet sein, dann würde der dauerhaft rebooten.

Ist evtl die Query Setting falsch?

**Comment by Lacrimosa99** [comment]
Wurde die Firewall, Server Config, Server Verbindungen geprüft?
Desweiteren auch mal die Webserver Logs durchforsten um etwaige Fehler des Webservers auszuschließen.

**Comment by gaRt3n** [comment]
Hallöchen,
die Dienste befinden sich auf dem gleichen Server wie das Webinterface.

Der Webserver spuckt auch falsche query Versuche aus? Muss ich sofort überprüfen. Daran habe ich jetzt garnicht gedacht

**Comment by Lacrimosa99** [comment]
Wurde der Fehler gefunden und behoben?

**Comment by gaRt3n** [comment]
Ich finde dazu nichts in den normalen Logs. Diese Werden weiterhin als offline dargestellt. Neu angelegte Server werden richtig als online/offline dargestellt.

![image](https://user-images.githubusercontent.com/1362494/44216563-791d2980-a175-11e8-8419-fbd7aa34a684.png)

**Comment by Lacrimosa99** [comment]
Localhost kannst du dem Masterserver geben... die GS brauchen schon die Öffenliche IP.

**Comment by gaRt3n** [comment]
Ne hat schon so seine Richtigkeit, dass diese den localhost haben.

**Comment by gaRt3n** [comment]
Nein leider nicht...

**Comment by Lacrimosa99** [comment]
Dann kann ich dir leider nicht helfen da wir selbst keine MC Server hosten.
Wenn die Query abfrage ins nichts verläuft heißt das meist:

- Fehlkonfiguration des Servers (Config oder rcon fehlerhaft)
- Port stimmt nicht oder ist belegt
- Routing zum betreffenden Gameserver fehlerhaft oder geblockt
