### ISSUE TITLE
ts3 kann nicht installiert werden

### ISSUE THREAD

**Issue by hendrikator** [easy-wi/developer#1144]
Hallo ich habe nach der Installation von https://www.youtube.com/watch?v=q5nKN4n5zyc den Server isntallieren wollen leider ohne erfolg 

Fehlermeldung ist folgende

Fehler
SSH2 IP, Queryport

kann es sein das ein server nicht gleichzeit auch als gameserver tätig sein kann?

**Comment by Lacrimosa99** [comment]
Bitte das Installer Script verwenden anstatt veraltete Videos auf Youtube.
https://easy-wi.com/de/installation/web-interface/

**Comment by SamuelNitsche** [comment]
Leider tritt exakt dieser Fehler auch bei dem Installer Script auf.
