### ISSUE TITLE
Resellers won't get e-mails

### ISSUE THREAD

**Issue by chronicals** [easy-wi/developer#1145]
Resellers are unable to receive e-mails from the webpanel.

This includes, registration, password forgotten. etc. It simply won't send anything and event won't show anything in the mail log.

**Comment by chronicals** [comment]
Error log is completely empty. Any ideas?

**Comment by Lacrimosa99** [comment]
Running a local Mailserver on the same System?
Easy-Wi will not installing a Mailserver... that must you self do.

**Comment by chronicals** [comment]
It's not a problem with email delivery. I'm running a server with working e-mail server as well as working sendmail php extension.

I can receive all kinds of emails for accounts that are listed as administrator or user, no problems at all under my own domain/mailserver, gmail, gmx.de, web.de, hotmail, etc.

But when for example requesting a passwort reset url or sending a account created mail or some other template email, it simply send any email. It won't even attempt doing so or show an attempt in the e-mail log, that you can see inside of the admin area.

So there is an issue with sending e-mails to reseller accounts.

**Comment by Lacrimosa99** [comment]
What say´s your Webserver Logs in `/home/easy-wi/logs`?
