### ISSUE TITLE
FTP can't get used

### ISSUE THREAD

**Issue by TivogGaming** [easy-wi/developer#1146]
Hello,

I installed today easy_wi on my root server. Its working fine because I can add, delete and edit users... BUT the WebFTP. For example: When I try to edit the EULA.txt for minecraft is there standing: Error: FTP Access

What can I do?

For more details, just ask me what I have to give ^^

Regards,

Marvin

**Comment by Lacrimosa99** [comment]
If your Gameserver User exist and have all Permissions?
Check if exist and what your ProFTP Server Logs say.

**Comment by TivogGaming** [comment]
Hello @Lacrimosa99,

thanks for the respond! I would like to know where I can see the logs :) As well how to see if the user have all permissions.

regards

**Comment by Lacrimosa99** [comment]
first question: how was the interface installed?
second question: what say your proftp logs?
third question: exist your game server user whom you like access?

**Comment by TivogGaming** [comment]
1: I was going step by step trough the install guide from the official website
2: (look picture)

Where can I see if the gameserver user exists in the system? 
![image-2018-08-16](https://user-images.githubusercontent.com/41875502/44229568-c19a0e80-a198-11e8-8018-cd2dabdc3701.jpg)

**Comment by Lacrimosa99** [comment]
without any clue, I can not help you....
I continue to think that it is a missing library.

**Comment by TivogGaming** [comment]
Do you need any log files uploaded from me? I want that this works 🙂

**Comment by Lacrimosa99** [comment]
that is not my job to do your job.
We provide assistance and solutions ... it has now been pointed out several times that the user does not exist.
Then please check why this is so by searching the logs.

**Comment by TivogGaming** [comment]
Really? It is my job to fix it self? I would love to do that, if I just know how... Don't you have for me a log file who I have to look to? Because I'm not a member of the company, I'm a consumer, who wants to use your service. 

I don't ask you to log you in my root, I ask if you for help, what file I need to watch to.

**Comment by TivogGaming** [comment]
No, it will be come good, I will switch to TekLab. Maybe there will get helped if I have an issue...
