### ISSUE TITLE
Bei Installation von Addons für Minecraft (Problem)

### ISSUE THREAD

**Issue by Sakora86** [easy-wi/developer#1147]
Guten Tag,

folgendes Problem hab ich sobald ich ein Addon für Minecraft in den server Ordner via dem Addon Button hinzufüge taucht folgendes Problem auf:

Addon wird hinzugefügt, jedoch macht der Server alle 3-4 minuten einen Save der ganzen daten, dies hat zur folge das alle Spieler rausfliegen, es gibt kein absturtz nur ein Server neustart hat dies zur folge.

Ich bitte einmal um behebung dieses Problems :)

**Comment by Lacrimosa99** [comment]
Dazu bitte Logs... ohne Logs, welche MC Version, WI Version, OS usw können wir das Problem nicht nachstellen.

**Comment by Sakora86** [comment]
welche Logs genau, von MC direkt gabs ja keine fehlermeldung, daher die Frage.

Wi Version ist es die 6.0.4 OS : Debian Stretch amd64

**Comment by Lacrimosa99** [comment]
Um was für eine MC Version geht es und um welches Plugin dazu?
Versuche auf meiner Testumgebung deinen Fehler 1:1 nachzustellen.

**Comment by Sakora86** [comment]
Also bei mir tratt es bei jeder MC Forge Version auf und es betraff alle Plugins seis Dynmap, Worldedit oder Traincraft. 

Hoffe konnte damit helfen, aber danke für die reproduktion.

**Comment by Lacrimosa99** [comment]
Konnte deinen Fehler nach 2 Tagen in verschiedenen Konstellationen nicht nachstellen.
Getestet mit Debian 8/9, Ubuntu 16.10/17.04/18.10, CentOS 7.
Folgendes Plugin wurde zum Test verwendet: ClearLag, WorldEdit 6.1.8
Minecraft Versionen: Bukkit, Spigot

**Comment by Sakora86** [comment]
hmm bukkit, spigot könnt ich ja mal versuchen zu nutzen hab bisher immer nur das normale forge genutzt mal schauen was passiert bei mir, wenn spigot und bukkit nutze aber so auch keine ahnung was es sein kann bei mir?

**Comment by Lacrimosa99** [comment]
Leider keine Ahnung was es sein kann... wurde das Problem mittlerweile gelöst?

**Comment by Sakora86** [comment]
Ja Problem wurde behoben jedoch lag da ein komplett anderes problem vor hatte einen kleinen fehler bei der erstellung des Gameservers gehabt der diesen Fehler verursachte ohne den tollen server.properties datei verursacht er bei mir diesen Fehler, da auf irgendtwelchen Grund die server.properties jedesmal in den Mods Ordner landete statt vorne im Hauptordner damit war dann das Problem gelöst.
