### ISSUE TITLE
Support for TeaSpeak

### ISSUE THREAD

**Issue by berci07** [easy-wi/developer#1148]
Can we get TeaSpeak (www.teaspeak.de) support  for Voiceservers? :)

**Comment by chronicals** [comment]
Waiting for support as well. Sadly TeaSpeak refuses to implement support.

**Comment by MikkelDK** [comment]
@chronicals - Because they never has hear about "easy-wi" ;) so someone needed to "code" ownself.. for getting it works on Easy-Wi! ;)

**Comment by chronicals** [comment]
@MikkelDK I know, even though this is such a nice interface ;)

The TeaSpeak developer says to the issue that...

> Broken pipe leads to a connection which has been disconnected remotely that mean that you lovely easy wi closes the connections to early or something else. Please contact the easy we support.

**Comment by chronicals** [comment]
It seems to be an EasyWI problem here. Query responses from TeaSpeak seem to be identical to the ones TeamSpeak gives.

Always getting error messages like this, even with the same line endings ( \n ) used in TeamSpeak.

It seems to be an EasyWI Issue where EasyWI tries to check something an disconnects without any reason.

**Comment by chronicals** [comment]
For anyone following, we found the solution:

### In short: The solution seems to be to choose the following expected default line ending: 

> \n\r

[See here in detail](https://forum.teaspeak.de/index.php?threads/easywi-error-log.915/post-7183)

#close
