### ISSUE TITLE
Darstellungsfehler (Umlaute) in Support-Tickets beheben

### ISSUE THREAD

**Issue by IceTecX** [easy-wi/developer#1149]
Leider gibt es einen Fehler bei der Darstellung von Umlauten in den Support-Tickets.
Screenshot:
![Screenshot](https://abload.de/img/easywi_fehlerpwie4.png)

**Dies liegt daran, dass beim Absenden eines Support-Tickets der Text mit der Funktion: _htmlentities_ bearbeitet wird ([Hier](https://github.com/easy-wi/developer/blob/17eb07b8f4ccc8f23b1a1d6cfdd3081de30e9d38/stuff/user/userpanel_tickets.php#L124)) bevor, dieser in die Datenbank geht, jedoch nicht zurück codiert wird, wenn dieser wieder aus der Datenbank ausgelesen wird.**

Fehlende Funktion ist: *html_entity_decode*

Diese müsste im Userpanel-Template einfügt werden an folgender Stelle: [LINK bitte klicken](https://github.com/easy-wi/developer/blob/17eb07b8f4ccc8f23b1a1d6cfdd3081de30e9d38/template/default/user/userpanel_tickets_view.tpl#L51)
**sowie**
im Adminpanel-Template an folgender Stelle: [LINK bitte klicken](https://github.com/easy-wi/developer/blob/17eb07b8f4ccc8f23b1a1d6cfdd3081de30e9d38/template/default/admin/admin_tickets_view.tpl#L50)

### 😃 Beispiel:
```
<?php
echo $table_row['ticket'] . "<br>"; 
echo html_entity_decode($table_row['ticket']);
?>
```
erzeugt folgende Ausgabe:

![ScreenshotNo2](https://abload.de/img/easywi_fehler2nqekl.png)

Wichtig ist also folgender Code:
```
<?php
echo html_entity_decode($table_row['ticket']);
?>
```

Vielleicht konnte ich ja helfen. 😎

**Comment by Lacrimosa99** [comment]
Sollte behoben sein.
Danke für den Fix.
