### ISSUE TITLE
Spezielle Charakter werden in der Config nicht escaped

### ISSUE THREAD

**Issue by SamuelNitsche** [easy-wi/developer#1157]
Ich habe in der Konfiguration in einem Feld einfaches Anführungszeichen (') verwendet. Nun bekomme ich beim Aufruf des Panels folgenden Fehler
```
Parse error: syntax error, unexpected 's' (T_STRING) in /home/easywi_web/htdocs/stuff/config.php on line 10
```
Hab den Fehler manuell behoben indem ich meine config.php angepasst habe. Ich denke mit `htmlspecialchars()` sollte das ganze schnell behoben sein.

**Comment by Lacrimosa99** [comment]
> Ich habe in der Konfiguration in einem Feld einfaches Anführungszeichen (') verwendet.

Zum einen bitte Ausführlicher … was, wie wo wurde wann und warum verwendet.

**Comment by SamuelNitsche** [comment]
Das Zeichen wurde in während der Konfiguration in dem Feld für die Beschreibung des Panels verwendet. Genaueres kann ich im Moment leider nicht sagen, da ich das Panel nicht mehr installiert habe. Falls weitere Informationen benötigt werden kann ich aber gerne die Installation noch einmal machen und das genaue Feld zeigen.

**Comment by chronicals** [comment]
Haben teilweise auch den Fehler, dass wenn Config Dateien bearbeitet und gespeichert werden, auf einmal die Hälfte der Config fehlt.

Glücklicherweise hatten wir Backups, verwenden jetzt nur noch den File Browser.

**Comment by Lacrimosa99** [comment]
> Haben teilweise auch den Fehler, dass wenn Config Dateien bearbeitet und gespeichert werden, auf einmal die Hälfte der Config fehlt.
> 
> Glücklicherweise hatten wir Backups, verwenden jetzt nur noch den File Browser.

Wahrscheinlich ein Spiel und daher falscher Tread ;)
Bitte neuen Starten wenn keiner offen ist mit dem Problem.

**Comment by gOOvER** [comment]
DAs problem ist, das kein   '   verwendet werden darf. Ich hatte den Fehler auch bereits
