### ISSUE TITLE
Ubuntu - MC GS reinstall

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#1162]
Minecraft GS reinstall ohne Funktion unter Ubuntu 14.04, 16.04, 18.04.
Fehler im exec/Ausführungs Script (Shell Script)?

**Comment by Lacrimosa99** [comment]
aktuelle Permissions der Datei im temp Ordner ``

**Comment by Nexus633** [comment]
Minecraft lässt sich unter Ubuntu Neuinstallieren. Hier sind keine Probleme vorhanden. Dieser Bug wurde bereits behoben. Bitte schließen.
