### ISSUE TITLE
Voiceserver Import

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#1164]
nach hinzufügen des Voiceservers ins Interface, wird die Instanz gestoppt.
Nach neustarten des TS Masters ist ein Import möglich.

**Comment by nokia001** [comment]
Das Problem kann ich bestätigen. (Freie Version)
Nur kommt ein weiteres hinzu. Nach dem Neustart mit ./ts3server_minimal_runscript.sh sieht man ja die kompletten infos vom Server.

Wenn man jetzt den Server hinzugügen möchtet, Klappt dies nicht. EasyWi meldet "bind to Port fehlgeschlagen".

Kann mit das nicht erklären. Wo liegt der Fehler.
Ist es möglich, dass schon ein Virtueller Server gestartet ist und deshalb easywi nicht mehr drauf verbinden kann? Ist nur eine Vermutung.

**Comment by Lacrimosa99** [comment]
> Wenn man jetzt den Server hinzugügen möchtet, Klappt dies nicht. EasyWi meldet "bind to Port fehlgeschlagen".

Problem hierbei ist, das du anstatt des "minimal" Scriptes, das Hauptstartscript "ts3server_startscript.sh" ausführen musst.
