### ISSUE TITLE
OVH Gameroot

### ISSUE THREAD

**Issue by ZockerCloud** [easy-wi/developer#1169]
Hallo habe folgendes Problem.
OVH Gameroot mit Proxmox.
Der Server läuft auf einer KVM Maschine.
Leider kann ich keine Master Server hinzufügen. 

×
Fehler
SSH2 Benutzername, Public Keyfile benutzen, SSH2 Passwort

Habe schon das Internet durchforstet aber nichts hilfreiches gefunden.

**Comment by asdfxD** [comment]
Same...

Hab die Daten korrekt eingetragen und bekomme auch diesen Fehler.

×
Fehler
SSH2 Benutzername, Public Keyfile benutzen, SSH2 Passwort

**Comment by ZockerCloud** [comment]
Es soll wohl mit OVH zusammenhängen.
Aber es muss doch eine Lösung geben.

**Comment by asdfxD** [comment]
Also bei mir gehts jetzt, hab den 2.4 installer geladen, aufn root hochgeladen und mit diesem installiert.

**Comment by asdfxD** [comment]
Nein, ich teste das easy-wi auf einem home server.

**Comment by asdfxD** [comment]
Nun steh ich vor einem weiteren Problem. Wenn ich ein Gameserver adden will, alles einstelle und unten auf hizufügen klicke, passiert einfach nichts XD

**Comment by ZockerCloud** [comment]
Der 2.4 installer funktioniert auf den OVH Game Servern auch nicht. Keine Verbindung.
/home/easywi_web/htdocs/third_party/phpseclib/Net/SSH2.php on line 1011

**Comment by asdfxD** [comment]
Dann würde ich mal OVH Support anschreiben.

**Comment by Lacrimosa99** [comment]
@ZockerCloud dann bitte den Output des Installers prüfen, welches Packet er nicht installieren konnte.
Desweiteren welches OS kommt zum Einsatz und in welcher Version?

**Comment by Lacrimosa99** [comment]
Da hier keinerlei Antwort mehr kommt.. Closed
