### ISSUE TITLE
gameserver template factorio

### ISSUE THREAD

**Issue by AsaTyr2018** [easy-wi/developer#1170]
good day,

i´m looking for someone that has experiance in this. i need to setup a gameserver template for factorio.
its not a steamcmd game. so i need to store the files on the server in masterserver i guess.

now the tricky part. factorio needs an existing savegame to run the server in headless. so the start parameter need to have a variable that can be altered by a user itself. like "savegame name" 

the next part is that factorio itself stores savegame files outside the game root. this need to be altered too. 

any ideas?

Thanks a lot for the help in advance!

**Comment by boyfromgermany** [comment]
I have this Problem to, have you found a Solution ?

**Comment by AncientEntity** [comment]
You could have a cronjob that every 5-15 minutes generates a new world in the template so almost everybody gets a different map.

**Comment by Da-Geek** [comment]
The Factorio Dedicated Server(called headless by Wube Software) looks like it can be downloaded from https://factorio.com/get-download/stable/headless/linux64
But it is also available via Steam https://steamdb.info/app/427520/info/

I will check if I can get the Steam Version to run as a dedicated server, with some simple cmd line options, and If I can work it out, I will create a game definition that can be imported into easy-wi

Myself and @TheRealMrBC are working on trying to get this issue solved as well as trying to get some new Templates added for updated Minecraft versions as well as some common ModPacks fro Minecraft

**Comment by Pr0mises** [comment]
@Da-Geek Are there any updates, of your current state?

**Comment by Lacrimosa99** [comment]
any changes or can i close?
