### ISSUE TITLE
Game Servers not deleting

### ISSUE THREAD

**Issue by Roshke** [easy-wi/developer#1172]
Hi,

I'm encountering an issue where when I try to delete a game server safely or in any way it doesn't get removed from the Master (VPS). I have no issues with adding or editing users.

in /stuff/methods/class_app.php this segment isn't properly executed
```
   private function linuxDeleteUserGenerate ($userName) {

        $this->shellScripts['user'] .=  'if [ "`id ' . $userName . ' 2>/dev/null`" != "" ]; then' . "\n";
        $this->shellScripts['user'] .=  '${IONICE}nice -n +19 sudo /usr/sbin/userdel -fr ' . $userName . ' > /dev/null 2>&1 ' . "\n";
        $this->addLogline('user.log', 'User ' . $userName . ' deleted');
        $this->shellScripts['user'] .=  'fi' . "\n";

    }
```

I've verified with echo in this function that it gets executed but the "shellScripts" and the "addLogline" doesn't for some reason.

**Comment by Lacrimosa99** [comment]
pls more informations to your system..
