### ISSUE TITLE
Master Apps aktualisieren / MC bleibt auf 1.12.2

### ISSUE THREAD

**Issue by loxonoff** [easy-wi/developer#1173]
Hallo
Ich habe gerade die easy-wi version 6.0.4 frisch auf einem Testsystem installiert.
Gamehost und WI jeweils auf einem eigenen Betriebssystem => Debian 9.5/64

Dort habe ich nun das Problem, dass über das WI, über den Menüpunkt 'Master Apps aktualisieren' , kein Updates für den Minecraft-Server heruntergeladen wird.

Ich bin selbst ein absoluter HTML - PHP - Noob und kann nur grobe Schätzungen anstellen.
Allerdings habe ich unter /home/easywi_web/htdocs/stuff/methods die php-Datei 'queries_updates.php' gefunden.

Darin scheint eine alte URL für die Ermittlung des aktuellen Versionsstandes verwendet zu werden.
Es wird "http://s3.amazonaws.com/Minecraft.Download/versions/versions.json" abgefragt, allerdings liegt dort nur eine versions.json, in der die Serverversion bis 1.12.2 vermerkt ist.
Die entsprechende Datei liegt seitdem mit neuem Namen auf folgender URL: "https://launchermeta.mojang.com/mc/game/version_manifest.json"

Ich hatte zunächst selbst versucht etwas in der queries_updates.php anzupassen, allerdings kommt dabei unglücklicherweise zum tragen, dass ich diesbezüglich (wie oben schon beschrieben...) ein absoluter Noob bin.
Daraus resultierend ergibt sich, dass ich natürlich leider keinen Erfolg mit meinen Anpassungen hatte.

Dabei bleibt ja auch noch die Frage, ob das überhaupt die richtige Datei ist die ich da gefunden und vermeintlich als fehlerhaft identifiziert habe...

Vielen Dank und Grüße
Tobias

**Comment by chronicals** [comment]
Hierzu ist es vielleicht wichtig zu notieren, dass die Versions.json nicht mehr gewartet, gepatcht wird.

Es müsste hier die neue Version benutzt werden. 

Siehe versions.json:
`"__comment": "This URL is being phased out! Please update your scripts to check https://launchermeta.mojang.com/mc/game/version_manifest.json instead. Thanks <3 --Dinnerbone",
`

**Comment by loxonoff** [comment]
Hallo und guten Morgen
Ja, genau das ist das Problem, die neue URL hatte ich oben ja gepostet.

Allerdings weiss ich nicht an welcher Stelle die geparst und ausgewertet wird.
Ich habe ja nur die eine php-Datei gefunden, die vom Namen her passt und der Inhalt entsprechend das gesuchte Stück Code sein könnte.
Leider haben meine Anpassungen darin nichts bewirkt.

Ich frage mich wie das aktuell die easy-wi Benutzer machen, die Minecraft-Updates funktionieren ja schon seit 12.2 nicht mehr, die aktualisieren wohl händisch?
Wir haben jetzt die 13.1 auf einem anderen Server laufen, die automatischen Updates müssen daher doch schon eine ganze Weile nicht mehr funktionieren.

Hast Du mal eine Neuinstallation versucht, wenn es keine Meldungen im Log gibt bleiben ja nicht viele Möglichkeiten...
Problem könnte doch, wenn es nicht einmal angeboten wird, nur auf Seite des WI liegen, oder?
Hast Du die Konfiguratin bei dessen installation dokumentiert?
Dann könnte man es doch vielleicht relativ schnell einmal neu aufsetzen.

Das Thema ist nicht extrem wichtig für mich, habe noch einen native Linux-Rechner im Keller auf dem zur Zeit der aktuelle Minecraft-Server für meine Kinder läuft.
Wollte ihnen mit dem easy-wi eine komfortable Möglichkeit an die Hand geben um diesen zu steuern.
So wäre ich aus dem Thema so ziemlich raus, brauche mich um Start-Stop nicht zu kümmern, es können einfach Konfigrationen verändert und ausprobiert werden, andere Spiele... es können eigenständig und regelmässig BackUps per FTP angelegt werden.

Könnte mir aber auch vorstellen, die Kinder werden ja älter..., später mal einen Rootserver zu mieten und das WI zu dessen Verwaltung einzusetzen. Das WI dann auf einem Webspace und der Root irgendwo, wo es vernünftige Hardware zum angemessenen Preis gibt.

Grundsätzlich bleibt aber zu sagen, dass ich mich für dieses grossartige Stück Arbeit und die Bereitschaft diese mit anderen zu teilen, bei Herrn Block bedanken möchte.

Beste Grüße, Tobias

**Comment by Lacrimosa99** [comment]
Wir werden in naher Zukunft das Problem suchen und beheben.
Aktuell sind wir jedoch viel beschäftigt und haben weniger Zeit als früher.

**Comment by Slluxx** [comment]
Zur not kann man die server.jar manuell auf den ftp hochladen und im startcommand "%binary%" zu "server.jar" ändern. Das funktioniert genauso, allerdings kann dann der user die datei mit jeder beliebigen überschreiben und seine statdessen ausführen.

**Comment by Da-Geek** [comment]
> We will find and fix the problem in the near future. 
> Currently we are busy and have less time than before.

I think this should be something that could be easily fixed, @TheRealMrBC & I will see if we can make the changes needed and submit the fix for review.

Any help or basic pointers from @Lacrimosa99 might help us speedup the fix.

**Comment by Da-Geek** [comment]
It seems Mojang have changed the syntax of the 'version_manifest.json'
it seems as if it is no longer as simple as using the version number in a URL to download the .jar file, as it was via AWS
It may need some addition lines of code to parse the json from the new URL to extract the download URL.

Anyone care to offer some additional help with this?

**Comment by Da-Geek** [comment]
I am able to extract the release version from the new version_manifest.json file without any issue, this was a trivial change.
The issue is Mojang have changed the process so that the version_manifest.json now points to a 2nd json file that contains the Download URL for the server.jar
The url of both the 2nd json file and the final server.jar we want are no longer simple URLs with the version in them like before (on s3.amazonaws.com), the URLs of the 2nd json and the .jar now have 40 char UUIDs in the path, so we have to read one json file to get the url of a 2nd json file to extract the download URL of the server.jar

**Comment by Lacrimosa99** [comment]
the file what you must edit is ```stuff\methods\queries_updates.php```
I have no time to change the code.. sorry..

**Comment by Da-Geek** [comment]
> the file what you must edit is `stuff\methods\queries_updates.php`
> I have no time to change the code.. sorry..

@Lacrimosa99 Is this project still active @ all?

I can see most files are Years old, but some small changes here and there.
I am getting very close to deploying 16 physical servers and easy-wi is one of the projects
I am looking at for this deployment.

I really don't want to sink a load of time into it, if the project is already stale/dead/dying?

Easy-wi looks Amazing and has all of the features I am looking for, for this deployment.
Thank you for taking the time originally to release this code/project.

**Comment by Lacrimosa99** [comment]
@Da-Geek yes the project lives ;)
we have little time =(

**Comment by Lacrimosa99** [comment]
In the Dev Version is the old mc url deactivated and sync only with the imageserver yet.
On the imageserver is the last mc files and will updatet every 12h.

**Comment by FluX80** [comment]
Müsste man ggf noch anpassen oder so.

    function getMinecraftVersion($release = 'release') {

         $responseBody = webhostRequest('launchermeta.mojang.com', 'easy-wi.com', '/mc/game/version_manifest.json');

         $json = @json_decode(cleanFsockOpenRequest($responseBody, '{', '}'));

         $jsondlurl = file_get_contents($json->versions[0]->url);
         $obj = json_decode($jsondlurl);

         return ($json) ? array('version' => $json->latest->$release, 'downloadPath' => $obj->downloads->server->url) : array('version' => '', 'downloadPath' => ''); }

**Comment by Nexus633** [comment]
Ist das noch ein aktuelles Problem? Dann werde ich mich dem Problem widmen :-)
