### ISSUE TITLE
Can't install Voiceserver 

### ISSUE THREAD

**Issue by boyfromgermany** [easy-wi/developer#1175]
So i tried to install the easy-wi servers on a new VM yesterday i installed Gameserver and Webserver and they are working just fine but today i tried to install the Voiceserver and it won't work it always shows this error during installation and the output won't work in easy-wi

![log](https://user-images.githubusercontent.com/36824290/48082321-9c92c600-e1f2-11e8-98c9-3f906f83085f.PNG)

i already tried to add the parameter license_accepted=1 to the script but that won't work either

Has anyone an idea for this ?

**Comment by Lacrimosa99** [comment]
Which installer is in use?
you can create yet the accept file with the teamspeak user and with this command ```touch /home/your_ts_user/ts3server_license_accept``` insode your putty and start/restart your teamspeak server by hand.

**Comment by boyfromgermany** [comment]
i used this installer https://easy-wi.com/en/installation/voice-root-server/

![wont](https://user-images.githubusercontent.com/36824290/48158360-9d9b2480-e2d2-11e8-8a71-741d93fb1ba5.PNG)

So with the file created as you can see it won't work either and shows the same error 
I tried to watch into the logs folder but the same lines there 0always says License Accepted

**Comment by Lacrimosa99** [comment]
replace the ```your_ts_user```` with your user!

**Comment by boyfromgermany** [comment]
I replaced it in the line below 
should have cuttet this out of the screenshop

**Comment by boyfromgermany** [comment]
Thank you now it worked 
i think i have tried it before but anyway now it works 
Maybe this should be added to the script and with a query before "Do you accept the Licence ?"

**Comment by Lacrimosa99** [comment]
inside the installer 2.4 is this function included.
