### ISSUE TITLE
[Frage] Server neu zuweisen

### ISSUE THREAD

**Issue by FarukGamer** [easy-wi/developer#1177]
Ist es möglich den Gameserver von Nutzer A auf Nutzer B zuweisen und ist es eventuell auch möglich mehrere Nutzer auf einen Gameserver zuweisen? ( nicht als Vertreter )

**Comment by Lacrimosa99** [comment]
Im Housting Bereich wird dieses Feature weniger benötigt da die Kunden in aller Regel ihre Login Namen behalten.
