### ISSUE TITLE
Cannot create support category's 

### ISSUE THREAD

**Issue by Slluxx** [easy-wi/developer#1178]
Im trying to add some category's but once i save one it doesnt show up. Tested on multiple installations and never works. Can i provide something that helps resolving this?

**Comment by Lacrimosa99** [comment]
Were synonyms used or umlauts?

**Comment by Lacrimosa99** [comment]
can i not confirm
https://imgur.com/AEFUg64

**Comment by Lacrimosa99** [comment]
you can write your log but i don't can reproduce your failure..
