### ISSUE TITLE
No "Gameserver IP" when creating first game server

### ISSUE THREAD

**Issue by littledevilvito** [easy-wi/developer#1180]
So when I hover over "Gameserver IP" under the Easy-WI Gameserver overwiev there is like a 10px dropdown but no IP I could select... 
![easywi](https://user-images.githubusercontent.com/46631743/51076932-cb706100-16a7-11e9-9b2c-4d54c2aa63bd.PNG)
I created the Master without problems and can also select the master's IP under "Rootserver"

**Comment by Lacrimosa99** [comment]
pls more information to your system...

**Comment by littledevilvito** [comment]
My server has:
Ram: 8GB DDR3
Cpu: i3-3220
500 GB Storage HDD and an 128GB boot SSD with Ubuntu 18.04 LTS installed.
I freshly installed the easy-wi webinterface and game server files via the installer from the official website. Everything worked fine while setting things up with a local ip (192.168.0.53) for Config purposes, though through out the setup when selecting the IP for the WI to use, I had following selections:
1)0
2)0
3)Other
4)Quit
Wich was odd but it didn't bother me much. Everything installed like a charm, logged into the website and installed everything.
GameServer Master installed without problem's and my two test games (CS:GO and Gmod) downloaded fine.
I added a user (user2) and gave him a password. Again no problem, i wanted to create a gameserver for the user and i could fill everything out fine, except the Gameserver IP (when i hover over it it behaves like a normal dropdown but it only drops like 10px, so basically no entry's)

**Comment by littledevilvito** [comment]
Atm I am not at home, though i just copy pasted the command from "https://easy-wi.com/#unstable-installer-debian-9-ubuntu-1710-and-centos-7" into the terminal when setting it up.
I updated via the WI to version 6.0.6 i believe, basically it just told me to update after i finished the installation and logged in into the WI for the first time.

**Comment by Lacrimosa99** [comment]
have you specified a master server?
and it the master server installed via script and was this also stored in the interface?

**Comment by littledevilvito** [comment]
The master server was created via the WI and i could install the games on it (cs:go and gmod)&& i could select the master server as master server when trying to create the game server...

**Comment by littledevilvito** [comment]
Now i am confused?!
I installed the master server via the webinterface and i can also select it as Master server. The problem i have is that i don't have any IP entry's for the "Gameserver IP"
See:  https://m.imgur.com/9YYohX9
I did everything step by step like the guide from the official website.

**Comment by Lacrimosa99** [comment]
then must you installed a gameserver root like this todo https://easy-wi.com/en/installation/game-root-server/

is that installed?

**Comment by littledevilvito** [comment]
I did that, i first installed the WI via the .sh and then the game root server. Its setup, folder structure is there and everything has 775 permissions
https://m.imgur.com/fr5pNOJ

**Comment by Lacrimosa99** [comment]
by the gameroot installation have you by ip the option "other" executed and enter your local ip?

**Comment by littledevilvito** [comment]
Your question doesn't really make sense, but if you mean that when i installed the gameroot master, i selected
3) Other
And entered the server's LAN ip then YES

**Comment by Lacrimosa99** [comment]
that mean i^^
and to your  problem... i tried to adjust it but could not reproduce the error.
https://imgur.com/8vN58BL

**Comment by littledevilvito** [comment]
I can select the master server without problem...
But when creating a Game server I cant select an IP under "Gameserver IP" its an empty list
https://m.imgur.com/pae45yo

**Comment by Lacrimosa99** [comment]
can i too not confirm..
![Picture](https://imgur.com/WAn4qsd)

**Comment by littledevilvito** [comment]
What shall i do now? Reinstall everything?
And btw i see you speak German, vielleicht ist das einfacher für uns beide :D

**Comment by Lacrimosa99** [comment]
Um genaue Problemanalyse zu betreiben würde ich dich bitten, dich im Gitter Chat zu melden.
Dies ist für beide Seiten einfacher und schneller... so bläht das Ticket System nicht so auf.
