### ISSUE TITLE
Problem mit Domain

### ISSUE THREAD

**Issue by GermanY1337** [easy-wi/developer#1181]
Hallo, ich habe seit neuerem ein Porblem mit mein Domains.
Ich habe für ein Freund eine Webseite angelegt und die mit SSL verifiziert.
Sobald ich meine Hauptdomain auch mit SSL verifiziere dann wird seine Webseite direkt auf meine Weitergeleitet. Das ist erst so seitdem ich easy-wi installiert habe.

Ich habe mal aus der Easy-Wi config den 443 Part raus genommen danach geht das alles super. nur sobald ich das wieder drinne habe funktioniert das nicht mehr.

Mit freundlichen Grüßen
Chris

**Comment by Lacrimosa99** [comment]
Jeder VHost benötigt ein Zerfitikat und das dazugehörige Template.
Bei dir wird die Anpassung des Templates fehlen..

Beispiel Template (ist das Masterserver Template für alle VHosts):

`<VirtualHost *:80>
    ServerName %domain%
    Redirect 301 "/" "https://%domain%/"
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin %email%
    DocumentRoot "%vhostpath%/%user%/%htdocs%/%path%"
    ServerName %domain%
    ErrorLog "%vhostpath%/%user%/%logDir%/error_%domain%.log"
    CustomLog "%vhostpath%/%user%/%logDir%/access_%domain%.log" common
    DirectoryIndex index.php index.html
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/%domain%/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/%domain%/privkey.pem
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomain"
    <IfModule mpm_itk_module>
       AssignUserId %user% %group%
       MaxClientsVHost 50
       NiceValue 10
       php_admin_value open_basedir "%vhostpath%/%user%/%htdocs%/%path%:%vhostpath%/%user%/tmp"
       php_admin_value session.save_path "%vhostpath%/%user%/sessions"
       php_admin_value upload_tmp_dir "%vhostpath%/%user%/tmp"
       php_admin_flag allow_url_fopen Off
       php_admin_flag allow_url_include Off
       %phpConfiguration%
    </IfModule>
    <Directory %vhostpath%/%user%/%htdocs%/%path%>
        Options -Indexes +FollowSymLinks +Includes
        AllowOverride All
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
    </Directory>
</VirtualHost>`

**Comment by GermanY1337** [comment]
Ich benutze aber nicht das Webspace Modul. Ich hatte mir das zwar nachträglich installiert aber wieder runter geworfen da es mir nicht gefallen hat. Ich hatte mein Server komplett Platt gemacht und neu aufgesetzt. Davor hat ja auch alles funktioniert.

**Comment by Lacrimosa99** [comment]
Bitte mal genau beschrieben was das Problem ist und wie Konfiguriert wurde... versteh nicht ganz was das mit dem WI zutun hat, wenn du das betreffende Modul nicht installiert hast..

**Comment by GermanY1337** [comment]
Das könnte gut möglich sein. Nun funktioniert alles.
