### ISSUE TITLE
problems with lend server (not lended)

### ISSUE THREAD

**Issue by MikkelDK** [easy-wi/developer#1185]
Hi.

There is problems with lend the server (I have set 4 csgoservers to bed lended as)

It works. **BUT** after maybe small minutes, it will disconnect, and the log saying: 

Cronjob: Stop Game Server IP:27015 not lended
--
What can i do? how can i get it works, so it don't say "not lended" since i have set it to "anonymous" as example. but it will still say "not lended" what can I do?

**Comment by MikkelDK** [comment]
@Lacrimosa99 & @ulrichblock maybe you guys have some idea?

**Comment by Lacrimosa99** [comment]
Is anyone on the server at the time?
if the server is empty they will be stopped.

**Comment by MikkelDK** [comment]
Its too stop, if it's not set. The empty was not set. So it will still stop the server.

**Comment by Lacrimosa99** [comment]
can i self nothings say to.. we have no lendserver running.
