### ISSUE TITLE
Sidepanel does not appear on Mobile

### ISSUE THREAD

**Issue by FarukGamer** [easy-wi/developer#1186]
On a Mobile Device your unable to use the Sidepanel, it was excepted that on pressing the three lined lines on the top left to show up the Sidepanel.

My Galaxy Note 4 is running with the Custom Firmware LineageOS 15.1 ( Android 8.1 ). As browser I do use Bromite an chromium based browser.

**Comment by Lacrimosa99** [comment]
can i not confirm.
Tested on a Samsung Galaxy S5 and official OS.
