### ISSUE TITLE
Game auf GS installieren

### ISSUE THREAD

**Issue by TheMo0102** [easy-wi/developer#1188]
Hallo Habe folgende Herausforderung.

Beim Updaten von den Spieldatei bekomme ich immer die Meldung:

The login data does not work

Steamuser ist im Template leer gelassen worden lt. Anleitung

Kann mir dabeiwer helfen, Danke

lg 

TheMo

**Comment by Lacrimosa99** [comment]
Bitte mehr Infos... welches Game hat den Fehler?

**Comment by TheMo0102** [comment]
Dieser Fehler tritt unabhängig auf, also bei jedem Game.
den Anonymous und die normalen SteamCMD Daten habe ich eingetragen
jedoch Ohne erfolg, sieht aus als wie wenn er sich nicht Anmelden könnte.

![unbenannt](https://user-images.githubusercontent.com/48160022/53721658-0c912000-3e64-11e9-826c-f461cb0ea06a.PNG)

lg 

Alex

**Comment by Lacrimosa99** [comment]
Die Meldung sieht wie ein fehlgeschlagenes Login auf dem Masterserver aus und nicht in Verbindung mit Steam.
Bitte Login Daten des Masterservers prüfen.

**Comment by TheMo0102** [comment]
OK, Danke Fehlermeldung ist weg.
Spitze, Danke Danke

Hingegen darf ich dir ein Feedback geben ???

**Comment by Lacrimosa99** [comment]
ist technisch nicht so einfach da man den Prozess "greppen" müsste um die Taskbar/Prozent auslesen zu können.

**Comment by TheMo0102** [comment]
ok hast du sonst eine Idee wo man noch ausser in der Konsole nach sehen kann wg. dem Fortschritt ???
da ich via dem UI 7 days und Ark zum installieren eingerichtet habe und er noch immer am Installieren ist seit ca. 1 Stunde

**Comment by TheMo0102** [comment]
weisst was spitze wäre darf ich dir meine TS3 Daten geben dann is ein wenig einfach wenn es für dich OK ist.
Weil wir machen jetzt schon seit dem 28.02. mit dem UI herum und haben es nicht zum laufen gebracht, leider :-(((((((
Die Daten sind auf www.bohf.de

**Comment by Lacrimosa99** [comment]
Sitze leider aktuell auf Arbeit und schreibe nur nebenher hier..
Wo du schauen kannst ist in der SSH Console und mit HTOP... du hast auch die Möglichkeit dich in den Prozess Screen einzuloggen und darin zu lesen.
Es ist Möglich, das die ARK ID geändert wurde und daher solange zum Download benötigt... daher mal die ARK ID prüfen um das auszuschliessen.

**Comment by TheMo0102** [comment]
OK, Ark habe ich hinaus genommen, jedoch die 7 Days Daten passen
einmal Server ID und Client ID.

**Comment by Lacrimosa99** [comment]
dann mal ein Update Fahren übers Interface und mit htop beobachten, ob der Prozess beginnt und dieser mit der Zeit mehr wird oder ob dieser sich sofort wieder schliesst.. Hintergrund ist, erstmal herauszufinden ob die Verbindung zustande kommt und Steam auch den Login zulässt.
Was spucken die Logs des Masterservers aus?

**Comment by TheMo0102** [comment]
So alles zurück auf Anfang, bekomme heute wieder die Meldung The Login Data does not work

Ich hätte gedacht wenn du zeit hast das wir das von vorne in Ruhe durchgehen damit da einmal was wird mit dem Server ;-)

Ich Bedanke mich schon einmal im voraus

lg 

TheMo

**Comment by Lacrimosa99** [comment]
Wie wurde der Masterserver eingerichtet... mit Keyfile, Keyfile + PW oder nur PW?
Liegen Interface und Gameserver auf einem System oder sind diese getrennt?
Wie schaut es mit dem OS aus... welches OS mit welcher Version ist in Benutzung?

**Comment by TheMo0102** [comment]
Das UI und GS liegen auf einem System // auf Debian 9 // Keyfile + pw

**Comment by TheMo0102** [comment]
kann das sein das es hier eine BN Problematik gibt:

User:
![user](https://user-images.githubusercontent.com/48160022/53872897-7db90a80-3fff-11e9-847a-b8487481cb3e.PNG)

Admin:

![admin](https://user-images.githubusercontent.com/48160022/53872917-89a4cc80-3fff-11e9-8007-84cfb75254b6.PNG)

**Comment by Lacrimosa99** [comment]
Nutz bitte testweise mal zur Masterserver Authentifizierung nur das Keyfile ohne PW.
Möchte ausschließen, dass es an dem Keyfile PW liegt.

**Comment by TheMo0102** [comment]
OK Keyfile is draussen, er zeigt zwar an das der download startet jedoch passiert auf dem Server nichts
weil kein Prozess gestartet wird :-( lt. Htop

**Comment by TheMo0102** [comment]
hab mir das gerade im Iftop auch angesehen und das gleiche
es wird einfach kein Download gestartet

**Comment by Lacrimosa99** [comment]
Du hast dem Admin/User die Rechte entzogen, die GS Upzudaten.
Setz das Rechtesystem mal zurück und teste es dann erneut.

![grafik](https://user-images.githubusercontent.com/5357756/53940242-6e949400-40b5-11e9-8dae-53cbf0e499a7.png)

**Comment by TheMo0102** [comment]
Hi, Danke für die Info ;-)
habe es gemacht jedoch ohne erfolg, deswegen habe ich es mit einem Vorinstallierten Template
überprüft und das ist das gleiche leider :-(

![gsupdate](https://user-images.githubusercontent.com/48160022/53949263-f6849900-40c9-11e9-8ff5-2840677b31bd.PNG)

**Comment by Lacrimosa99** [comment]
Bitte IPs nicht öffentlich (DSGVO) ;)
Was spuckt der Masterserver in den Logs und das System in den Systemlogs dazu aus?

**Comment by TheMo0102** [comment]
Keine Reaktion seit 02.03. lt. Logs ist es so wie wenn der Server am 02.03. zum arbeiten aufgehört hat :-(

**Comment by Lacrimosa99** [comment]
Kann dir nur Anbieten, am Wochenende mich mit dir zusammen zu setzen und zu schauen, woran es liegt.
Für mich klingt es wie Login Problem des Masterservers bzw Routing Fehler.

**Comment by TheMo0102** [comment]
ja das wäre top, danke danke
hast du eine Idee was ich sonst in der Zwischenzeit noch machen könnte ?????

**Comment by Lacrimosa99** [comment]
Teste mal das Login als Masterserver mittels Putty/WinSCP und deinem Keyfile... so brauch ich das zumindest nicht machen^^
