### ISSUE TITLE
Eigener Startbefehl wird nicht angezeigt

### ISSUE THREAD

**Issue by nbhosting** [easy-wi/developer#1191]
Hallo Community, 

ich nutze derzeit Easy-Wi 6.0.5 und mir ist aufgefallen, dass ich als User keine eigenen Startparameter mehr vergeben kann. Die Funktion ist jedoch im Template aktiviert, als Benutzer-unter Einstellungen kann ich jedoch kein Feld mit Startparameter finden...  hilfe ^^

** Wenn ich diese als Administrator für jeden Server einzelt Editiere,funktionieren diese. Auch wenn ich bsp. Arma 3 Exile, als Addon einsetze, dort andere Startparameter setze, nimmt es sie auch.. Ich kann sie einfach als "User ( Kunde)" nicht Editieren.. 

MFG

**Comment by Lacrimosa99** [comment]
Abend,

ist gewollt denn die Parameter sollen nicht vom User editierbar sein, da Shell Scripte ausgeführt werden, worin man sich SuperUser (Root) Rechte geben könnte.

**Comment by nbhosting** [comment]
Ist auch nicht nachträglich änderbar?

**Comment by Lacrimosa99** [comment]
soweit ich weis sollte die Funktion enthalten sein und funktionieren.
Da es aber unsicher ist, rate ich davon ab.
