### ISSUE TITLE
Irreführende Versions Warnung

### ISSUE THREAD

**Issue by Bara** [easy-wi/developer#1192]
Hab mit die aktuelle Version hier von Github gezogen und beim Installieren meinte er 6.0.5 (noch nicht public?) sei eine "ältere" Version wie 6.0.4. Vielleicht sollte man was einbauen mit dem Hinweis das die Version neuer ist als die aktuelle Stable.
![image](https://user-images.githubusercontent.com/17928280/55280971-831f2180-532d-11e9-8222-810094b451ed.png)

**Comment by Lacrimosa99** [comment]
Liegt daran, die die 6.0.5 nicht Puplic ist.
Wird demnächst behoben und Puplic gemacht.
