### ISSUE TITLE
error log and error WebFTP

### ISSUE THREAD

**Issue by arthurs9571** [easy-wi/developer#1193]
I have 2 problems,

when I try to access the server console it looks like this:

Can not download screenlog from server / mta / screenlog.0

and when I try to access the Web FTP it looks like this:

Errors Ocurred

Unable to access
Folder does not exist

these 2 errors happens on all game servers I tested.

I use Debian 8 Jessie more also happens in Debian 9, CentOS and Ubuntu

Print

Console:
https://files.gitter.im/easy-wi/Lobby/6C9M/erro-console-2.png

WebFTP:
https://files.gitter.im/easy-wi/Lobby/6C9M/erro-ftp-1.png

**Comment by chronicals** [comment]
Have you correctly installed the ftp server on the master server?
And can you connect to it with a third party programm like filezilla?
Also try to open the ftp port (21) in the master server firewall, if the ftp server appears to be running correctly but you can't reach it.

**Comment by Lacrimosa99** [comment]
gta mta files must you self installing.. we have no imageserver with mta running.
