### ISSUE TITLE
Streamserver Modul for ShoutCast

### ISSUE THREAD

**Issue by MiningVillains** [easy-wi/developer#1194]
Hey is there a way to Administrate ShoutCaststreams over Easy-Wi?
Or is an Streamservermodul planned in a Future release?

**Comment by Lacrimosa99** [comment]
Hi,
is no stream plugin in plane and i think, that the interface no streaming supported.

**Comment by MiningVillains** [comment]
Ok, and is there a way that a Streaming Modul for ShoutCast will be integrated in future?
