### ISSUE TITLE
Fragen zur Einrichtung

### ISSUE THREAD

**Issue by MiningVillains** [easy-wi/developer#1195]
Hallo erstmal,
ich hätte da Zwei Fragen:

Wenn easy-wi nicht mit Plesk läuft, gibt es dann eine Alternative für Plesk die unter Ubuntu Funktioniert?

Wie kann ich das Webinterface über eine Sub-Domain erreichbar machen, oder ist nur die Ip eine Möglichkeit?

Mfg
MiningVillains

**Comment by Lacrimosa99** [comment]
Hi,
bitte Vorraussetzungen des WebInterfaces lesen... daraus ergeben sich viele Antworten.
www.easy-wi.com
