### ISSUE TITLE
Ubuntu 18.04 support?

### ISSUE THREAD

**Issue by GrexAut** [easy-wi/developer#1196]
Hi,

i don't use easywi very often, but today I wanted to install a new game "starbound".
Last month, I upgraded from Ubuntu 16.04 to Ubuntu 18.04, maybe this is the reason because I have troubles with easywi now...

I added "starbound" to the master apps, and on my server under /home/easywi/masterserver I have my folder with startbound. But in subfolder starbound, I have only one folder called steamapps within is a file called libraryfolder.vdf

After adding a new gameserver, it will be created in easywi Web Panel, but there is no subfolder under /home/easywi with userid-gameserverid, like user5-14

I tried with another gameserver app, I had already installed (arkse), but also will be not created under /home/easywi.

Now I saw at installer github, that 18.04 is not supported?

**Comment by Lacrimosa99** [comment]
check what if updated and read the changelogs from them.
i think that a problem with your rights or permissions.

**Comment by GrexAut** [comment]
Hab übersehen, dass easywi eigentlich ein deutsches Produkt ist, und ich eh auch deutsch schreiben kann ;)
Also das easywi wurde nicht geupdated, und Permissions Probleme könnens auch nicht sein, der komplette /home/easywi Ordner und die haben den Owner "easywi".

Warum der Ordner für starbound leer ist, kann ich mir nun erklären, da ich mittels steamcmd mal manuell installieren wollt, der steam account braucht das Spiel starbound.

Aber warum die gameserver nicht Filetechnisch angelegt wird, vor allem auch nicht mit dem Spiel "arkse", ist fraglich.
Gibt es logfiles/debugging Möglichkeiten?

**Comment by Lacrimosa99** [comment]
Es gibt eine debugging Möglichkeit in dem du dich per SSH und deinem WebInterface User einloggst und dort die ```statuscheck.php``` manuell ausführst.

Beispiel Code: ```cd /home/easywi_web/htdocs && timeout 290 php ./statuscheck.php```

Dort bekommst du das debugging bzw was er versucht.

**Comment by GrexAut** [comment]
Hallo,

sorry für die späte Rückmeldung, also ich erhalte folgendes Ergebnis:

> Cannot load the ionCube PHP Loader - it was already loaded
> Checking Gameserver, Voiceserver MySQL DB sizes and Web Quotas
> GameQ v3 support for arkse xxx.xxx.xxx.xxx:7777
> GameQ v2 support for starbound xxx.xxx.xxx.xxx:21025
> Checking 1 server(s) with GameQ v3 query
> Checking 1 server(s) with GameQ v2 query
> Server xxx.xxx.xxx.xxx:7777 is running as ARK: Survival Evolved. The name converted to ISO-8859-1 is Wipe 1.1.2019-Servername- (v296.104).
> Restarting: xxx.xxx.xxx.xxx:21025
> Checking TSDNS
> Checking Quota usage
> Gathering statistics for user grex with ID 1
> Gathering statistics for user user2 with ID 2
> Gathering statistics for user user4 with ID 4
> Gathering statistics for user user5 with ID 5
> Gathering statistics for user user6 with ID 6
> 

Unter /home/easywi/logs am Masterserver, steht folgendes drinnen wenn ich einen Server erstelle:
Tue Jun 11 20:56:47 CEST 2019: User user2-16 added
Tue Jun 11 20:56:47 CEST 2019: User user2-16-p added
Tue Jun 11 21:05:12 CEST 2019: User user2-17 added
Tue Jun 11 21:05:12 CEST 2019: User user2-17-p added

Aber unter /etc/passwd, gibt es garkeinen user2-16 bzw. user2-17

Unter im app_server.log steht folgendes:

> Tue Jun 11 21:05:12 CEST 2019: Server template /home/easywi/user2-17/server/7dtd/ owned by user user2-17 added/synced

Aber, der Ordner user2-17 wird nicht angelegt...

**Comment by GrexAut** [comment]
Hab das Problem gefunden, die locales waren nicht richtig gesetzt.

> locale-gen "en_US.UTF-8"
Danach hat es funktioniert.
