### ISSUE TITLE
FastDownload

### ISSUE THREAD

**Issue by arthurs9571** [easy-wi/developer#1197]
where the fastdownload sends the files, where I locate this file so that I can insert the HTTP URL

**Comment by Lacrimosa99** [comment]
Have you a FastDL Server installed?
All needed Datas find you in your WebInterface under "FastDownload" or so.

**Comment by arthurs9571** [comment]
eu nao sei configurar o fastdownload, previss configursr o webspace antes? ou como que faço? e se for configursr o webspace antes como faço para deixar um dominio para todos os webspace?

**Comment by Lacrimosa99** [comment]
use our installer script... all relevant modes are inside this script.

**Comment by arthurs9571** [comment]
Lacrimosa99, what script do I use for debian 8? 2.3 or 2.4?

**Comment by arthurs9571** [comment]
For fastdl to work, do you need to configure webspace?

**Comment by arthurs9571** [comment]
webspace settings are not creating when I create a vhost in apache2

**Comment by Lacrimosa99** [comment]
Please send the Installer Output... without can we not help.

**Comment by arthurs9571** [comment]
please explain to me, do you have any contacts that can help me to install and configure?

**Comment by arthurs9571** [comment]
I installed everything correctly, when I was setting up the webspace it reconfigured the configuration file in the sites-enabled folder does not create

**Comment by Lacrimosa99** [comment]
Use a Service like [https://first-version.de/easywi](https://first-version.de/easywi) or so.
