### ISSUE TITLE
Suspicious Behaivior: Gameserver crashed but normaly running

### ISSUE THREAD

**Issue by Miraculix1337** [easy-wi/developer#1198]
Hello Together,

I got an installation with one Webserver and one gamemasterserver. First of all i will explain my setup.
GS-Konfigurations (GS=gameserver):
- GS1 Port 27015, GS2 Port27016, and so on til 27020
- Every GS has an own server.cfg with an uniqe name

Problem
1. I have attached two Networkcards with different Subnets. S1: 192,  S1:10.x.x.x (Webhost)
The easy-wi will start the servers normaly also the behavior of the Servers would be normal. But easy-wi shows that some servers are offline. When i look at HLSW i saw that easy-wi startet the Servers with the wrong IP Adresses (192). Also the Labels in the User section will mixed up. GS-Label1 is now GS-Label2 and so on. I deattached the second Networkcard and the IP-Problem should be fixed.

2. When i Try to start the servers with the second networkcard deatached. I got the label problem from 1 and easy-wi shows the normal running servers as offline or crashed

I would like to fix this issue and need just a little of help and need to know if it is a bug or my fault.

Greeting Tobi

**Comment by Lacrimosa99** [comment]
is discussed by gitter chat.
