### ISSUE TITLE
PT_br/PT_pt 100% Language Suport

### ISSUE THREAD

**Issue by OnlyHardOfficial** [easy-wi/developer#1199]
Hello everyone! I am a professional in the area of ​​software translation, I have participated in such translations as PFsense, OPNSense, Boxbilling, OpenGamePanel ... I would like to have the opportunity to speak with some of the administrators so that we can improve the translation a little more and cover even more the language of this panel!

**Comment by Lacrimosa99** [comment]
We are opensource.. send a pull request and we pushed into the interface.

**Comment by andretunes** [comment]
> Hello everyone! I am a professional in the area of ​​software translation, I have participated in such translations as PFsense, OPNSense, Boxbilling, OpenGamePanel ... I would like to have the opportunity to speak with some of the administrators so that we can improve the translation a little more and cover even more the language of this panel!

Hi, i would love to help you ;)
