### ISSUE TITLE
Force update files? [CSGO Server]

### ISSUE THREAD

**Issue by MikkelDK** [easy-wi/developer#1200]
Hi,

Is there some-way possible to make (changed/changes files) via 
`/home/easy-wi/masterserver/csgo/csgo/cfg` >> forced applied updated to exists gameservers?

As example: `/home/user2-1/server/csgo/csgo/cfg.`

**E.g server.cfg**

**Comment by MikkelDK** [comment]
Maybe you know @Lacrimosa99 ^

**Comment by Lacrimosa99** [comment]
No, there is no way to upgrade all the game servers at once with certain config files.
You must every Gameserver Config Update by Hand while otherwise it can lead to problems.
