### ISSUE TITLE
Konfigurationsdateien von Eco Server sind Symlinks

### ISSUE THREAD

**Issue by Semixx** [easy-wi/developer#1201]
Hallo,

ich habe letztens einen Eco Server aufgesetzt. Dieser konnte aber nicht gestartet werden, da alle Config Dateien unter Configs/ als Symlink erstellt wurden.
Die Konfigurationsdateien haben die Endung .eco.

Um das Problem zu lösen, habe ich wie von @Lacrimosa99 vorgeschlagen die Config Dateien aus dem Masterserver gelöscht und diese wieder manuell per FTP Zugang vom User wieder ins Config Verzeichnis hochgeladen.

Ich würde mich darüber freuen, wenn man die Dateien, welche explizit kopiert werden sollen angeben kann ;).

Freundliche Grüße
Semixx

**Comment by Lacrimosa99** [comment]
Wie schaut dein Template aus dazu?
Wahrscheinlich nen kleiner Fehler darin.

**Comment by Semixx** [comment]
Hab das Template angefügt.
[eco.zip](https://github.com/easy-wi/developer/files/3297869/eco.zip)

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/developer/commit/111c05f1fbec8a0c13448b96a3e76b3b1cffed6a

**Comment by Lacrimosa99** [comment]
Bitte mal den Fix testen ob er nun die Files kopiert.

**Comment by Semixx** [comment]
Jo nach dem Fix wurden die Dateien kopiert.

**Comment by Lacrimosa99** [comment]
alles klar und danke fürs melden =)
