### ISSUE TITLE
Gameserver wird nicht installiert

### ISSUE THREAD

**Issue by TobiasKirfel** [easy-wi/developer#1202]
Hallo zusammen,

ich komme gerade von einer anderen Software, und möchte nun zu Easy-WI wechseln.
Alles klappt auch so weit, Imageserver funktioniert und downloadet auch alles auf dem Gameserver Server.

Der Server für die Gameserver erstellt auch korrekt die FTP-User, jedoch nicht den Ordner für den Gameserver. In /home/easy-wi/masterserver wurde es korrekt vom Imageserver gedownloadet.

Woran könnte es liegen?

**Comment by Mitleidleggins** [comment]
Welches Betriebssystem?
