### ISSUE TITLE
Problem with delete gameserver.

### ISSUE THREAD

**Issue by MikkelDK** [easy-wi/developer#1204]
Hi.

I have some weird problem, with the Easy-WI.

Where I tried to "Force Delete or Safe Delete" 1 GameServer.

And, so soon I'm doing that (it's, of course, delete on the panel!)

**But It doesn't delete from the server. - If I create one: and it's called: user2-20 > Delete the gameserver from panel >> Checking "ls -l" on PuTTY, user2-20 is still there.**

What can I do?
I can't see anything on logs! ;-/

Using: Apache2
OS: Ubuntu 18.10/Ubuntu 18.04
PHP: 7.2 version.

**Comment by MikkelDK** [comment]
@Lacrimosa99 Do you see this error, before?

I have tried to set "debug on" via Easy-Wi, but I don't get any "logs" about it _remove/delete_ on masterserver.

**Comment by Lacrimosa99** [comment]
i reproduce this in the next days.

**Comment by GLITCH-Jan** [comment]
+ Resync / Reinstall also not functional

**Comment by primeas-de** [comment]
OS: Debian 10
Installer: Stable
Web-Panel: developer-6.0.5-New
Getestet: Gameserver Anlegen / Löschen / Neu installieren / Start / Stop

- Problem: Bei Debian 10 ist die Verbindung über die PHP SSH2 Extension beendet bevor die Daten gelöscht werden.

- Lösung: Das beenden des Prozesses am ende des Bash Scriptes ausführen lassen und dem SSH2 Benutzer rechte für pkill geben.



> /etc/sudoers

Hinzufügen der Rechte für den PKILL
`gameserverssh2 ALL = NOPASSWD: /usr/bin/pkill`


> /stuff/methods/class_app.php

Hinzufügen in Zeile 481
`$this->shellScripts['user'] .= 'sudo pkill -u ' . $userName . "\n";`

Deaktivieren in Zeile 914
`// $script .= 'pkill -u 'whoami'' . "\n"`


> BEISPIEL

/etc/sudoers

```
#includedir /etc/sudoers.d
gameserverssh2 ALL = NOPASSWD: /usr/bin/pkill
gameserverssh2 ALL = NOPASSWD: /usr/sbin/useradd
gameserverssh2 ALL = NOPASSWD: /usr/sbin/usermod
gameserverssh2 ALL = NOPASSWD: /usr/sbin/userdel
gameserverssh2 ALL = (ALL, !root:easywi) NOPASSWD: /home/gameserverssh2/temp/*.sh
gameserverssh2 ALL = (ALL, !root:easywi) NOPASSWD: /bin/bash /home/gameserverssh2/temp/*.sh

```

/stuff/methods/class_app.php

Zeile 914

```
private function linuxHardStop ($userName) {

$scriptName = $this->removeSlashes('/home/' . $this->appMasterServerDetails['ssh2User'] . '/temp/hardstop-' . $userName . '.sh');

$script = $this->shellScriptHeader;
$script .= 'rm -f ' . $scriptName . "\n";
$script .= 'crontab -r' . "\n";

$script .= 'screen -wipe > /dev/null 2>&1' . "\n";
// $script .= 'pkill -u 'whoami'' . "\n";
$this->addLinuxScript($scriptName, $script, $userName);

$this->addLogline('app_server.log', 'Hard stop for user ' . $userName);
}
```

Zeile 481

```
private function linuxDeleteUserGenerate ($userName) {
$this->shellScripts['user'] .= 'sudo pkill -u ' . $userName . "\n";
$this->shellScripts['user'] .= 'if [ "'id ' . $userName . ' 2>/dev/null'" != "" ]; then' . "\n";
$this->shellScripts['user'] .= '${IONICE}nice -n +19 sudo /usr/sbin/userdel -fr ' . $userName . ' > /dev/null 2>&1 ' . "\n";
$this->addLogline('user.log', 'User ' . $userName . ' deleted');
$this->shellScripts['user'] .= 'fi' . "\n";
}
```

**Zur Lösung beigetragen: R3belWithoutAPause - Thanks!**

**Comment by R3belWithoutAPause** [comment]
Happy to help you fix this issue :)

**Comment by MikkelDK** [comment]
I will fix PR! =)
