### ISSUE TITLE
Mobile View: Hamburger menü klappt nicht aus

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#1206]
- EWI 6.0.5
- Android 9
- Chrome 74.0.3729.157

Offenbar neuer Bug nach #1052 / Dublikat von #1126

In der mobilen Ansicht klapp das "Hamburger"-Menü nicht mehr aus woraus sich ergibt das man im "Dashboard" festhängt.

User-Dropdown funktioniert.

![20190611_202410](https://user-images.githubusercontent.com/3930214/59296937-66855b00-8c87-11e9-9c27-48a9f47c8da1.jpg)

**Comment by MadMakz** [comment]
Dublicate / Reopen von #1126

**Comment by gOOvER** [comment]
evtl sollte man mal AdminLTE auf die neuste Version updaten. Leider ist sehr viel umgeschrieben und ich muss mich da erstmal durchwurschteln :/

**Comment by MikkelDK** [comment]
Did you get it solved @MadMakz ? I have continued the problem, without I got time to look on it.

**Comment by sscs12345** [comment]
change this line
`<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">`
to
`<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">`

**Comment by Lacrimosa99** [comment]
> 
> 
> change this line
> `<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">`
> to
> `<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">`

pls as pull-request =)

**Comment by MikkelDK** [comment]
> > change this line
> > `<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">`
> > to
> > `<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">`
> 
> pls as pull-request =)

I fix! ;)

**Comment by Lacrimosa99** [comment]
request merged :)
