### ISSUE TITLE
Webspace funktioniert nicht

### ISSUE THREAD

**Issue by SGTshan** [easy-wi/developer#1210]
Hallo,
ich habe den Easy-Wi Webspace Master per Installer installiert und ohne Fehler in mein Webpanel hinzugefügt. Jetzt habe ich einen Virtual Host erstellt, einem User zugewiesen und eine Subdomain hinzugefügt. Sowohl die normale Domain als auch die Subdomain leiten nun nicht zum Webspace des Benutzers sondern auf den Login vom Easy-Wi Webpanel weiter. Die DNS Einträge in der Domain sind korrekt konfiguriert.

**Comment by gOOvER** [comment]
Linux distro? Logs?

**Comment by gOOvER** [comment]
Welche DNS einträge sind gesetzt beim deinem DOmain Hoster? auch die "*" ?

**Comment by Lacrimosa99** [comment]
Ich gehe mal davon aus, dass der Eintrag in der Apache Config fehlt wo er die Configs des Webspace Moduls läd.
Bitte den Eintrag in der Datei ```/etc/apache2/apache2.conf``` nachtragen -> ```IncludeOptional /home/dein_Webspace_User/sites-enabled/*.conf```
Bitte ```dein_Webspace_User``` ändern in den User, welchen du wären des Installationsvorganges dem Webspace Modul zugewiesen hast.

**Comment by SGTshan** [comment]
> Linux distro? Logs?

Ubuntu 18.04, Kein Fehler in den Logs vorhanden


> Welche DNS einträge sind gesetzt beim deinem DOmain Hoster? auch die "*" ?

Wildcard (@/*), www und die erwähnte Subdomain.


> Ich gehe mal davon aus, dass der Eintrag in der Apache Config fehlt wo er die Configs des Webspace Moduls läd.

Hat tatsächlich gefehlt. Eingetragen und Apache neugestartet, Problem besteht immer noch. Hab ich was vergessen zu tun?

**Comment by Lacrimosa99** [comment]
Free Domains besitzen nur eine Frameweiterleitung und wird nicht Supported.
Bitte eine TLD mieten.
