### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by Cresnik85** [easy-wi/developer#1211]
![unknown](https://user-images.githubusercontent.com/51888764/59568524-fd815700-907b-11e9-907b-99e02c7ce26b.png)

Die Links für Forum und Wiki verweisen noch auf die alte Website.

**Comment by Lacrimosa99** [comment]
Danke fürs melden =)

**Comment by MikkelDK** [comment]
Es kann die folgenden Dateien korrigieren:

```
template/default/user/userpanel_header.tpl
template/default/admin/userpanel_header.tpl
template/default/cms/page_header.tpl
```
