### ISSUE TITLE
Fehler beim Gameservermaster

### ISSUE THREAD

**Issue by Sxlaxs** [easy-wi/developer#1212]
Hallo,

Ich habe einen Webspace, dort ist Easywi Webpanel installiert. Ich habe auf meinem Root den Gamemaster ertsellt, wenn ich alle Daten eintragen dann kommt dieser Fehler: http://prntscr.com/o31u5o
Ich habe auch schon probiert anstatt Root den Masteruser einzutragen. Das PW ist richtig und habe ich mehrmals geändert.

Mit freundlichen Grüßen

**Comment by Lacrimosa99** [comment]
Abend,
deinem Webspace fehlen PHP Abhängigkeiten welche für die Verbindung zum Root zuständig sind.
Entweder kann dein Provider diese nachinstallieren/aktivieren oder du must eine alternative zum Webspace suchen.

**Comment by Sxlaxs** [comment]
Was genau für PHP Abhängigkeiten fehlen denn?

**Comment by Lacrimosa99** [comment]
eines der Pakete wird fehlen/nicht aktiviert sein.

php-common (ist standard)
php-gd
libsodium-devel (Ubuntu ab 18.04) - alternativ (Debian und Ubuntu bis 18.03) php-mcrypt
php-mysqlnd
php-cli
php-xml
php-mbstring
php-zip

**Comment by Sxlaxs** [comment]
Nun bekomme ich folgende Fehler:
http://prntscr.com/o3hdts
http://prntscr.com/o3hd5d

**Comment by Sxlaxs** [comment]
Bei dem unteren versuche ich mich mit dem erstellten Benutzer für den Gameserver zu verbinden

**Comment by gOOvER** [comment]
Was sagt der log vom FTP?

**Comment by Lacrimosa99** [comment]
Kann es sein, das der Anbieter (dein Webspace) kein Port 21 nach außen zulässt?

**Comment by Lacrimosa99** [comment]
da keine Rückmeldung -> Closed
