### ISSUE TITLE
Ubuntu 18.04 - Quota check

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#1213]
Fehler in der Quota abfrage:

Execute command: for DIR in `grep -E 'usrjquota=|usrquota' /etc/fstab | awk '{print $2}'`; do for USER in `sudo /usr/sbin/repquota  -u -v -s $DIR 2>/dev/null | grep 'web-' | awk '{print $1":"$3}'`; do USERS="$USERS;$USER"; done; done; echo "$USERS;"
Command returns: ;

No web user found in server return: ;

Checking webMaster Root_IP with webMasterID 2
Execute command: for DIR in `grep -E 'usrjquota=|usrquota' /etc/fstab | awk '{print $2}'`; do for USER in `sudo /usr/sbin/repquota  -u -v -s $DIR 2>/dev/null | grep 'web-' | awk '{print $1":"$3}'`; do USERS="$USERS;$USER"; done; done; echo "$USERS;"
Command returns: ;

No web user found in server return: ;

![statuscheck_execute](https://user-images.githubusercontent.com/5357756/59967937-079ace00-9532-11e9-8b7e-2bb59f099d94.png)

**Comment by Nexus633** [comment]
also die Quota funktioniert tadellos. Bitte beschreibe was du genau im wi gemacht hast

**Comment by GLITCH-Jan** [comment]
#Closed aktuell nicht nachvollziehbar.
