### ISSUE TITLE
Debian 10 - PHP 7.3

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#1214]
Debian 10 used PHP7.3 as default

**Comment by Lacrimosa99** [comment]
Libsodium as alternative?
https://github.com/jedisct1/libsodium

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/installer/issues/75

**Comment by bammertine** [comment]
Gibt´s hier eigentlich schon was neues?
Warte wirklich seit Anfang 2019 darauf :(
