### ISSUE TITLE
Screenlog Error

### ISSUE THREAD

**Issue by Sxlaxs** [easy-wi/developer#1215]
Hey,

we are getting this error:
https://prnt.sc/ogzm7l

Silas

**Comment by MikkelDK** [comment]
And you are sure, gmod files has been installed on: /home/userpanel/masterserver/garrysmod?

**Comment by Lacrimosa99** [comment]
this can have several causes... please check if the server is running (via Putty or something like that).
See if the master server files all exist.

**Comment by MikkelDK** [comment]
@Lacrimosa99 can we close this. seems it's inactive! ;)
