### ISSUE TITLE
Debian 10 - curl & cron Problem

### ISSUE THREAD

**Issue by bammertine** [easy-wi/developer#1216]
Seit meinem Update auf Debian 10, wird mir angezeigt, ich hätte die CURL Erweiterung nicht installiert (was ich aber habe), ebenso laufen reboot.php und job.php Cronjobs nicht mehr durch.

**Comment by Lacrimosa99** [comment]
Debian 10 wird auch noch nicht vollständig vom Interface unterstützt da sich viele PHP Pakete geändert haben oder gar weggefallen sind.
Daher bitte vorerst auf Debian 9 setzen.
Wurde allerdings schon hier als Ticket behandelt.
https://github.com/easy-wi/developer/issues/1214

**Comment by Lacrimosa99** [comment]
https://github.com/easy-wi/installer/issues/75
