### ISSUE TITLE
Bad path

### ISSUE THREAD

**Issue by Balt0s** [easy-wi/developer#1217]
I select the path panel.domain.net, but the url domain.net redirects to panel.domain.net. 
I would like to cancel this automatic redirection.

Thanks you.

**Comment by MikkelDK** [comment]
Hi,

it's because you need to set it to your "own domain"

As example:
http://yourowndomain.eu/

You can write on discord if you want faster help! =)

**Comment by Balt0s** [comment]
Hello, thank you for your answer and your help, do I have to reinstall EasyWI ?

**Comment by MikkelDK** [comment]
Nope, you don't need. - did you use easy-wi installer? to install?

**Comment by Balt0s** [comment]
![Capture](https://user-images.githubusercontent.com/47494812/63652884-db840f00-c765-11e9-8359-4de2d34765cd.PNG)

I write 

> http://panel.domain.net/

 ?

**Comment by MikkelDK** [comment]
No. you need to use your **REAL** domain, or just the IP-address!

**Comment by Balt0s** [comment]
So, I write 

> domain.net ?

**Comment by MikkelDK** [comment]
No.

You can't use domain.net if you don't have your own domain.

If you need to use **domain** you need to buy one! :-)  
So you can only use **IP** > As an example: http://IPAddresshere

**Comment by Balt0s** [comment]
Yes, "domain.net" it's a example, my real domain is Ikovich.net

**Comment by MikkelDK** [comment]
btw, the panel works fine, on your domain. so is it redirect to wrong domain, if you log in?

**Comment by Balt0s** [comment]
No, when I go on IKOVICH.NET redirect me on PANEL.IKOVICH.NET

**Comment by Balt0s** [comment]
I want to disable this feature

**Comment by MikkelDK** [comment]
Oooh, I see what you mean.

Go to: `/home/easy-wi/sites-enabled` > edit the .conf file =)

**Comment by Balt0s** [comment]
Thank you but what should I change to prevent redirection?

**Comment by MikkelDK** [comment]
Display the file here with [CODE] [/ CODE] without space.

**Comment by Balt0s** [comment]
`<VirtualHost *:80>
    ServerName **VPS-IP-ADRESS**
    ServerAdmin info@**VPS-IP-ADRESS*
    DocumentRoot "/var/www/html/"
    ErrorLog "/home/easywi_web/logs/error.log"
    CustomLog "/home/easywi_web/logs/access.log" common
    DirectoryIndex index.php index.html
    <IfModule mpm_itk_module>
       AssignUserId easywi_web www-data
       MaxClientsVHost 50
       NiceValue 10
       php_admin_flag allow_url_include off
       php_admin_flag display_errors off
       php_admin_flag log_errors on
       php_admin_flag mod_rewrite on
       php_admin_value open_basedir "/home/easywi_web/htdocs/:/home/easywi_web/tmp"
       php_admin_value session.save_path "/home/easywi_web/sessions"
       php_admin_value upload_tmp_dir "/home/easywi_web/tmp"
       php_admin_value upload_max_size 32M
       php_admin_value memory_limit 32M
    </IfModule>
    <Directory /home/easywi_web/htdocs/>
        Options -Indexes +FollowSymLinks +Includes
        AllowOverride None
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
    </Directory>
    <LocationMatch "/(keys|stuff|template|languages|downloads|tmp)">
        <IfVersion >= 2.4>
            Require all denied
        </IfVersion>
        <IfVersion < 2.4>
            Order deny,allow
            Deny  from all
        </IfVersion>
    </LocationMatch>
</VirtualHost>
`

**Comment by Balt0s** [comment]
[CODE] <VirtualHost *:80>
    ServerName **ip adress*
    ServerAdmin info@**ip adress**
    DocumentRoot "/var/www/html/"
    ErrorLog "/home/easywi_web/logs/error.log"
    CustomLog "/home/easywi_web/logs/access.log" common
    DirectoryIndex index.php index.html
    <IfModule mpm_itk_module>
       AssignUserId easywi_web www-data
       MaxClientsVHost 50
       NiceValue 10
       php_admin_flag allow_url_include off
       php_admin_flag display_errors off
       php_admin_flag log_errors on
       php_admin_flag mod_rewrite on
       php_admin_value open_basedir "/home/easywi_web/htdocs/:/home/easywi_web/tmp"
       php_admin_value session.save_path "/home/easywi_web/sessions"
       php_admin_value upload_tmp_dir "/home/easywi_web/tmp"
       php_admin_value upload_max_size 32M
       php_admin_value memory_limit 32M
    </IfModule>
    <Directory /home/easywi_web/htdocs/>
        Options -Indexes +FollowSymLinks +Includes
        AllowOverride None
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
    </Directory>
    <LocationMatch "/(keys|stuff|template|languages|downloads|tmp)">
        <IfVersion >= 2.4>
            Require all denied
        </IfVersion>
        <IfVersion < 2.4>
            Order deny,allow
            Deny  from all
        </IfVersion>
    </LocationMatch>
</VirtualHost>
 [/ CODE]

**Comment by MikkelDK** [comment]
Aha, I know where => Do you have access to phpmyadmin?

Login on phpmyadmin >go to easy_wi > open settings > click on "Edit" > find: paneldomain =)

**Comment by Balt0s** [comment]
My http://ikovich.net/phpmyadmin/ don't work :(

**Comment by MikkelDK** [comment]
Write to me on Discord. I will assist you, and fix it. (if you want.) =)
