### ISSUE TITLE
2 Problemes with /home/admin/sites-enabled/configuration_file.conf

### ISSUE THREAD

**Issue by Balt0s** [easy-wi/developer#1219]
Hello, when I activate the default configuration file create by Easy WI, I have two problems:
1: mydomain.net/phpmyadmin send me an error 500.
2: mydomain.net redirect me to panel.mydomain.net 
I would like the panel only on panel.mydomain.net and not on mydomain.net.

This is the file : /home/admin/sites-enabled/configuration_file.conf
**<VirtualHost *:80>
    ServerName panel.mydomain.net
    ServerAdmin info@panel.mydomain.net
    DocumentRoot "/home/easywi_web/htdocs/"
    ErrorLog "/home/easywi_web/logs/error.log"
    CustomLog "/home/easywi_web/logs/access.log" common
    DirectoryIndex index.php index.html
    <IfModule mpm_itk_module>
       AssignUserId easywi_web www-data
       MaxClientsVHost 50
       NiceValue 10
       php_admin_flag allow_url_include off
       php_admin_flag display_errors off
       php_admin_flag log_errors on
       php_admin_flag mod_rewrite on
       php_admin_value open_basedir "/home/easywi_web/htdocs/:/home/easywi_web/tmp"
       php_admin_value session.save_path "/home/easywi_web/sessions"
       php_admin_value upload_tmp_dir "/home/easywi_web/tmp"
       php_admin_value upload_max_size 32M
       php_admin_value memory_limit 32M
    </IfModule>
    <Directory /home/easywi_web/htdocs/>
        Options -Indexes +FollowSymLinks +Includes
        AllowOverride None
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
    </Directory>
    <LocationMatch "/(keys|stuff|template|languages|downloads|tmp)">
        <IfVersion >= 2.4>
            Require all denied
        </IfVersion>
        <IfVersion < 2.4>
            Order deny,allow
            Deny  from all
        </IfVersion>
    </LocationMatch>
</VirtualHost>**

Thanks you.

**Comment by Lacrimosa99** [comment]
Install you phpmyadmin over the repository or by hand?
