### ISSUE TITLE
Problem with HTML

### ISSUE THREAD

**Issue by Onyxzium** [easy-wi/developer#1221]
Hello, I have deleted the user easy-wi in the home directory now my HTML net works more so I can not go to any website from us anymore

**Comment by MikkelDK** [comment]
html? - it better for us, if you post the errors, you are getting.

**Comment by Onyxzium** [comment]
Its on german but thats my problem.
Ich gebe in meinen Browser bsp. xevelia.net ein und dann kommt ein HTTP Error
HTTP ERROR 500

oder was mir am wichtiges ist bei der Datenbank kann ich jetzt nicht mehr in phymyadmin
HTTP ERROR 500

Und auch leitet jede Subdomain die auf den Server leitet automatisch auf xevelia.net um
bsp. sftp.xevelia.net >> xevelia.net

**Comment by Onyxzium** [comment]
Und keiner kann auch mehr über Ports zugreifen ERR_SSL_PROTOCOL_ERROR

**Comment by gOOvER** [comment]
apache error log bitte

**Comment by gOOvER** [comment]
Scheint nicht akut zu sein. Eher ein Benutzer Fehler
