### ISSUE TITLE
How can I set a domain to a webspace?

### ISSUE THREAD

**Issue by Damerino** [easy-wi/developer#1224]

**Comment by MikkelDK** [comment]
It's better if you are asking at discord! =) 

I'm pretty sure, the "domain" needs to pointing > to the easy-wi server via A record.

**Comment by Damerino** [comment]
Okay, but then how do I put the domain on the webspace? which path should I specify? 
Maybe you can help me :)

**Comment by gOOvER** [comment]
Thats no error. Pls close.
