### ISSUE TITLE
Ticket Kategorien funktionieren nicht

### ISSUE THREAD

**Issue by Bourns** [easy-wi/developer#1225]
Hi,

die Support Ticket Kategorien funktionieren nicht. Es können keine Kategorien erstellt werden.

Beste Grüße

**Comment by edraft** [comment]
Moin,

ich bestätige dies.

Ich habe des bezüglich noch ein wenig herum getestet. 

Wenn man in der Datenbank eine Kategorie manuell anlegt und danach eine Kategorie in Easy WI anlegt und nun alle Daten (Inklusive der manuell erstellen Kategorie als Unterkategorie von) angibt, funktioniert es.
Ich konnte bisher nur auf dem Weg eine Kategorie erstellen.

Leider kann ich nicht sagen, seid wann dies so ist :/
Mir ist der Fehler erst heute aufgefallen.

**Comment by GLITCH-Jan** [comment]
Getestet mit Debian 10 Buster + Unstable Install Skript = Funktioniert NICHT.
Getestet mit Ubuntu LTS 18.4.4 + Unstable Install Skript = Funktioniert.

Bitte in diesem Fall Ubuntu Verwenden.

**Comment by Nexus633** [comment]
Bei mir funktionieren die Kategorien einwandfrei, ich kann diesen Fehler nicht nachvollziehen. Ist der Fehler noch aktuell oder wurde dieser bereits gefixt?

**Comment by GLITCH-Jan** [comment]
Meines Wissens ... handelte es sich um einen Generellen Fehler mit Debian.... habe von vielen gehört das sie Buggy Ergebnisse mit MySQL erhalten (kein EasyWI verwendet) ... scheint also nicht direkt an EasyWI gelegen zu haben ....

PS: bei mir funktionierte es auch die ganze zeit

**Comment by Bourns** [comment]
Also bei mir funktionierte es bei Ubuntu nicht ;-)

**Comment by Nexus633** [comment]
Ubuntu Version? Plesk oder sonstige Verwaltungssoftware im Hintergrund laufen? Welche php Version?

**Comment by Bourns** [comment]
Zu der Zeit Ubuntu 16.04, 18.04 und PHP Version die zu der Zeit aktuellst und jeweils ein oder zwei Versionen darunter getestet. Jeweils mit komplett neuer Inytallation, mit und ohne Script. Im Hintergrund lief nichts anderes.

**Comment by Nexus633** [comment]
Ok also generell Ubuntu :-). Werde ich testen und wenn gefunden ein fix einreichen! Bitte habt Geduld. Bin derzeit die issues am durchgehen ;-)

**Comment by Bourns** [comment]
Das ganze ist im Dezember letzten Jahres gewesen. Es kann durchaus sein, das es mitlerweile behoben ist.

**Comment by Nexus633** [comment]
> Das ganze ist im Dezember letzten Jahres gewesen. Es kann durchaus sein, das es mitlerweile behoben ist.

Werde es dennoch testen da hier es noch als offen deklariert ist. Wollen wir hoffen das es behoben ist. Auf Debian funktioniert es einwandfrei.

**Comment by Bourns** [comment]
Ich habe ja den Beitrag gestartet. Wer die Tage auch nochmal ne installation starten, vielleicht kann ich dann genaueres sagen.

Beste Grüße
