### ISSUE TITLE
user-configs speichern

### ISSUE THREAD

**Issue by boyfromgermany** [easy-wi/developer#1227]
Guten Tag,

Ich habe ein Custom Template angelegt und dazu eine config-datei die der user bearbeiten kann

Das Problem ist nun, das diese Datei nicht Speichert.
ich habe bereits unter den logs: /home/easy-wi_gameserver/logs/
geschaut, kann hier jedoch keine Fehler finden.

**Comment by GLITCH-Jan** [comment]
Hey,
meinst du mit Custom Template ein Datei Template oder ein Gameserver Template?
