### ISSUE TITLE
Problems running/Installing Steam Games

### ISSUE THREAD

**Issue by LuxemGamer** [easy-wi/developer#1230]
I have freshly setup Easy Wi and a seperat gameserver. The Image Server is the default from easy-wi.
I added the Master Apps (CS:GO, Arma3, Ark, Minecraft) to the gameserver. When I add a gameserver with Minecraft as game to a user, it works fine, it starts and you can play on it. But if I do that with any steam game I get errors like

CS:GO
`LD_LIBRARY_PATH=/home/LXM_User_2-3/server/csgo/bin:/home/LXM_User_2-3/server/csgo:/home/LXM_User_2-3/server/csgo/bin:
Failed to open dedicated.so (libstdc++.so.6: cannot open shared object file: No such file or directory)
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Fri 27 Mar 2020 05:17:04 PM UTC: Server restart in 10 seconds`

Arma3
`Cannot exec './arma3server': No such file or directory`

So they don't find the files, but why? the Arma steamapps directory is empty, but the csgo one has multiple folders etc in it...

Thanks for your help

EDIT: Kann auch Deutsch :p

**Comment by MikkelDK** [comment]
1) Arma3 no such file = it's not installed. because _**You need a REAL account with the game!**_
2) CSGO - do this as (root) `apt-get install lib32stdc++6`

**Comment by LuxemGamer** [comment]
> 1. Arma3 no such file = it's not installed. because _**You need a REAL account with the game!**_

I tried to login with SteamCmd but it didn't change, is it a problem that I use Steam Guard?, or is the issue somewhere else?

**Comment by MikkelDK** [comment]
> > 1. Arma3 no such file = it's not installed. because _**You need a REAL account with the game!**_
> 
> I tried to login with SteamCmd but it didn't change, is it a problem that I use Steam Guard?, or is the issue somewhere else?

Probably because of steamguard. =)

**Comment by LuxemGamer** [comment]
> Probably because of steamguard. =)

So I removed the authenticator from my steam account (the mobile authenticator) but now everytime I want to push arma 3 on the gameserver I get a mail with the code I have to enter in steam. How and where should I enter the code?

**Comment by MikkelDK** [comment]
> > Probably because of steamguard. =)
> 
> So I removed the authenticator from my steam account (the mobile authenticator) but now everytime I want to push arma 3 on the gameserver I get a mail with the code I have to enter in steam. How and where should I enter the code?

I don't know how to, since I don't host ARMA 3, and I don't have the game.
You could _try_ disable the steam guard (totally) and see about its work.

**Comment by GLITCH-Jan** [comment]
Hey!
Hier mal auf Deutsch um Spiele mit Email Guard zu installieren musst du dich einmal via Putty als Gamemaster anmelden und die Steamcmd manuell ausführen! 

Also:
1. Als Gamemaster anmelden (nicht root)
2. Steamcmd im ordner Masterserver/steamcmd ausführen
3. Die mit deinem account einloggen | Nun wirst du nach dem Steamguard email code gefragt den eingeben
4. Nun speichert die SteamCMD den code und ein Login via EasyWI sollte nun möglich sein

@MikkelDK
Hey, you must login manually the first time to get access steamcmd via EasyWI ... i needed some time so figure that out ^^
