### ISSUE TITLE
ftp user idee/fix

### ISSUE THREAD

**Issue by Blackfire499** [easy-wi/developer#1236]
Hey Guys don't know if it is possible already but every server gets its Ftp user that's ok but why different folder? it would be better if you have one folder lets say for user2 in this folder you have your server and p-server folder.

And in the server folder you have <game>-<serverid> 

here a little example

default:
 - /home/gameservers/user2-1/server/<game>
- /home/gameservers/user2-2/server/<game>

clean/better looking:
- /home/gameservers/user2/server/<game>-<serverid>

This would make it look much cleaner.

and Ftp User could be still user2-<id> 

Would could do it myself but don't want to :)

**Comment by MikkelDK** [comment]
So you mean like example this:

You are adding 2 gameserver. so it should look:

- /home/gameservers/user2/IP-port1/
- /home/gameserver/user2/IP-port2/

We have earlier had the function once! but removed it.

https://github.com/easy-wi/developer/issues/961
https://github.com/easy-wi/developer/pull/986
https://github.com/easy-wi/developer/pull/985
https://github.com/easy-wi/developer/pull/984

**Comment by Blackfire499** [comment]
Ah ok, any reason you removed it?

**Comment by MikkelDK** [comment]
I didn't =) but you can read on these (tag) I did link.
