### ISSUE TITLE
Cannot exec './srcds_run': No such file or directory

### ISSUE THREAD

**Issue by Massim0Arts** [easy-wi/developer#1237]
Hey Guys,
I installed everything fine. But as soon i start the CSGO server i got this error.
Also it seems like the CS:GO Server didnt insalled right. I looked in FTP and the folders are kind of broke. Is there anything known bug or fix for it?

Would be nice.

Best regards
- Max

**Comment by MikkelDK** [comment]
Did you installed csgo serverfiles to /home/easy-wi/masterserver/csgo ?

E.g: `./steamcmd.sh +login anonymous +force_install_dir /home/easy-wi/masterserver/csgo +app_update 740 +quit`
