### ISSUE TITLE
webserver not reachable

### ISSUE THREAD

**Issue by Anokata42** [easy-wi/developer#1241]
Hello all,

I have installed a Debian 10.4 locally Then I downloaded and executed the "Easy-Wi Bash Installer". After I installed any additional software (which was necessary for the installation), I was asked to continue via https://ip/install/install.php.

When I call this page, I get the error message "ERR_CONNECTION_REFUSED" - although the server itself allows everything (since it can only be accessed locally).

If I install a pure Apache2 or Nginx on the same server, I reach the default website. If I then install easy-wi, the web server is not accessible again.

Did someone already have this problem and can tell me how to fix it?

Best regards,

**Comment by TheP3di** [comment]
Hi,
do you have an ssl-certificate for your web-site/-server?
Try http and not https.

Maybe a wrong web-server configuration.

regards
Pedi

**Comment by Anokata42** [comment]
Hey TheP3di,

thank you very much for your reply.

I get the same error message, no matter if HTTP or HTTPS. No matter if I tell you during the installation if SSL should be used or not. It is also independent if apache2 or nginx.

I also thought about a faulty configuration, unfortunately webserver under Linux was years ago, so my current knowledge is very limited what the configuration is about.

Since I am using a blank Debian 10, on which I only install Easy-Wi, can I assume that the included configuration is wrong?

Do you have a clue where I can start to check the configuration?

Best regards,

**Comment by GLITCH-Jan** [comment]
Hey,
You can join the EasyWI discord and reach out for me there... i would take a look at your installation ... and post the results here!

I think its an issue with your Certificate, The web server will not start if the VHOST template is wrong or not fully/right configured.
Its an Webserver / Config issue.


https://discord.com/invite/quJvvfF

YS

**Comment by Nexus633** [comment]
Check your webserver config. See what connection IP is set. If localhost or 127.0.0.1 is set, the error is somewhere else. If your LAN IP is used, you must also use it. You can also enter a local domain in your host file to come to the page. If this not, please join Our discord Server for Support

**Comment by GLITCH-Jan** [comment]
Local addresses are not supported
https://github.com/easy-wi/developer/issues/1244

YS
