### ISSUE TITLE
Cronjob Statuscheck.php restart Minecraft-server every 5 min

### ISSUE THREAD

**Issue by TheP3di** [easy-wi/developer#1242]
Hi,
ich bin neu bei easy-wi und wollte dies installieren.
Ich habe ca. drei Wochen das Problem, das die Minecraft-Server mit "SERVER WILL SAVE THE WORLD NOW" sich neustarten und somit die Verbindungen zum Spieler-Server trennen.

Dies ist immer der Fall, wenn die statuscheck.php ausgeführt wird (egal ob mit cron oder manuell)
Ohne statuscheck.php laufen die Server.

Ausgabe statuscheck.php: 
[statuscheck_ausgabe.txt](https://github.com/easy-wi/developer/files/4741511/statuscheck_ausgabe.txt)
IP zensiert mit: XXX.XXX.XXX.XXX

Ausgabe Minecraft-Server: 
[minecraft screenlog.txt](https://github.com/easy-wi/developer/files/4741525/minecraft.screenlog.txt)
Keine Veränderung oder Zensierung

Neu installierte System (Testserver):
OS: Debian 9 64-bit
Datenbank: MySQL
PHP: Standard 7.3 [(getestet mit php5 /5.6 , php7.0.33, php7.2.31, php7.3.18) FastCGI]
Webserver Apache2
Firewall: Mit und ohne getestet
Minecraftversion: 1.15.2

Ich hoffe ihr könnt mir helfen.

Vielen Dank
Pedi

**Comment by DennisF10** [comment]
Make sure the branding option is set to no or the server name includes the servertag

**Comment by TheP3di** [comment]
Hi DennisF10,
thank you for your help.
Branding Option is setted to no.
My Gameserver easy-wi options:
[Minecraft-serversettings.pdf](https://github.com/easy-wi/developer/files/4742684/Minecraft-serversettings.pdf)


My Gamemaster easy-wi options:
[Gamemaster-serversettings.pdf](https://github.com/easy-wi/developer/files/4742682/Gamemaster-serversettings.pdf)

Thank you
Pedi

**Comment by edraft** [comment]
Moin,

ich werde mir das demnächst noch genauer anschauen aber hier schon mal mein Stand:

Ich habe zwei Minecraft Server einen Spigot 1.15.2 und seid vorgestern einen Forge 1.7.10, der Spigot läuft seelenruhig vor sich hin wohingegen der Forge nach ca 5 Minuten mit der Meldung "SERVER WILL SAVE THE WORLD NOW" neustartet.

Ich habe bisher die Beobachtung gemacht, dass vor dem shutdown immer die statuscheck.php aufgerufen wird. 

Interessant finde ich, dass dies auf den Forge und nicht auf den Spigot zutrifft.

OS: Debian 10.3
Datenbank: MySQL
PHP: 7.3
Webserver: Apache2
Firewall: ufw (keine Sorge, ist richtig eingestellt ^^)

MfG

edraft

**Comment by primeas-de** [comment]
Mach den Auto Restart aus dann sollte es gehen. das liegt dadran das easy-wi denkt das der server offline ist und startet ihn neu. Das Panel zeigt dir den Server auch Offline an obwohl er Online ist oder ? (Roter Hintergrund)

**Comment by TheP3di** [comment]
Hallo,
und danke @primeas-de das du geantwortet hast und sorry für die späte Antwort..
Der Server wird als Online angezeigt, grün hinterlegt. Er startet diesen immer neu bzw. er meldet das der Server ein Backup machen möchte im Minecraft-Chat, danach startet er ihn immer neu. Ich Installiere nun Easy-wi Gameserver auf einen neuen Server und teste dies erneut. Ich melde mich dann noch einmal.

**Comment by TheP3di** [comment]
Hi,
hier ist noch einmal ein Mincecraft Log von einem neuen Server, GameMaster und Minecraft-Server. Nichts gemacht außer Server installiert, GameMaster und dann den Minecraft.
Der MinecraftServer will ein Backup machen laut Ingame-Chat, spuckt dann im Log aus "Unknown or incomplete command, see below for error..." (siehe Logfile ganz unten) und paar Java Fehler.

[2020-07-10-7.log](https://github.com/easy-wi/developer/files/4905619/2020-07-10-7.log)

Wie kann ich diese beheben oder woran liegt es das ein komplett neuer Server schon direkt die Fehler hat?

Danke für eure Hilfe

Grüße
Pedi

**Comment by GLITCH-Jan** [comment]
Also die logfile sagt aus das der Server Probleme hat und "hinterhängt" die Java exception unten sagt aus das es einen Fehler beim lesen von "bytes" gekommen ist ... hast du dir die Server Auslastung mal genauer angesehen wenn der Fehler auftritt?

**Comment by TheP3di** [comment]
Hi,
ja habe ich. Habe es auch noch einmal auf einen komplett neuen Server aufgesetzt und Minecraft 10GB-Ram zugewiesen.

Netzwerk: <5%
CPU: <22%
RAM: <29%
HDD: <18%

Vlt. hilft diese Info noch.
P.S.: 1x Die Daten für die Web-Oberfläche lade ich auf ein Webspace(extern) hoch und rufe die Seite/Installer über den Browser auf.
1x Auch schon auf den selben Server wie die Gameserver gemacht. Aber nicht über den easy-wi installer.sh, sondern wie oben beschrieben die Daten auf meinen Webserver (gleichzeitig Server für die Gameserver) hochgeladen und installiert.

Danke
Pedi

**Comment by Nexus633** [comment]
Mach mal ein update vom minecraft server. Ich hatte es in einem Fix behoben. Eventuell löst das dass Problem. (#1173)

**Comment by Lacrimosa99** [comment]
Bitte die "Autorestart" Funktion im MC Template deaktivieren.
Es gibt aktuell noch ein Bug in der Statusabfrage, welche auch das Backup bei MC antriggert.

**Comment by Nexus633** [comment]
Also die Statusabfrage funktioniert einwandfrei. Was ich bei dir aber sehe: Dein Minecraft server startet mit 0.0.0.0 Query. Demnach kann sich die Statusabfrage nicht mit dem Queryserver von Minecraft verbinden und denkt das er aus ist. Hast du in deiner   server.properties die beiden optionen drinne ?

query.port=25565 (query.port = Serverport + 10)
enable-query=true

wenn nicht trage es nach. Dann kannst du auch die Autorestart funktion wieder einschalten. Solltes su das nicht wollen, musst du den Autorestart ausgeschaltet lassen, da das system sonst weiterhin denkt das dieser Offline ist!

**Comment by TheP3di** [comment]
Hi,
vielen Dank für eure Hilfe.

Hier ist meine Minecraft-Server Config (Nur server-ip entfernt)
[server.properties.txt](https://github.com/easy-wi/developer/files/5011372/server.properties.txt).

Sind beide drin:
query.port=25565
enable-query=true

Das Ausschalten der Auto-Start Funktion führt bei der Ausführung der statuscheck.php zu keinem Neustart des Servers und zu keiner Meldung "[Server] SERVER WILL SAVE THE WORLD NOW" im Game-Chat.
Der Server wird aber auch daher immer als offline angezeigt, obwohl er eingeschaltet ist und funktioniert. Start und Stop funktioniert jedoch ohne Probleme.

Also vermute ich, dass es sich um einen Bug handelt wie von Lacrimosa99 geschrieben.
Ich hoffe das dieser bald behoben wird :-)

Vielen Dank allen und wenn einer doch eine Lösung finden sollte damit es mit Autostart und Status-Check funktioniert, immer her damit.

Pedi

**Comment by Nexus633** [comment]
Hast du denn die aktuelle Version? Ich habe die autostart Funktion eingeschaltet. Wenn du heute abend Zeit hast, könntest du mich bei discord anschreiben. Wir gucken uns das an.

**Comment by AEon-Jan** [comment]
Keine Antwort - Problem wird als Gelöst angesehen
