### ISSUE TITLE
Webpanel Not Found

### ISSUE THREAD

**Issue by Minialer** [easy-wi/developer#1244]
First I installed an Ubuntu 20.04 server.
then LAMP (https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-20-04)
and Easy-WI Webinterface
(https://easy-wi.com/de/installation/web-interface/)

The installation says:
Easy-WI Webpanel setup is done regarding architecture. Please open https://192.168.178.32/install/install.php and complete the installation dialog.
DB user and table name are "easy_wi". The password is "************".

But at "https://192.168.178.32/install/install.php" it just say "Error: network timeout"
(at "192.168.178.32/install/install.php" it says
"Not Found
The requested URL was not found on this server.
Apache/2.4.41 (Ubuntu) Server at 192.168.178.32 Port 80")

What do I wrong?
Thanks in advance

**Comment by GLITCH-Jan** [comment]
Hey,

Are you able to connect via a Local address?

because 192.168. is ONLY used in local networks ... (like your phone and Computer in you home Network)

I am not sure if it even Possible to Host easywi wich such an address... i recomend you to check the Host and IP Configs and use a Public address

YC Jan

**Comment by Minialer** [comment]
My Server is next to me.
192.168.178.32 is the right adress.

**Comment by GLITCH-Jan** [comment]
Then check your Webserver on the server ... 

Is the Web Service up an running? (Standard Apache page?)
If Yes check the VHOST file for easywi 

If There is no File you can install the Webpanel by hand ...

**Comment by Minialer** [comment]
Standard Apache2 page is running.
How can I check the VHOST file for easywi?

**Comment by Minialer** [comment]
I completely reinstalled all of this, but the same error occurs.

Ich das alles nochmal komplatt neu installiert, aber es kommt der gleiche Fehler.

**Comment by Lacrimosa99** [comment]
Wir unterstützen keine lokale Home Installation (VirtualBox/Hyper-V) da die IP nicht validiert werden kann.
