### ISSUE TITLE
Custom modul

### ISSUE THREAD

**Issue by NYLoRD** [easy-wi/developer#1245]
Hello how to create the custom modul that it will be show in the div: box-body and not at the top of the site?

Thanks. 
![image](https://user-images.githubusercontent.com/5408449/85061762-a5f25b80-b1a7-11ea-9761-b65b682292ad.jpg)

**Comment by GLITCH-Jan** [comment]
Hey, Sorry for the late Reply.

some how your Module is placed above the header ... can you check the .php files for me?
There should be something with "custommodule"

Otherwise visit the discord for direct replys: https://discord.gg/hEnBsUk

**Comment by NYLoRD** [comment]
> Hey, Sorry for the late Reply.
> 
> somehow your Module is placed above the header ... can you check the .php files for me?
> There should be something with "custommodule"
> 
> Otherwise visit the discord for direct replys: https://discord.gg/hEnBsUk

Under /stuff/custom_modules/ is my php file with the module. What u want so See? My php file?

**Comment by AEon-Jan** [comment]
Please read the Update notes!
your Module is in our vanilla build.

just go to the "example module"

#closed
