### ISSUE TITLE
Teamspeak Backup Feature Problem

### ISSUE THREAD

**Issue by cyberlimbo** [easy-wi/developer#1248]
Everything is working fine with teamspeak server (if we do not use the backup feature)..
If we use the backup feature, the backup is successfully created but after applying it, 
a new server ID is created and the panel stop detecting the server.
All teamspeak panel options stop working after that.

Query error: "invalid\sserverID"

**Comment by GLITCH-Jan** [comment]
Hmm Strange...  i will try to reproduce that ... 

so did you tryed to delte the Old server (only from the DB) and redetect the new one ? You dont have to Delete the Whole Server ... just redetect the new one.... its a bit messy but when TS is giving you a new ID ... its the only way

**Comment by cyberlimbo** [comment]
I'll take a look in this "problem" again this week and give feedback ;)
