### ISSUE TITLE
User Groups Problem

### ISSUE THREAD

**Issue by cyberlimbo** [easy-wi/developer#1249]
User Groups are not working properly.

Example..
I created a group with permitions to:
-User settings
*The user assigned with this group cant access account "Settings" menu (instant logout).

**Comment by cyberlimbo** [comment]
any solution?

**Comment by GLITCH-Jan** [comment]
Can you give me the URL youre trying to access?

maybe its an issue with the URL ... there was a bug with the Setting of a user where the User = user.php tryed to access admin.php

that resulted in an instant logout ...

**Comment by cyberlimbo** [comment]
> Can you give me the URL youre trying to access?
> 
> maybe its an issue with the URL ... there was a bug with the Setting of a user where the User = user.php tryed to access admin.php
> 
> that resulted in an instant logout ...

yeah, i think thats the problem..
The "Settings" link is "https://example.com/admin.php?w=su"
