### ISSUE TITLE
Email settings not working

### ISSUE THREAD

**Issue by cyberlimbo** [easy-wi/developer#1250]
In "Email settings"
SMTP option is not working.
(Using a valid outgoing server address/port and emails are not being sent..)

**Comment by cyberlimbo** [comment]
any solution?

**Comment by primeas-de** [comment]
SMTP Server Setting (user: email@email.de Port: 25 Host: mail.domain.com Setting: TLS) for me is working fine, check the mailo.err log file on your machine to check where is the error
