### ISSUE TITLE
CsGo server.cfg file not being created

### ISSUE THREAD

**Issue by cyberlimbo** [easy-wi/developer#1252]
Hi

Why is csgo server.cfg file not being created?
When trying to edit using "Server Configs" option:
" Error writing config: /csgo/cfg/server.cfg "

*Using latest easy-wi panel version
*Using Debian 10 x64 game server root

any solution?

**Comment by MikkelDK** [comment]
Because, you need to create one. Under **masterserver/csgo/csgo/cfg/** inside there, you need to create server.cfg :)

**Comment by cyberlimbo** [comment]
I already tried that and still the same problem :(

**Comment by MikkelDK** [comment]
Is it there, if you try resync reinstall. Or create a new server.

**Comment by cyberlimbo** [comment]
Same problem after reync or reinstall xD

**Comment by MikkelDK** [comment]
Try this: (If you are using easy-wi as username)

`nano /home/easy-wi/masterserver/csgo/csgo/cfg/server.cfg`

```
hostname "server by cyber-limbo"
sv_password ""
rcon_password ""

```
**Ctrl+O and Ctrl+X**
**chmod 640 /home/easy-wi/masterserver/csgo/csgo/cfg/server.cfg**

And check about it will be there. ^^ it should work anyway =D

**Comment by cyberlimbo** [comment]
Thats exactly what i have tried before.
Didnt worked.
I lot my patience, i have other things to do.
Thanks for the help anyway ;)

**Comment by primeas-de** [comment]
edit the configs work over default ftp connection if you have no acces to the ftp by a client you cant edit the files by the panel its a problem with AuthOrder (mybe it is set on mysql and not pam / unix) there are both ways why this not work but the most problem is Umask (chmod) or the AuthOrder =)

**Comment by cyberlimbo** [comment]
-I can access using external ftp (filezilla or winscp).
-I can access using panel "ftp link" option. 

The only problems i want to solve:
-When i access using "web ftp" it shows an empty folder.
-I cant edit files using "Server configs" option from the easy-wi panel.
-"Live console" panel option not working: "Cannot download screenlog from server/csgo/screenlog.0"
(already reported by other users...)

**Comment by GLITCH-Jan** [comment]
Looked into the issue.

It seems a issue with MonstaFTP on Webserver side : ftp_rawlist(): php_connect_nonb() failed: Operation now in progress (115)

@cyberlimbo  Will look into his Server Settings.

I will leave the issue open for Contribution

**Comment by GLITCH-Jan** [comment]
Issue found!

The port of the FTP server was not the same port as from Monstaftp (WebFTP)

#closed
