### ISSUE TITLE
Error: FTP Access | User keinen Zugriff auf FTP / Console

### ISSUE THREAD

**Issue by MasterShadowDE** [easy-wi/developer#1253]
Ich habe einen Gameserver angelegt und auch dafür einen Benutzer bestimmt. 

Logge ich mich jetzt mit diesem Benutzer ein und möchte dort in der Config etwas ändern kommt immer der Fehler 

"Error:FTP Access" 

Ich hab auch schon in den Logs geschaut nur dort taucht nirgends ein Fehler auf. 

Kann mir evtl, jemand sagen wo der Fehler genau liegen kann ? 

Gruß

**Comment by GLITCH-Jan** [comment]
Hey,
kannst du WebFTP verwenden?
Hast du das Passwort geändert?
Welche Logs hast du dir angeschaut?
Welches OS? und Version?
Welchen Installer hast du verwendet?

**Comment by Nexus633** [comment]
@MasterShadowDE wir benötigen Infos. Am besten postest du auch gleich die proftpd.conf dann kann man eventuelle Fehler ausschließen/behandeln

**Comment by AEon-Jan** [comment]
User does not answer
