### ISSUE TITLE
Dns not showing correctly

### ISSUE THREAD

**Issue by cyberlimbo** [easy-wi/developer#1262]
Dns is not showing correctly in servers list
example:  i have added this dns "sv.domain.com" to Apps/Game master.
In "Game server" -» "Overview" and inside the clients account, the dns of the game servers is showing "sv.domain:27015"
not showing the complete dns.
The " .com " is not present.

Regards

**Comment by Nexus633** [comment]
I did not notice. I'm sorry. I'm looking at this tonight. He filters out the tld. Then I will check the domain to be checked against the dns afterwards. Then he doesn't filter anything away.
