### ISSUE TITLE
[BUG] Log-Out loop wieder da. (New theme)

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#1284]
Moin, Logout-Loop ist wider da u.a. wegen

/favicon.ico
/css/ftnaws.min.css

Mit folgenden änderungen scheint es zu klappen:

[template.zip](https://github.com/easy-wi/developer/files/5012209/template.zip)

**Comment by AEon-Jan** [comment]
guck ich mir sofort an

Danke

**Comment by AEon-Jan** [comment]
Welche Änderungen hast du vorgenommen ich sehe hier nur das die Socialmedia Links Entfernt wurden...

LG

**Comment by MadMakz** [comment]
`<link rel="shortcut icon" type="image/x-icon" href="<?php echo (isset($rSA['favicon']) and !empty($rSA['favicon'])) ? $rSA['favicon'] : 'images/favicon.ico';?>" />`

`<!--<link href="css/ftnaws.min.css" rel="stylesheet" type="text/css">-->`

**Comment by AEon-Jan** [comment]
Änderungen übernommen ... Die datei war garnicht mehr vorhanden ... 

Danke für die deine Info 👍
