### ISSUE TITLE
[enhancement] Bitte Twitter widget / call home entfernen oder optional machen.

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#1286]
![twitter](https://user-images.githubusercontent.com/3930214/89124477-899c4b00-d4d7-11ea-98a5-52e4a94de24a.jpg)

Wenn man es als reines Verwaltungstool betreibt bitte so wenig wie möglich oder gar kein call-home betreiben.

**Comment by AEon-Jan** [comment]
https://github.com/easy-wi/developer/commit/94fd8334a8ad3be3d8a3e3eda1178c481790d332

Es wurde die selber abfrage im header wie auch im home bereich verwendet ... sollte nun also "abschaltbar" sein...

LG
