### ISSUE TITLE
[BUG](New Theme) Kein user-dropdown / logout möglich in mobiler Ansicht.

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#1287]
![1024-2105](https://user-images.githubusercontent.com/3930214/89124637-ce74b180-d4d8-11ea-8131-56553903be1b.jpg)

**Comment by AEon-Jan** [comment]
Hey, Ich guck mir das sofort an und werde zeitnah ein Fix bereitstellen...


LG

**Comment by AEon-Jan** [comment]
Workaround ist das ... werde es zu einem späteren zeitpunk natürlich "schöner" fixen aber damit es erstmal wieder funktioniert....
