### ISSUE TITLE
[BUG] Latest panel version bug

### ISSUE THREAD

**Issue by cyberlimbo** [easy-wi/developer#1293]
**Describe the bug**
-When trying to edit user account "Settings" = logout from the panel
-When trying to stop / start teamspeak server = logout from the panel

**To Reproduce**
1. Go to 'VoiceServer' --» 'Overview'
2. Click on a random username
3. Try to stop / start a ts3 server 
4. You got instantly logout from the panel
**Same happens if you login a user account and try to edit the "Settings"

**Expected behavior**
Usually the server starts / stops xD

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: chrome
 - Version: Latest panel version (v6.2.0)

**Comment by AEon-Jan** [comment]
Please Try Again with the Developer Version:

-Go to Settings
-Search for "Developer"
-Set it to "ON"
(this can take up to an hour)
-Update the panel to : 6.2.0.1.


Sadly i couldn't reproduce the issue.


If you have the same issue again after updating to the DEV Version:
-Which Server OS ?
-Which Design Template?

**Comment by cyberlimbo** [comment]
Thanks.
It worked ;)

**Comment by AEon-Jan** [comment]
Glad to hear!

Were Fixed a bug with the logins in the Dev version ^^.
