### ISSUE TITLE
easy-wi error

### ISSUE THREAD

**Issue by Pixel-Games-Studio** [easy-wi/developer#1294]
If I try to finish the installation, I get this:
![easy-wi](https://user-images.githubusercontent.com/65785173/95681471-587b7d80-0be0-11eb-9d86-2adf42835cea.PNG)

**Comment by AEon-Jan** [comment]
With installer or manual install ...?

PLEASE PROVIDE MORE INFORMATIONS!

**Comment by gOOvER** [comment]
I bet, he add wrong Login Data. Not really an error

**Comment by AEon-Jan** [comment]
I think...

-Wrong Login Data
-Wrong file rights 
-Maybe Wrong DB Setup / File Setup


but we cannot isolate the error in this way

**Comment by Pixel-Games-Studio** [comment]
I copied the login-data fom my terminal!

It was the installer!

**Comment by Pixel-Games-Studio** [comment]
Jan? Can you help me please?

I`m not good at programming

**Comment by AEon-Jan** [comment]
PLEASE PROVIDE MORE INFORMATIONS!

Next time use the Issue Template here .... so i dont have to ask you every Question.


OS ?
OS Version ?
Installer Version ?
Which User did u used to Execute the installer ?
Is the OS a Fresh Install ?
Any Issues in the Installer ?

MOST IMPORTANT: Did you tried to Reset the DB Password ?

**Comment by Pixel-Games-Studio** [comment]
OS: Debian
OS V: Ubuntu 18.04 Bionic Beaver (LTS)
Installer V: https://github.com/easy-wi/installer/archive/master.zip
User: root
Fresh Install: yes
issues in the installer: no
Tried to reset DP Password: no
