### ISSUE TITLE
Easy WI help

### ISSUE THREAD

**Issue by Pixel-Games-Studio** [easy-wi/developer#1295]
If I try to finish the installation, I get this:
![easy-wi](https://user-images.githubusercontent.com/65785173/95681471-587b7d80-0be0-11eb-9d86-2adf42835cea.PNG)

OS: Debian
OS V: Ubuntu 18.04 Bionic Beaver (LTS)
Installer V: https://github.com/easy-wi/installer/archive/master.zip
User: root
Fresh Install: yes
issues in the installer: no
Tried to reset DP Password: no

**Comment by MikkelDK** [comment]
Why you open a new issue? 
Just read the error...

As it says: "**Access denied for user for MySQL**" and it says too, it can't **create** stuff/config.php & stuff/keyphrasefile.php

**Comment by AEon-Jan** [comment]
1st. Debian and Ubuntu are 2 Different OS, How can you install debian but the version is Ubuntu?!
2nd The installer you mentioned is NOT the installer i meant. i meant the SSH Installer.
3th We cant help you here with Installation Please Head over to our Discord: https://discord.com/invite/quJvvfF
