### ISSUE TITLE
[BUG] [PLESK] Screenlog cannot be reached

### ISSUE THREAD

**Issue by FlashModz** [easy-wi/developer#1296]
**Describe the bug**
When we create a game server for a client, it really adds to the interface and installs.

On the other hand, as soon as we try to access the console, it returns that the screenlog file does not exist.
Testing with minecraft Spigot

**To Reproduce**
1. Create a game server with Minecraft Spigot
2. Assign to an user
3. Directly from the user category, then click on the user's name
4. Access the game server console

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - Browser : Chrome
 - Version : 86.0.4240.75

**Comment by AEon-Jan** [comment]
Can you access WebFTP?
Did you changed any FTP Passwords?
Are you sure the spigot Jar is Uploaded Correctly to the master ?


Can you Provide some more info about the Server? (debian? Ubuntu ? etc...)

**Comment by FlashModz** [comment]
Hi @AEon-Jan ,

FTP via web returns the error (The folder does not exist)
I haven't changed any FTP password
The version works on a server created before the last Easy-Wi update

Server :

- OS : Ubuntu 16.04
- Content : (Plesk and Easy-Wi GameServer)

**Comment by AEon-Jan** [comment]
is this your 1st server?

Please Try to Remove the Server and add the server again!

If this is not working for you:
Check your ProFTPD Settings!
Make sure you can access FTP with the Webpanel!

**Comment by FlashModz** [comment]
Thank you !
I had looked at the Easy-Wi settings but had not looked after Plesk was upgraded.

**Solution:**
The latest plesk update adds an limit All in PSASERV and group ROOT.
This breaks the easy-wi config.

**Comment by AEon-Jan** [comment]
Ok so your problem is solved now ?

I will leave this open ... maybe other users will run into the same problem!

**Comment by FlashModz** [comment]
Yes @AEon-Jan problem solved now 👍 
Many thanks for your help ;)
