### ISSUE TITLE
Bug, Servers Infinity Install / Map Unknown

### ISSUE THREAD

**Issue by thedoc013** [easy-wi/developer#1298]
Hello i have easy-wi installed on debian  Betriebssystem: ‪Debian 9.13‬ 

Nur hab ich das Problem das Weder die Crons Laufen nachdem ich sie unter /etc/cron hinzugefügt habe , 
noch das die Server starten oder sich spiele installieren 

Wäre super wenn mir jemand helfen könnte , danke 

------------------------------------------------------------
Hello, I installed easy-wi on debian managed: Debian 9.13

I only have the problem that neither the crons are running, which I added under / etc / cron,
nor that the server start or let play

Would be great if someone could help me, thank you

and i add now manuelly the crons over plesk , but when i start a server he said crashed 
think theres something wrong

Testserver Info:

Template
mc
Status vom
10.11.2020 15:20:02
Map
Unknown
Spieler
0/0
Maximaler Ram
1024 MB
FTP-Link
Censored
FTP-Adresse
Censored
FTP-Benutzername
user2-2
FTP-Passwort
Censored

[home]
path = /home
mountpoint = /
size = 500GB
default = 1

my path to the script is : /var/www/vhosts/privacy-hosting.in/gp.privacy-hosting.in

when i install any game then installed it endless very creepy

i´ve used the web installer

**Comment by thedoc013** [comment]
and i add now manuelly the crons over plesk , but when i start a server he said crashed 
think theres something wrong

**Comment by thedoc013** [comment]
Testserver Info: 

Template
    mc
Status vom
    10.11.2020 15:20:02
Map
    Unknown
Spieler
    0/0
Maximaler Ram
    1024 MB
FTP-Link
    Censored
FTP-Adresse
   Censored
FTP-Benutzername
    user2-2
FTP-Passwort
    Censored

**Comment by AEon-Jan** [comment]
Gameroot was not installed.
It is not possible to install the Gameroot on a Plesk machine!

#Closed
