### ISSUE TITLE
[BUG] CsGo masterserver not being updated

### ISSUE THREAD

**Issue by cyberlimbo** [easy-wi/developer#1302]
CsGo masterserver not being automatically updated.
I tried to do it manually, but still the same problem.
 
**To Reproduce**
1. Go to "Master apps Update"
2. Select the csgo sever and choose to update it
3. Basically the server is not being updated. 

Debian 10 x64
Latest developer panel version

**Comment by tellerrocker** [comment]
Same issue here - singel server log:

`MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.`

**Comment by AEon-Jan** [comment]
hey,

Did you tried a manual Update? via Shell?

**Comment by cyberlimbo** [comment]
Manual update it works, but it is suposed to work with easy-wi "Master apps Update".

**Comment by tellerrocker** [comment]
We tryed but didn't work at all

**Comment by AEon-Jan** [comment]
the update function in easy-wi worked for me ... can you paste your logs from update-csgo.log?
(/home/<master user>/logs/update-csgo.log)
and check the date of the file with "ls -a"

**Comment by cyberlimbo** [comment]
In my case "update-csgo.log" file it is completely empty, maybe because i've reinstalled easy master server in another machine
just to test if it works or not, but no success..

**Comment by tellerrocker** [comment]
So also laut Serverkonsole ist der einzelne Gameserver auf dem neusten Stand und läuft auch. Nun will ich drauf und

`Disconnect: Server uses different class tables.`

`version : 1.37.7.4/13774 1213/8012 secure [G:1:3903959]`

**Comment by cyberlimbo** [comment]
Users are still waiting for any news / solutions / updates...
Easy-wi project is dying day by day, it is sad :(

**Comment by cyberlimbo** [comment]
Problem solved.  I'm not sure what's the solution but i only edited my gameserver dns's to cloudflare ones and steamcmd started installing / updating the servers xD   then i removed the cloudflare dns's and restarted the machine to test if the problem come back, but everything is still working fine...  lol      I really dont understand wtf just happened ahah
