### ISSUE TITLE
Uninstall Easy-wi?

### ISSUE THREAD

**Issue by PassiHD2004** [easy-wi/developer#1303]
I want to uninstall/remove Easy-wi, but dont know how.

**Comment by MikkelDK** [comment]
Remove easy-wi Database, the Interface under `/home/easy_wi` and don't forget to remove the easy-wi user.

And remove files from easy-wi (eg: web files)

**Comment by PassiHD2004** [comment]
> Remove easy-wi Database, the Interface under `/home/easy_wi` and don't forget to remove the easy-wi user.
> 
> And remove files from easy-wi (eg: web files)

There isnt a easy-wi user thats the problem....

**Comment by MikkelDK** [comment]
If you only did installed the "web part" > remove it from your ``/var/www/html`` and remove the database from MySQL =)

**Comment by PassiHD2004** [comment]
> If you only did installed the "web part" > remove it from your ``/var/www/html`` and remove the database from MySQL =)

Aight thanks
