### ISSUE TITLE
[BUG] Adding Master App throws back to login

### ISSUE THREAD

**Issue by cleanlock** [easy-wi/developer#1305]
**Describe the bug**
When I try to add a Master App, it immediately throws me back to the login. We're using Cloudflare and NGINX with PHP Version 7.3

**To Reproduce**
1. Go to 'App/Game Master'
2. Click on 'Master apps'
3. Click on add
4. Select the game you want
5. Click on Add and confirm with "OK"
6. Throws back to loginpage

**Expected behavior**
Well obviously I shouldn't get thrown back to the loginpage.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 84.0.2 (64-Bit)

**Server**
- OS: Debian 10 64-Bit

**Comment by cleanlock** [comment]
I've added the game (CS:GO) via database to the App/Game Master servers, but no masterserver will be installed by doing this, so I tried to force it by doing an update through the "Master apps update" tab, no luck.

**Comment by AEon-Jan** [comment]
Hey, Sadly i cant reproduce that,,,

Did you checked your SSL settings? Cache? 
Are you using a Proxy ? Cloudflare? 


Any PHP Errors in log?

Thanks,
Jan

**Comment by feartheduck** [comment]
check if you have all icons.
because by default you dont have paper.png so panel dont have file back to login.
that is a miss files .
Check images/games/icons/paper.png if dont have copy hex and paste (rename to paper.png)

And cabum works :D

**Comment by AEon-Jan** [comment]
No reply - So it is considered solved
