### ISSUE TITLE
Questions and Concerns: Attempting to Understand This "Server Manager" For Game Servers

### ISSUE THREAD

**Issue by FriendlyGamer** [easy-wi/developer#1310]
Hello there and I hope this finds you well! I don't have Discord anymore since it's birching about my account all of the time and I can't set up 2FA since I am deaf and blind (they don't have alt emailing, SMS or even hardware as 2FA options). 

I am trying to find another option for my Minetest 5.4.1 that is easier to manage than to dealing with Tmux, CLI editing and so forth. To switch from my shared gaming provider that isn't cutting it for me due to their lack of features. So moving to a VPS might do me better and either let me do it directly in the panel or at least at the VPS's level. 

So anyways, I am seeking for... 

1. Does the panel "ez" installer get you going right there and then? Or does the environment have to be already set up in advance? Additionally once set apart from updating the panel and dependencies on the OS, do I need to concern myself with the VPS there after? Or it is pretty much "as easy as shared hosting" after that?
2. Does the panel support "custom" processes? If so how exactly? Do you need a query/RCON? Or will a game like Minetest (LUA based) would works just fine and give me access to at least "the basics" like start, restart, stop, file manager, etc? Even if I am not gonna get player counts and all of that "jazz" from the panel itself?
3. Does the panel have custom scheduling if at all? If not, I may do the backup "manually" at the OS level of the VPS through cron or whatever right? If I need to do this manually, where are the game servers' contents are gonna be stored by default?

Thank you very much in advance!

**Comment by 4deevspt** [comment]
if you read on website there anwer your questions.

**Comment by AEon-Jan** [comment]
Please check Discord if you need more help!
