### ISSUE TITLE
Need help with Error: No SQL server running but required for Webpanel installation.

### ISSUE THREAD

**Issue by WolfzzzYT** [easy-wi/developer#1315]
Hey, quick question:
I have just tried to install the Easy-wi web interface using the installer script, but just got the error message
"Error: No SQL server running but required for Webpanel installation." receive.
I've tried both MySQL and Mariadb, but both produced the same error. Could someone help me with this?
Thank you in advance ;D
Ps I use VPS Ubuntu 20.04 LTS 64bit

**Comment by ripkens** [comment]
Check where MySQL ist listening

`netstat -l --numeric-ports | grep 3306`

If it is listening on localhost, use localhost or 127.0.0.1 for the connection.
If it only listens on the external IP, use the external ip or change MySQL config.
If it is not listening, it is not installed or not running.

**Comment by AEon-Jan** [comment]
Please check Discord if you need more help!
