### ISSUE TITLE
[BUG] Updater does not update version in table.

### ISSUE THREAD

**Issue by AEon-Jan** [easy-wi/developer#1319]
**Describe the bug**
Version is not updated in the Database

**To Reproduce**
Update -> check DB -> Update is still pending

**Expected behavior**
Update will be dismissed when the Database Version is matching the Github version

Will Check on it Later

**Comment by AEon-Jan** [comment]
Even if the update is Still pending ... it should be installed.

You could add the version manually to the database or just ignore the update button.
Until i fixed it

**Comment by 4deevspt** [comment]
Already fix.

Open update.php

After that 
if (versioncheck($version, '6.2.0', 'update_618-620.php', $response)) {
    $version = '6.2.0';
}

add

if (versioncheck($version, '6.2.0.1', 'update_620-6201.php', $response)) {
    $version = '6.2.0.1';
}
if (versioncheck($version, '6.2.1', 'update_dev_6201-621.php', $response)) {
    $version = '6.2.1';
}

change 
if (versioncheck($version, $devVersion, 'update_dev_620-6201.php', $response, true)) {
to 
if (versioncheck($version, $devVersion, 'update_dev_6201-621.php', $response, true)) {


check if you have file . update_dev_6201-621.php
open and check if have this 

$query = $sql->prepare("INSERT INTO `easywi_version` (`version`,`de`,`en`) VALUES
('6.2.1','<div align=\"right\">22.12.2021</div>

for me works

**Comment by AEon-Jan** [comment]
Will check that ASAP.

**Comment by AEon-Jan** [comment]
Fixed
