### ISSUE TITLE
[BUG] login issues

### ISSUE THREAD

**Issue by alix1383** [easy-wi/developer#1321]
i can't login in panel

**Comment by 4deevspt** [comment]
what version you have ?

**Comment by alix1383** [comment]
last version

[error.log](https://github.com/easy-wi/developer/files/7854711/error.log)

**Comment by 4deevspt** [comment]
PHP Warning:  Unknown: write failed: No space left on device (28) 
Have space on webhost ?

**Comment by alix1383** [comment]
6gb free
need more?

**Comment by 4deevspt** [comment]
delete error log, and try login again

because to logs xD

**Comment by alix1383** [comment]
fixed :) ty dud

**Comment by alix1383** [comment]
I think The reason low space
but 5gb Enough 
when free up its fixed
sry for bad English

**Comment by 4deevspt** [comment]
:D if work works :D close ticket :D
