### ISSUE TITLE
[BUG] Always getting logged out when navigating anywhere

### ISSUE THREAD

**Issue by NoobKeksTV** [easy-wi/developer#1329]
I did a fresh install of easy-wi and now whenever i log in and want to navigate somewhere else other than the main page i get logged out.  Issue was there in 6.2.0 and is also there in 6.2.1. 
Tried both Chrome and Edge and Firefox and all have the same issue.
I didnt use the Installer as i have a alredy running Server i want to install it on. No i can not try the installer on a fresh server as i dont have any. 

**Expected behavior**
Well. Obviously that i can navigate, configure and actually use the Panel at all.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome, Firefox, Edge 
 - Version all latest versions

**Comment by AEon-Jan** [comment]
Check your cache / webserver cache / cloudflare cache and delete it.
If the error continues, check your theme to see if your SSL certificate is valid anywhere.
E.g. already a wrongly linked picture already ensure that your browser classifies a single page as not safe, then this page is considered as compromised.

Please check Discord if you need more help!

**Comment by NoobKeksTV** [comment]
yes, after over 2 months of waiting on any possible fix the issue still persists. No Cache is active, happens on multiple browsers again, different pc, etc. all the same issue. No Cloudflare cache active as it was accessed using the servers ip. 

The Picture is gone, yes, we switched storage servers and the software didnt like that.

I asked in the discord multiple times and never got any answer so far. Since this didnt work i switched to Pterodactyl anyways.

Thanks for your (very late) response tho ❤

**Comment by AEon-Jan** [comment]
Yeah sorry 4 that ... 

#Closed
