### ISSUE TITLE
[BUG]CS2 Server crashing after round 3

### ISSUE THREAD

**Issue by lukrei** [easy-wi/developer#1365]
I cannot play longer then 2-3 rounds on my newly created cs2 server.
I start the server via easywi web gui then CS2 Server shows as started but after around 80 seconds it shows offline.

Easywi version: 6.2.2 (newest development according to gui)
OS: Debian 12

EasyWi creates the screen session like this:
screen -A -m -d -L -S 10.222.111.101_27015 ./cs2 -dedicated -usercon +ip 10.222.111.101 +hostport 27015 +clientport 0 -maxplayers_override 12 +mapgroup +map de_dust2 +game_type 0 +game_mode 0

When I run this as user3-1 manually without easywi behind I can play fine on the server without crash.

I changed into the screen session easywi created then I see this:
`[STARTUP] {5.853} activated session on GC
13.390625 UNEXPECTED LONG FRAME DETECTED: 22.95ms elapsed, 0.06ms sim time, 1 ticks, 857..857.

Warning: failed to set thread priority: set failed for -10: 1:
Warning: failed to set thread priority: set failed for -10: 1:
23.843750 UNEXPECTED LONG FRAME DETECTED: 28.07ms elapsed, 0.06ms sim time, 1 ticks, 1526..1526.

55.734375 UNEXPECTED LONG FRAME DETECTED: 20.56ms elapsed, 0.05ms sim time, 1 ticks, 3567..3567.

80.109375 UNEXPECTED LONG FRAME DETECTED: 26.68ms elapsed, 0.04ms sim time, 1 ticks, 5127..5127.

85.125000 UNEXPECTED LONG FRAME DETECTED: 22.54ms elapsed, 0.05ms sim time, 1 ticks, 5448..5448.

93.156250 UNEXPECTED LONG FRAME DETECTED: 47.96ms elapsed, 0.06ms sim time, 1 ticks, 5962..5962.

113.609375 UNEXPECTED LONG FRAME DETECTED: 27.08ms elapsed, 0.08ms sim time, 1 ticks, 7271..7271.

118.687500 UNEXPECTED LONG FRAME DETECTED: 21.24ms elapsed, 0.05ms sim time, 1 ticks, 7596..7596.

127.234375 UNEXPECTED LONG FRAME DETECTED: 24.21ms elapsed, 0.06ms sim time, 1 ticks, 8143..8143.

149.203125 UNEXPECTED LONG FRAME DETECTED: 24.67ms elapsed, 0.06ms sim time, 1 ticks, 9549..9549.

149.218750 UNEXPECTED LONG FRAME DETECTED: 32.23ms elapsed, 0.07ms sim time, 1 ticks, 9550..9550.

157.328125 UNEXPECTED LONG FRAME DETECTED: 26.19ms elapsed, 0.04ms sim time, 1 ticks, 10069..10069.

186.953125 UNEXPECTED LONG FRAME DETECTED: 24.74ms elapsed, 0.05ms sim time, 1 ticks, 11965..11965.

186.984375 UNEXPECTED LONG FRAME DETECTED: 34.02ms elapsed, 0.11ms sim time, 2 ticks, 11966..11967.

196.968750 UNEXPECTED LONG FRAME DETECTED: 23.13ms elapsed, 0.08ms sim time, 1 ticks, 12606..12606.

Error: Cannot find master process to attach to!
`
I dont see any crash log or dumpfiles in /home/user3-1/.steam and /home/user3-1/Steam or /home/user3-1/server/cs2
If you know where I can find them i would be glad since i cannot attach any further infos to this bug.

I did not modify anything outside of easywi and also I did not add any mods or configs all I did was using the easywi defaults i just changed the steam account in gamemaster and cs2 template.

Expected behaviour: easy starts cs2 server and you can play full match.
Current behaviour: easy starts cs2 server and server crashing after you had played 2-3 rounds.

**Comment by AEon-Jan** [comment]
Taking a look into it

**Comment by AEon-Jan** [comment]
Problem fixed.

The servers are not "online," causing the auto-restart function to restart them every 80 seconds.
