### ISSUE TITLE
[CS:GO] [Userpanel] Gameserver Settings Mapgroup selection defective

### ISSUE THREAD

**Issue by myReaper** [easy-wi/developer#341]
If you choose Mapgroup (not workshop collection) for CS:GO and choose any item from the dropdown list, this item will not be visible after you have saved the settings and opened the settings menu again.

Most likely any script that should choose the saved menu item again after reopening the settings is running wrong and instead selecting it removing it from that list so always ar_baggage is selected as it is the first menu item.

In current GIT I installed a Gameserver only running CS:GO (no other games), went to settings and choose random_classic, saved and reopened the settings page -> after this, you could not even choose if you want to use Mapgroup or Workshop Collection as the dropdown menu just was gone (see screenshot).

![no_workshop_dropdown](https://f.cloud.github.com/assets/5735944/2240283/b0e1ab84-9c84-11e3-95a0-8ccbb836137f.png)

**Comment by LordRofl** [comment]
Warum closed? Das Problem besteht nochimmer.

**Comment by LordRofl** [comment]
Es wird im startparameter wie z.b +mapgroup mg_bomb_se das +mapgroup rausgefiltert sodass nur mg_bomb_se dort steht

**Comment by ulrichblock** [comment]
Warum Leichenfleddern? Das Ticket war gelöst und bleibt damit dicht. Wenn was erneut auftaucht, dann kann man ein neues Ticket machen.
