### ISSUE TITLE
dbmail support

### ISSUE THREAD

**Issue by ulrichblock** [easy-wi/developer#371]
After enhancing the fastDL modul to be a full web modul, mail support becomes interesting,

dbmail could be a way to go as it does not require system users and could be managed only with SQL. Check if PostgreSQL and MySQL, or both should be supported.

**Comment by FV-Chris** [comment]
Die Doku von debinux kann als vorlage für den Mail Support genutzt werden, die Doku bezieht sich auf Debian Wheezy funktioniert allerdings auch ohne Probleme auf Debian Jessie.
https://www.debinux.de/2013/10/mailserver-postfix-dovecot-ssl-und-sieve-mysql-spam-und-virenfilter-auf-debian-wheezy/
