### ISSUE TITLE
Autologin for external pages

### ISSUE THREAD

**Issue by ulrichblock** [easy-wi/developer#470]
Given a user is already logged in an authorued in some kind of booking system
And given he clicks on a login link to Easy-Wi
Than he should not be prompted for Login at Easy-Wi

Technical process should be:
-> User clicks link/button at external platform
-> Token is generated
-> Token is send via API to Easy-Wi together with externalID
-> Easy-Wi stores token in temp table (RAM?)
-> User is redirected to Easy-Wi and login.php together with token and externalID
--> login.php?autoLogin=1&token=generatedValue&user=base64(id)
--> Check if temp access exists and user can be found with matching data.
--> Will only work for users with accounttype "u"

Given, token is already invalid
Prompt user with normal loginform

**Comment by fsedarkalex** [comment]
I hope this will make it into ewi some time.

would love to see this in ombination to the WHMCS module.
