### ISSUE TITLE
Benutzer werden nicht mehr aufgelistet

### ISSUE THREAD

**Issue by speedlink1003** [easy-wi/developer#528]
Seid dem Update von Gestern wird kein Benutzer mehr unter dem Reiter Benutzer->Übersicht angezeigt.

**Comment by Bara20** [comment]
Sicher das gut alle überarbeiteten Dateien überschrieben hast? Kann das Problem bei mir nicht reproduzieren.

**Comment by speedlink1003** [comment]
Ich habe eig. alle Dateien welche vom dem Update betroffen waren geupdated, es könnte dennoch sein das mir evtl. ein Dummheitsfehler beim wieder einfügen von meinen eigenen PHP-Scripts unterlaufen ist. Ich werde mal mit der Fehlersuche auf meiner Seite beginnen.

Auf jeden Fall vielen Dank für den Hinweis, dass bei dir alles ohne Probleme läuft :).

**Comment by speedlink1003** [comment]
Ich habe nun das Webinterface mal komplett ohne custom-scripts neu aufgesetzt und bekomme nun immer noch keine User angezeigt :/. Ebenfalls scheinen auch andere Tabellen wie das Admin-Log, User-Log und diverse andere Auflistungen Probleme zu haben Daten auszugeben.

**Comment by FV-Chris** [comment]
Ich habe gerade meine Easy-WI Installation auf die neuste Github Version geupdatet und kann deinen Fehler nicht Reproduzieren.
Hast du schonmal die Datenbank reparieren lassen?

**Comment by dietzi** [comment]
Schalte mal dein Template in den Einstellungen auf adminlte um. Das hat bei mir geholfen. Musst dich halt an die neue Sortierung "gewöhnen". Master-Server stehen jetzt unter App-Server und so.
