### ISSUE TITLE
VHost Speicherplatz

### ISSUE THREAD

**Issue by alexzocker97** [easy-wi/developer#536]
Wenn man einen neun VHost/Webspace anlegt wird der Speicherplatz auf 1000MB festgelegt, auch wenn man 10MB eingibt. Will man nach dem erstellen dies ändern. Von 1000MB auf z.B. 10MB kommt die Meldung: Fehler: konnte die Tabelle nicht aktualisieren, oder es gab keine Neuerung!

**Comment by ulrichblock** [comment]
Angabe darf nur eine Zahl sein. Lass da "MB" weg und die Autokorrektur sollte nicht mehr passieren.
