### ISSUE TITLE
Gameserver neuinstallieren

### ISSUE THREAD

**Issue by alexzocker97** [easy-wi/developer#537]
Neuinstallation von Gameserver funktioniert nicht.
Es werden nicht die alten Dateien gelöscht und neue hinzugefügt (REINSTALL)

 Resynchronisation -> funktioniert auch nicht. Die gelöschten Dateien werden nicht hinzugefügt. 

Webserver gibt keine Fehlermeldung wie z.B. PHP oder ähnliches.

Log vom Root Server:
So 29. Mär 21:47:32 CEST 2015: Hard stop for user kd10001-50
So 29. Mär 21:47:32 CEST 2015: Server template server/gmod owned by user kd10001-50 deleted
So 29. Mär 21:47:32 CEST 2015: Server template /home/kd10001-50/server/89.163.185.181_27015/gmod/ owned by user kd10001-50 added/synced
So 29. Mär 21:48:02 CEST 2015: Server template /home/kd10001-50/server/89.163.185.181_27015/gmod/ owned by user kd10001-50 added/synced
So 29. Mär 21:48:02 CEST 2015: App 89.163.185.181_27015 owned by user kd10001-50 started

**Comment by FV-Chris** [comment]
Welche Easy-WI Version wird den verwendet?
Bei der Github Version, müssen unter umständen die sudores angepasst werden:

easy-wi-user ALL = NOPASSWD: /usr/sbin/useradd
easy-wi-user ALL = NOPASSWD: /usr/sbin/userdel
easy-wi-user ALL = NOPASSWD: /usr/sbin/deluser
easy-wi-user ALL = NOPASSWD: /usr/sbin/usermod
easy-wi-user ALL = NOPASSWD: /usr/sbin/setquota
easy-wi-user ALL = NOPASSWD: /usr/sbin/repquota
easy-wi-user ALL = (ALL, !root:easy-wi-user) NOPASSWD: /home/easy-wi-user/temp/*.sh

**Comment by alexzocker97** [comment]
Ich benutze die 5.0
Ich habe dies aber bereits drin.

**Comment by ulrichblock** [comment]
Kein Bug, deswegen geschlossen.

Fragen zur Einrichtung sind am besten im Forum aufgehoben.
