### ISSUE TITLE
MTA:SA Screenlog funktioniert nicht

### ISSUE THREAD

**Issue by Jusonex** [easy-wi/developer#539]
Die Logs von MTA:SA Servern funktionieren nicht richtig, weil MTA über ncurses einen 'spinner' in der oberen linken Ecke zeichnet, sodass im Screenlog die ganzen Formatierungszeichen enthalten sind.

Abhilfe schafft es MTA Server mit dem Parameter -n zu starten (getestet + funktioniert)

**Comment by ulrichblock** [comment]
Das Screenlog funktioniert an sich, nur ist die Ansicht nicht "Hübsch".

Das Default Template wurde angepasst, damit andere nicht in das Problem stolpern.
