### ISSUE TITLE
Include Project CARS

### ISSUE THREAD

**Issue by ulrichblock** [easy-wi/developer#547]
Steam Game:
{
	"appid": 332670,
	"name": "Project CARS - Dedicated Server"
},
{
	"appid": 234630,
	"name": "Project CARS"
}

http://www.pcars-forum.de/thema/1432-pcars-dedicated-server-installation-konfiguration-erkl%C3%A4rung/

**Comment by Lacrimosa99** [comment]
kleiner Template fehler.. die Datei "steamclient.so" welche sich im Hauptverzeichniss des Templates befindet, muss in denn Ordner "lib32" des Templates.
Ansonnsten wirft die Console einen Error aus: "dlopen failed trying to load: steamclient.so"

**Comment by FV-Chris** [comment]
Das Problem liegt nicht bei dem Easy-WI Template sondern bei Steam.
Steam stellt das Image so zum Download bereit und wird nicht von Easy-WI geändert.

**Comment by Lacrimosa99** [comment]
dann sorry für den Post =)
War davon ausgegangen, dass es das WI verwaltet ^^
