### ISSUE TITLE
Besseres Error Handling für Query

### ISSUE THREAD

**Issue by Bluscream** [easy-wi/developer#576]
Ich musste 4 1/2 Stunden Fehlersuchen und rumprobieren nachdem mir easy-wi beim erstellen einer TS-Instanz "Fehler: Querypasswort" angezeigt hatte, nur um zu merken das die IP in der query_blacklist war. Warum gibt Teamspeak denn die Error msgs zusammen mit den Error codes wieder wenn die nicht genutzt werden -.-

**Comment by ulrichblock** [comment]
- Debugger nicht genutzt
- Wiki nicht gelesen
- Allgemeine TS3 Hinweise nicht gelesen
