### ISSUE TITLE
easy-wi_install.sh Debian 8.1 quotacheck

### ISSUE THREAD

**Issue by FV-Chris** [easy-wi/developer#602]
Bei Debian Jessie 8.1 wird bei quotacheck folgende Meldung ausgegeben:

quotacheck: Ihr Kernel unterstützt wahrscheinlich Journalquotas, aber Sie verwenden sie nicht.  Vielleicht sollten Sie auf Journalquotas umsteigen, um nicht mehr quotacheck nach jedem unsauberen Herunterfahren ausführen zu müssen.

**Comment by Stinkesocke** [comment]
Diese Meldung ist bei Debian 6 schon aufgetreten, sie kommt immer wenn das JournalQouta Modul im Kernel aktiv ist. Wenn der Server unsauber heruntergefahren wird, muss man auch damit leben das die quotachecks dann laufen müssen. Journalquotas funktionieren nur auf einem Journaling Filesystem. Da Easy-Wi darauf keinen Einfluss hat, würde ich es bei Quotacheck belassen.

Gruss Stinkesocke
