### ISSUE TITLE
Easy-WI kann OVH Gameroots nicht erreichen

### ISSUE THREAD

**Issue by FV-Chris** [easy-wi/developer#604]
- Gameroots können nicht angelegt werden (SSH User Falsch, SSH IP Falsch, SSH Passwort Falsch)
- Es können keine Gameserver mehr angelegt werden (ohne ersichtliche Fehlermeldung im Easy-WI)
- Bestehende Gameserver können nicht gestartet werden (ohne ersichtliche Fehlermeldung im Easy-WI)
- Bestehende Gameserver werden nicht richtig gelöscht (ohne ersichtliche Fehlermeldung im Easy-WI)

Es muss die Originale sshd_conf wiederhergestellt werden.
Diese heißt "sshd_conf.orig" in /etc/ssh

Forenpost: https://easy-wi.com/forum/thread-7096.html

**Comment by ulrichblock** [comment]
Auch wenn es ein großer Hoster ist, sollten wir davon absehen so einen Spezialfall einzubauen.
FAQ und Forum muss es in diesem Fall richten.
