### ISSUE TITLE
Add multiple addons

### ISSUE THREAD

**Issue by dietzi** [easy-wi/developer#605]
Es wäre schön, wenn man gleichzeitig mehrere Addons hinzufügen könnte (im User-Backend). Ich stelle mir das so vor, dass neben jedem Addon eine Checkbox ist und ganz unten ein Button "Hinzufügen". Wenn man einen neuen Server anlegt und 10 Addons hinzufügen will, dann nervt das ganz schön.....

**Comment by Nollig** [comment]
Die Idee ist nicht schlecht, würde ja schon reichen wenn man, ohne dass die Seite neu läd, die Addons hinzufügen könnte. Die Checkboxen sind nicht mal notwendig.
