### ISSUE TITLE
Upgrade to latest GameQ v3 version

### ISSUE THREAD

**Issue by ulrichblock** [easy-wi/developer#606]
https://github.com/Austinb/GameQ/tree/v3

**Comment by ragnos** [comment]
Das Upgrade auf v3 bedeutet das alle Unreal Tournament Versionen nicht mehr "out of the box" funktionieren. [Issue bei GameQ](https://github.com/Austinb/GameQ/issues/272)

Ich kenne mich mit GameQ nicht gut genug aus um da einen Patch für zu schreiben (vom Zeitfaktor mal ganz abgesehen). Allerdings sehe ich das die grundlegenden Protokolle dafür wohl noch enthalten sind, das sollte also grundsätzlich möglich sein.
