### ISSUE TITLE
Unreal Tournament 3/4 starten nicht wenn die Binaries Symlinks sind.

### ISSUE THREAD

**Issue by ragnos** [easy-wi/developer#620]
UT3 und UT4 zeigen ein extrem zickiges Verhalten wenn es darum geht, von einem Symlink aus gestartet zu werden.

Lösung: Die Binaries der Spiele kopieren anstatt nur zu symlinken.
Die Lorbeeren für diese Entdeckung gehen an @FV-Chris #601 und @ulrichblock , der die Idee hatte das ganze bei UT3 anzuwenden.

Die Binaries, die kopiert werden müssten sind:
UT3: /Binaries/ut3
UT4: /Engine/Binaries/Linux/UE4Server-Linux-Test
**Achtung, bei UT4 kann sich der Binaryname jederzeit ändern!**

Eine allgemein gültige Lösung wäre eine Option, die ohnehin im Template definierte Binary zu kopieren anstatt zu symlinken. Dann braucht man den Code nicht für jedes neue UE4-Spiel nochmal anfassen. (Oder wenn Epic was an UT4 ändert).

**Comment by ulrichblock** [comment]
Allgemeine Lösung wir Binary Kopieren ja/nein wird implementiert.
