### ISSUE TITLE
Beschreibung für Game/Voice Server

### ISSUE THREAD

**Issue by ghost** [easy-wi/developer#637]
Ein nettes Features wäre noch die Möglichkeit Server zu beschreiben (ähnlich wie bei Appserver), was bei offline Server Sinn machen kann (da kein Hostname mehr vorhanden).

**Comment by ulrichblock** [comment]
Offline nur als prefix nutzen und den letzten erfassten Namen weiterhin anzeigen ist meiner Meinung nach die bessere und einfacher umsetzbarere Lösung.
