### ISSUE TITLE
GameQ v3 error

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#657]
Fehler im GameQ v3 Modul beim Auslesen des GS Status.

Meldung:

PHP Fatal error:  Uncaught exception 'GameQ\Exception\Server' with message 'Missing server info key 'type'!' in /var/www/webinterface-hp/third_party/gameq/GameQ/Server.php:112
Stack trace:
#0 /var/www/webinterface-hp/third_party/gameq/GameQ/GameQ.php(173): GameQ\Server->__construct(Array)
#1 /var/www/webinterface-hp/third_party/gameq/GameQ/GameQ.php(190): GameQ\GameQ->addServer(Array)
#2 /var/www/webinterface-hp/statuscheck.php(290): GameQ\GameQ->addServers(Array)
#3 {main}
  thrown in /var/www/webinterface-hp/third_party/gameq/GameQ/Server.php on line 112

**Comment by ulrichblock** [comment]
Kann so nicht bearbeitet werden:
- Die Fehlermeldung lässt keinen Schluss auf die Umstände schließen.
- Bei anderen und mir läuft es.
