### ISSUE TITLE
Universal Installer: Fehlerhafte Abfrage der Debian-Version

### ISSUE THREAD

**Issue by ragnos** [easy-wi/developer#658]
[Diese Bedingung](https://github.com/easy-wi/developer/blob/master/server/easy-wi_install.sh#L1129) funktioniert nicht, da das Paket "[lsb-release](https://packages.debian.org/jessie/lsb-release)" nicht zwangsläufig auf jedem Debian-Jessie-System installiert ist. Die Folge sind fehlende Pakete, die u.a. zum Betrieb von steamcmd erforderlich sind.

Ein Hotfix wäre vor der [Initialisierung von $DISTRIBUTORID und $OSVERSION](https://github.com/easy-wi/developer/blob/master/server/easy-wi_install.sh#L128) das Paket lsb-release zu installieren.

**Comment by Lacrimosa99** [comment]
Fix: https://github.com/easy-wi/developer/commit/d5a4dfd7ed6d35a6199192a7ff7d716528814a08

**Comment by Lacrimosa99** [comment]
Fix 2: https://github.com/Lacrimosa99/developer/commit/b20eb968a5eb924e6c4729f3e63493cc684cbf9a

**Comment by ulrichblock** [comment]
Scheint so, dass Debian ebenfalls etwas in den Paketnamen für 32bit Support umgestellt hat. Nach einem update && upgrade schlug der Installer auf dem Testsystem nun fehl. Deswegen werden die Installationsaufrufe nun je Paket gemacht um Support für altere Versionen und Ubuntu nicht zu gefährden.
