### ISSUE TITLE
Mumble als Voiceserver mit Masterfunktion

### ISSUE THREAD

**Issue by twiddern** [easy-wi/developer#66]
Es wäre toll, wenn Easy-Wi den Mumbleserver als Voiceserver verwalten könnte. Auch Mumble würde wie TeamSpeak nur einmal gestartet werden und über die ICE-Schnittstelle können verschiedene Instanzen gestartet werden.

> Am besten bestehende Formulare für TS3 Master und TS3 Virtual aufboren.

**Comment by Kandru** [comment]
Ich grabe zwar hier eine ältere Geschichte aus, allerdings möchte ich darauf hinweisen dass ich Mumble als wichtig empfinde und eine Unterstützung in dem Webinterface von Vorteil wäre. Wäre als Alternative zu TS3 immer noch super!

**Comment by robingroppe** [comment]
+1

**Comment by Pandry** [comment]
+1...
I'm waiting for mumble implementation soooo much :D

**Comment by PitbullOL** [comment]
Ich finde auch das hier mal die Priorität drauf gelegt werden sollte da Teamspeak mit ihren Lizensen es vielen schwer machen.

Hier könnte TR-Host mal ansetzen wenn er möchte er hat es ja in seinem Fork schon Integriert.

**Comment by robingroppe** [comment]
Hat ja auch weitere Vorteile. IPv6 und komplett freie Musikbots fallen mir gerade noch ein.

**Comment by ulrichblock** [comment]
Ich setze selber nicht auf Mumble. Aus diesem Grund kommt es als pull request, oder sicher nicht so schnell.

**Comment by twiddern** [comment]
Hi, ich sehe kein Commit. Kommt noch was oder ist das Feature ersatzlos gestrichen?

**Comment by Lacrimosa99** [comment]
Du darfst es gern bauen... leider ist unser Hauptentwickler nicht mehr Verfügbar (aus Zeitgründen) und das selbe ist bei mir auch.
Wenn es jemand macht, dann gern als Pull-Request einsenden und ich Pflege es bei Gelegenheit ein.

**Comment by twiddern** [comment]
Danke für die Info :) Ich hätte es lediglich zu Übersicht offen gelassen, so dass auch noch andere den Request sehen können und sich hoffentlich ein Entwickler mit viel Lust und Laune findet.

**Comment by Nexus633** [comment]
Besteht noch Interesse für den mumble Support? Ich würde dann mit der implementierung beginnen. Allerdings arbeite ich aktuell die issues von oben nach unten ab und somit kann es noch ein weilchen dauern aber ich mache es dann.
