### ISSUE TITLE
Games won't install Imageserver down?

### ISSUE THREAD

**Issue by TheOneWhoKnocks** [easy-wi/developer#663]
I'm not able to install games, the directories under /home/easy-wi/masterserver are created, but empty. Nothing else happens, even after waiting. I've also done the setup twice to exclude a error on my site. I've watched some tutorials on YouTube and a few other users are reporting this bug also.

I've used Debian 8 and the "full" tar.gz.

Edit:

I think the actual problem is, that the provided imageserver 84.200.78.232 seems to be down?

**Comment by ulrichblock** [comment]
Depends on the game you are trying to install. It was always the admins responsibility to upload his own masterfiles in case it was not a steamCMD supported game.

The imageserver should not have an effect. Besides we are working on setting a new one up.
