### ISSUE TITLE
easy-wi_install.sh probably too strict on Debian 8 checking only for .0 release

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#668]
Following is just a guess after the intaller tried to get ia32-libs on Debian 8 and had a quick look at the code!

Multiple occurrences. Example `printf "${OSVERSION}\n8.0`
Breaks on anything higher than 8.0. and then tries to resolve depencies for Debian < 8, like trying to get ia32-libs, wich is obviously false.
Current Debian release is 8.2.

**Comment by ulrichblock** [comment]
When testing with the latest version from Github I cannot reproduce. Given example becomes true:
```
[ "$OS" == "debian" -a "`printf "${OSVERSION}\n8.0" | sort -V | tail -n 1`" == "$OSVERSION" ]
```
