### ISSUE TITLE
Let's Encrypt Support

### ISSUE THREAD

**Issue by ulrichblock** [easy-wi/developer#672]

**Comment by Nollig** [comment]
Just use [Certbot](https://certbot.eff.org/). Working fine for me :D

**Comment by Lacrimosa99** [comment]
VHost Config mit Weiterleitung auf Port :443

`<VirtualHost *:80>
    ServerName %domain%
    Redirect 301 "/" "https://%domain%/"
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin %email%
    DocumentRoot "%vhostpath%/%user%/%htdocs%/%path%"
    ServerName %domain%
    ErrorLog "%vhostpath%/%user%/%logDir%/error_%domain%.log"
    CustomLog "%vhostpath%/%user%/%logDir%/access_%domain%.log" common
    DirectoryIndex index.php index.html
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/%domain%/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/%domain%/privkey.pem
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomain"
    <IfModule mpm_itk_module>
       AssignUserId %user% %group%
       MaxClientsVHost 50
       NiceValue 10
       php_admin_value open_basedir "%vhostpath%/%user%/%htdocs%/%path%:%vhostpath%/%user%/tmp"
       php_admin_value session.save_path "%vhostpath%/%user%/sessions"
       php_admin_value upload_tmp_dir "%vhostpath%/%user%/tmp"
       php_admin_flag allow_url_fopen Off
       php_admin_flag allow_url_include Off
       %phpConfiguration%
    </IfModule>
    <Directory %vhostpath%/%user%/%htdocs%/%path%>
        Options -Indexes +FollowSymLinks +Includes
        AllowOverride All
        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
    </Directory>
</VirtualHost>
`
