### ISSUE TITLE
class_app.php deletes backups on (re)start

### ISSUE THREAD

**Issue by ragnos** [easy-wi/developer#698]
Easy-Wi deletes any backup created either manual by user or via restart-planer. Responsible for this is [Line 1444 of class_app.php](https://github.com/easy-wi/developer/blob/95edb1eb6f04a39d34c336797a900689e292f037/web/stuff/methods/class_app.php#L1444)

Output of running that command manually without -delete:

```bash
ragnos-223@ragnos:~$ find /home/ragnos-223 -mindepth 2 -maxdepth 3 \( -type f -or -type l \) -not -name \"*.bz2\"
/home/ragnos-223/.oracle_jre_usage/9e360713136aba0a.timestamp
/home/ragnos-223/backup/144.76.70.86_25567-mc.tar.bz2
/home/ragnos-223/pserver/.profile
/home/ragnos-223/pserver/.bash_logout
/home/ragnos-223/pserver/.bashrc
```

This happens on all of our gameserver hosts, running both Debian 7 & 8, during every restart of a gameserver. We are running Easy-Wi 5.20

This is hardly intended behaviour.

**Comment by ulrichblock** [comment]
This is odd. First of all I cannot reproduce this output. Second mindepth should exclude this folder. A small change to test could be:
```bash
find /home/ragnos-223 -mindepth 2 -maxdepth 3 \( -type f -or -type l \) ! -name "*.bz2"
````

**Comment by ulrichblock** [comment]
My bad,

please see the commit.
