### ISSUE TITLE
Gameserver Template Masterserver helper

### ISSUE THREAD

**Issue by xm3n1** [easy-wi/developer#706]
It would be great if there is a Setup Guide or a Helper which helps you to set up or modify a Gameserver Template.

Like you install one CSGO Server and modify the Settings and you have a Button to Choose Set as Default CSGO Template or something like that, would be useful for Minecraft and other Games too and is simpler to handle.

**Comment by FV-Chris** [comment]
Please check the Wiki page for informations about the Gameserver Template.
https://easy-wi.com/wiki/de/admin/gameservertemplates
