### ISSUE TITLE
Respect RAM usage while picking best app root

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#711]
Leider kann ein Server noch mehr RAM zugewiesen bekommen, als er eigentlich besitzt.
http://i.imgur.com/BvHi7mP.png
In WHMCS sind beide Server angegeben.
Er sollte eigentlich in diesem Fall auf Server 1 die Daten packen.

**Comment by ulrichblock** [comment]
Wurde so bisher nicht implementiert.

**Comment by Qhiliqq** [comment]
Dann hab ich da was falsch verstanden mit der Resourrcenzuteilung.
Dachte das geht schon automatisch.

**Comment by ulrichblock** [comment]
Das geht bisher nur über Slots.

**Comment by Qhiliqq** [comment]
Alles klar.

Sinnvoll fände ich es.

**Comment by BlueFreakLP** [comment]
Ist ja recht schwach, dafür, dass das Modul knappe 119€ im Jahr kostet...

**Comment by Qhiliqq** [comment]
1. Ist das ganze ein OpenSource Projekt und zweitens ein Hobbyprojekt.
2. Ist das Modul nicht schwach, sondern noch nicht ganz ausgereift, was aber bei allem so ist.
3. Kostet das Modul nicht 119€ im Jahr sondern einmalig, nach dem Jahr kostet die "Update"Verlängerung etwas, wie es auch bei zig tausend anderen WHMCS Modulen so ist.

Also bevor du so anfängst solltest du dich evtl. in dem Thema besser einlesen ;) Danke

**Comment by ulrichblock** [comment]
Titel geändert, da es sich um ein zusätzliches Feature für die Open Source Software Easy-Wi handelt.

Das Limit wird von der API und dem UI umgesetzt.und nicht 3rd Party Modulen.
