### ISSUE TITLE
Nach aufhängen eines Servers kein Restart

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#720]
Wenn sich ein Server aufhängt und man diesen restartet bleibt der Screen weiterhin am laufen (Port ist belegt, obwohl der Server eigentlich aus ist) und wird nicht wie gewünscht gekillt.

**Comment by ulrichblock** [comment]
Bitte mehr Informationen. Bei CS:GO usw. ist dies kein Problem.

**Comment by ulrichblock** [comment]
Nach screen sharing session konnte das Problem nicht nachgestellt werden. Könnte ein Problem mit dem OVH Kernel Linux sein.

**Comment by Qhiliqq** [comment]
https://github.com/easy-wi/developer/issues/734
