### ISSUE TITLE
Scripts Sync failed

### ISSUE THREAD

**Issue by xm3n1** [easy-wi/developer#731]
Es scheint als das unregelmäßig aber gerade  bei Script Updates von CSGO die Mastergameserver sich nicht richtig die Files holen, erst wenn der Script Ordner bei csgo gelöscht wird und die Server Konsole diese nachlädt sind die CSGO Server wieder funktionsfähig.
Liegt hier ein Bug seitens Easy-Wi vor?

Der Fehler wurde mehrfach im Netz reported:

https://forums.alliedmods.net/showthread.php?p=2394053

**Comment by FV-Chris** [comment]
Also wenn du schon sagst, das der Fehler mehrfach im Netz reportet wurden ist, gehe ich mal schwer davon aus das Easy-WI nichts dafür kann.
Die SteamCMD wird zwar von Easy-WI verwendet aber wir können nichts für deren Fehler.

**Comment by Headwipe** [comment]
Dieser Fehler tritt nur im Easy-WI auf dadurch das die txt dateien im Script ordner nicht neu gesynct werden. Ich habe das selbe Problem.
