### ISSUE TITLE
TS3 Server Changes on Version 3.0.12.1

### ISSUE THREAD

**Issue by FV-Chris** [easy-wi/developer#732]
+ added "-mapping" to the serversnapshotdeploy command. This optional parameters will add a mapping of the old and new channelid's in the return

 ! Removed "virtualserver_max_upload_total_bandwidth" and "virtualserver_max_download_total_bandwidth" from the server template if the value was "-1"

**Comment by ulrichblock** [comment]
Irrelevant changes for us.
