### ISSUE TITLE
Quota GS

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/developer#733]
Implementierung des aktuell belegten Quotas, sowie des Rams in die GS Übersicht.

**Comment by ulrichblock** [comment]
Quotas is eine Sache. Ram wird schon schwieriger. Reden wir hier von belegten, reservierten, oder rechnerisch nach Angaben im Panel?

**Comment by Qhiliqq** [comment]
Ja nur Quota, das mit dem Ram ist mir später gekommen, dass das nicht so geht wie ich dachte.
Wenn einem Server 2GB Ram zugeschrieben sind, aus dem dann den aktuellen Verbrauch auslesen.
Das ist allerdings nicht nur schwierig, sondern irgendwie auch überflüssig.

Bei Quota sieht das anders aus, das finden meine Kunden und ich, dass man sehen sollte wieviel Speicherplatz belegt und frei ist. Evtl. in einer art loading bar.

**Comment by PitbullOL** [comment]
Bedenke je nach dem wie die Loading Bar aussehen soll geht es zum Nachteil des seitenaufbaus
