### ISSUE TITLE
Minecraft - class_app.php

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#734]
Change /stuff/methods/class_app.php in line 836 from:

`$script .= 'ps x | grep -v ' . $scriptName . ' | grep ' . $screenName . ' | grep java | grep -v grep | awk \'{print $1}\' | while read PID; do' . "\n";`

to

`$script .= 'ps x | grep -v ' . $scriptName . ' | grep Ssl | grep java | grep -v grep | awk \'{print $1}\' | while read PID; do' . "\n";`

Now MC servers are able to stop in case of hanging server.

**Comment by ulrichblock** [comment]
Duplicate of #720
