### ISSUE TITLE
WarSow Server fehler

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#766]
Nicht alle Datein des Masterservers werden auf den GS User übertragen.
Speziell die Dateien im Ordner basewsw, docs, libs werden nicht als Symlink angelegt.
Die Ordner selbst werden angelegt.
Beim Starten des Masterservers per Hand wird ein Ordner Namens ".warsow-2.0" im Hauptverzeichniss des Users angelegt.

Ergänzung:

im GS User Hauptverzeichniss wird ein Ordner Namens "home/" angelegt worin sich dann der Pfad der  "dedicated_autoexec.cfg" befindet.
Das ganze sieht dann so aus: /home/user2-2/home/user2-2/server/192.168.56.102_44400/warsow/basewsw/basewsw

**Comment by ulrichblock** [comment]
Klingt nach einer Fehlkonfiguration von WarSow selber.
