### ISSUE TITLE
Maximum execution time exceeded

### ISSUE THREAD

**Issue by falkse** [easy-wi/developer#767]
The panel worked fine the last days, now server start/stop is timing out and not working.
At the php-fpm error-log I can only find the following:
`[17-Mar-2016 23:14:39] WARNING: [pool www] child 1276 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /mnt/sdb/nginx/html/panel/third_party/phpseclib/Mclib/Math/BigInteger.php on line 3541"`
Webserver: NGINX
Panel Version: 5.21

**Comment by falkse** [comment]
Okay, es ist höchstwahrscheinlich die SSH Verbindung die nicht aufgebaut werden kann, da die Library "phpseclib" anscheinend nicht damit klar kommt. Ich habe mehrere SSH Verbindungen probiert (Ebenfalls mit dem Fork von TR-Host, der die SSH Verbindung extra testen kann), selbst die mit meinem privaten PC (Fedora Workstation 23) kann nicht aufgebaut werden. Wie auch immer, das ganze tritt seit gestern auf, nachdem ich den dazugehörigen Rootserver nach 3 Wochen mal wieder geupdatet hatte, und dort mitunter auch der OpenSSH Server aktualisiert wurde.
Im php-fpm Fehlerlog ist immer von der "BigInteger.php" die Rede, allerdings wechselt da auch die Zeilenangabe "line".
Verwendet wird die Linux Distribution Fedora Server (Version 23).

**Comment by ulrichblock** [comment]
Wahrscheinlich hat sich dann deine sshd_config geändert. Grundsätzlich liegt es ja nicht am Panel.

**Comment by falkse** [comment]
Ich habe das ganze Testweise in einer frisch aufgesetzten Virtuellen Maschine mit Fedora 23 probiert, und es ging dort ebenfalls nicht.
Diesmal jedoch mit Apache anstatt Nginx, sowohl die Verbindung zum eigentlichen RootServer als auch zu der Virtuellen Maschine selber wird nicht aufgebaut. Der SSH Zugang funktioniert natürlich.
Ich schaue mir meine sshd_config nochmal an, aber ich glaube kaum das es daran liegt, da es ja auf mehreren unabhängigen Testumgebungen nicht funktioniert.

Bilder:
https://cloud.terminal.run/index.php/s/yB4yWEppT2cJhJn
https://cloud.terminal.run/index.php/s/ZyYaYNJas9EYUyG

**Comment by falkse** [comment]
Nunja, ich habe das ganze auf eine Ubuntu VM ausgeweitet, und wie vermutet funktioniert es dort. Das Gamepanel läuft auf Apache und verbindet sich ohne Probleme mit dem Root Server.
Was mir dabei auffällt ist die Version von OpenSSH, Ubuntu/Debian nutzen 6.x (6.6.6) und RedHat basierte Distributionen 7.x (7.2), dabei wird wahrscheinlich das Problem liegen.

**Comment by falkse** [comment]
Zusätzlich habe ich nun geprüft, dass gar keine SSH Verbindung aufgebaut wird. Das PHP Script timed nach 30 Sekunden einfach nur aus, denn der der SSH Server auf dem Rootserver berichtet nicht von einem Verbindungsversuch.
Es könnte also vielleicht auch die Version des PHP Interpreter, Webserver oder etwas anderes eine Rolle spielen, jedenfalls bin ich mir sehr sicher das es nicht an der Konfiguration meinerseits liegt, warum das so ist habe ich in meinen vorherigen Posts ja schon belegt.

**Comment by Lacrimosa99** [comment]
Laut deiner Screens liegt an an der Uhrzeit des Servers und der PHP Einstellung (date.timezone).
Gruß

**Comment by falkse** [comment]
Die Einstellung ist auf dem Rootserver natürlich getan, und es funktionierte ja auch 1-2 Wochen.
In der Virtuellen Maschine hatte ich diese Einstellung nicht getätigt, deswegen die Warnung im Log, ich habe sie nun obligatorisch nachgeholt. Funktionieren tut das ganze immer noch nicht.

Bilder:
https://cloud.terminal.run/index.php/s/hHdQ9bpcWSGB0lj
https://cloud.terminal.run/index.php/s/0uFF0XPj85VHcPJ

Das Systemdatum sowie die Zeitzone sind natürlich korrekt.

**Comment by Lacrimosa99** [comment]
Wie Ulrich schon schrieb... wie sieht die sshd_config aus?

**Comment by falkse** [comment]
Nun wie gesagt, wenn das Gamepanel auf einem Debian basiertem System (z.B. Ubuntu) läuft, und auf einen Masterserver der auf Fedora läuft per SSH zugreifen soll, dann funktioniert das wunderbar.
Nur wenn das Gamepanel auf Fedora läuft, und auf den Masterserver der ebenfalls auf Fedora läuft zugreifen soll, dann funktioniert das ganze nicht.
Der Masterserver ist in beiden Fällen der gleiche.

https://cloud.terminal.run/index.php/s/35xTAbmfM4hrbE0

**Comment by Lacrimosa99** [comment]
Port 300 (SSH Port) wurde dem WI mitgeteilt?
Auch mal geschaut ob ein anderer Dienst dieses Port beansprucht?
Wie verbindet das WI mit dem Remote Server? (per Keyfile oder PW)

**Comment by falkse** [comment]
Port 300 wurde mitgeteilt, ebenfalls ist der Port nicht belegt, sondern steht allein dem SSH Dienst zu. Mehrmals versucht, geprüft usw. Wie gesagt funktioniert die Verbindung von einem Ubuntu System aus, von einem Fedora System wiederrum nicht, wohlgemerkt auf den selben Masterserver.
Ich vermute, es liegt an der neuen Version (7.2) des OpenSSH Paket's auf Fedora, im Gegensatz dazu 6.6.6 auf Ubuntu.

**Comment by ulrichblock** [comment]
Programmiert und getestet wird auf Ubuntu und Debian. Deswegen werden auch nur diese als unterstützte Systeme genannt. Wenn man nun eine andere Distro benutzt, und diese dann nicht funktioniert, ist man leider auf sich selber gestellt, was die Problemlösung betrifft.

Anscheinend gibt es Probleme mit den Komponenten OpenSSH und phpseclib. Letztere kommt unmodifiziert zum Einsatz und ist die Grundlage für die SSH2 und SFTP Verbindungen. Ich habe nun das schon länger vorgenomme Update auf 2.0.1 der Library vorgenommen. Ticket dazu ist #768

Wenn es nun immer noch nicht geht, kann man nur sagen, nichts benutzen, was nicht offiziell supported und getestet wird, wenn man die etwaigen Probleme nicht selber lösen kann.

**Comment by falkse** [comment]
Wunderbar! Es funktioniert nun!
Vielen Dank!!
Gruß

**Comment by ulrichblock** [comment]
Dann kann man abschließend sagen, dass es eine Inkompatibilität zwischen 3rd Party Komponenten auf einem nicht unterstützen System war.
