### ISSUE TITLE
Möglichkeit einer "Display IP"

### ISSUE THREAD

**Issue by falkse** [easy-wi/developer#770]
Kleiner Vorschlag für eine Funktion:

_Ausgangspunkt:_ Mein Homeserver besitzt eine dynamische IP, darüber hinaus besitze ich eine Domain, die den Server per DynDNS erreichbar macht. Im Gamepanel kann man für den SSH Zugang bedenkenlos "127.0.0.1" nutzen, es funktioniert auch alles wunderbar.

_Problem:_ Einzig von der Benutzerführung für die User ist es verwirrend wenn "127.0.0.1" als Server und FTP IP dasteht, oder im Falle eines aktivierten DMZ die veraltete öffentliche IP dasteht.

Schön wäre da die Option einer Display IP, wo man seine Domain eintragen kann, sodass der User diese in der Server, FTP usw. Übersicht angezeigt bekommt, sowie das im FTP der Ordner dann nicht mehr `<IP>_<Port> `sondern` <Domain>_<Port> `heißt.

Gruß

**Comment by ulrichblock** [comment]
Dieses doch recht exotische Scenario wird nicht unterstützt werden. Statt dessen schreibe dir lieber Update Scripte, die die entsprechenden Felder korrigieren, wenn dein DynDNS aktualisiert wird.

**Comment by falkse** [comment]
Ein Update-Script, welches die IP-Adresse nach Änderung in der Datenbank aktualisiert, würde die Konsistenz der Adresse eines Servers nicht auf Dauer ermöglichen. Wird dem Kunden heute eine IP angezeigt und morgen hat diese sich geändert, kann er sich nicht mehr mit der alten IP verbinden. Wird dem Kunden allerdings der Domainname angezeigt, welcher dynamisch auf den Hostserver verweist, wären diese Probleme gelöst. Abgesehen davon das sich der Name des Ordners im FTP ebenfalls wärend des laufenden Servers ändern würde.

**Comment by ulrichblock** [comment]
Kunden auf einem DynDNS? Wie bereits geschrieben, ist dies kein unterstütztes Scenario. Entweder man hat ein Intranet und bleibt in diesem, oder aber Internet mit fixen IPs. Alles anderes wirst du dir selber basteln müssen.
