### ISSUE TITLE
lib32gcc1 missing on debian wheezy installation

### ISSUE THREAD

**Issue by Toothwitch** [easy-wi/developer#780]
Adding any Streamapps didn't work because the steamcmd relies on lib32gcc1 on debian based systems. And because i had to install it manually i assume it isn't installed by the Easy-Wi installer. Please add this as a feature to the installer. Thanks

**Comment by gOOvER** [comment]
Wheezy is OldStable......... I Think everyone can easyly upgrade to Jessie ;)

**Comment by Toothwitch** [comment]
So Jessie doesn't rely on the library? If thats so i'll close this issue. But i'll stay at wheezy because jessie is too different.
