### ISSUE TITLE
Core Anzeige

### ISSUE THREAD

**Issue by Bara** [easy-wi/developer#782]
Aktuell sieht man es nur in der Liste beim Server bearbeiten, finde es aber Interessant und Hilfreich(er) das diese Information pro Server noch einmal in der Liste aufgelistet ist (sodass man sieht welcher Server zu welchen Kern gebunden ist).

**Comment by Nollig** [comment]
Das steht bei dem Benutzer im Webinterface drin. Aber ja fände ich auch nicht schlecht, das nochmal als Admin direkt in der Übersicht zu sehen. Vielleicht auch direkt im Dashboard so eine kleine Übersicht der CPU-Auslast.
