### ISSUE TITLE
Error - Skin/Template ändern

### ISSUE THREAD

**Issue by Bara20** [easy-wi/developer#785]
Egal welchen Skin/Template ich nehme es kommt immer dieser Error:

> Error: Updating the database failed, or no new data had been entered!

Version ist die aktuelle 5.22.

**Comment by TR-Host** [comment]
Wurde 5.22 neu installiert oder wurde das Easy-Wi von 5.21 auf 5.22 upgedatet?
Hintergrund: Bei der aktuellen Version (5.22) konnte ich den Fehler nicht nachvollziehen.

**Comment by Bara20** [comment]
Es handelt sich um eine ältere Installation (~1 Jahr).

**Comment by Bara20** [comment]
Nach einer frischen Installation zwar behoben, aber lasse diese Issue trotzdem mal auf.

**Comment by ulrichblock** [comment]
Es fehlte dir sehr wahrscheinlich das DB Feld zu der Änderung. An Stelle von einer Reinstall hätte man auch DB Repair machen können.
