### ISSUE TITLE
CS:GO ESL Mappack

### ISSUE THREAD

**Issue by sixteeN11** [easy-wi/developer#794]
Hallo, für CS:S und Co gibt es ein ESL Mappack aber für CS:GO nicht, besteht da die Möglichkeit das mit einzubinden? Danke euch!

**Comment by ragnos** [comment]
Abgesehen davon dass sich der ESL Mappool ändert wie Unterhosen, da gibt es eine Steam Workshop Collection zu: http://steamcommunity.com/sharedfiles/filedetails/?id=211090892

**Comment by Pandry** [comment]
You can do it yourself...
Just add a map pack extension and load the configs, uploading the maps
