### ISSUE TITLE
Mysql Datenbanken - Userlogin

### ISSUE THREAD

**Issue by LordRofl** [easy-wi/developer#798]
Ein automatischer login in die Datenbank, wenn man im Userpanel auf den Button phpmyadmin unter der entsprechenden Datenbank klickt, wäre sehr hilfreich.

**Comment by TR-Host** [comment]
Dazu müssten wir das MySQL Passwort eines Users in die DB schreiben. Da dies eine zu große Sicherheitslücke darstellt, wird es vorerst nicht implementiert. Der User selber sollte sich das Passwort merken können.
