### ISSUE TITLE
Addon Binary kopieren Option im WI

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#800]
Funktion "Addon Binary kopieren" wie bei den Gameserver Files hinzufügen, da Rust die Binary benötigt und nicht die Symlinks (der Compiler wird im Symlink Mode nicht ausgeführt trotz Vollzugriff im Addon Master).
Die Ausführrechte des Compilers im User Ordner werden zurückgesetzt auf 700.. Problem hierbei ist, das er Vollzugriff braucht um compilieren zu können (weitere System Libraries werden dazu benötigt).
Weitere Games noch am testen.

**Comment by ulrichblock** [comment]
Alle Beispiele betrafen Mods. Diese werden eben nicht über Addons bereit gestellt. Grundkurs in Englisch:
Add = Hinzufügen
Mod = Verändern

Ergo ist dieses Ticket irrelevant.

Wenn ihr Mods betreiben wollt, dann richtet bitte entsprechende GS Templates ein.
