### ISSUE TITLE
Fastdownload: Vorhandene Dateien ignorieren

### ISSUE THREAD

**Issue by LordRofl** [easy-wi/developer#801]
Wenn man einen Abgleich startet, läd easy-wi immer alles wieder hoch, egal ob es auf dem FastDL Server schon vorhanden ist.

**Comment by Lacrimosa99** [comment]
Das ist weder ein Fehler noch ein Bug.
Das ist gewollt und auch richtig so.
Ist zwar langwieriger aber eben das sicherste um alle Daten synchron zu haben.

**Comment by TR-Host** [comment]
Es wurde alles gesagt ;)

**Comment by LordRofl** [comment]
Ich habs mir fast gedacht^^ Ja gut, dann soll es wohl so sein.

**Comment by sosi-deadeye** [comment]
Der Gameserver und der Fastdownload müsste eine Datei vorhalten, in der alle Dateien gelistet sind. Diese Liste würde dann die Pfade, Größen und Timestamps enthalten. Beim Synchronisieren müsste der Server vom Fastdownload die Datei laden und einen Diff zur Dateiliste des Gameservers machen. Die Unterschiede sind dann die betroffenen Dateien, die neu hochgeladen werden müssen. Fehlende Dateien müssen natürlich auch hochgeladen werden. Viel Spaß.

**Comment by TR-Host** [comment]
@sosi-deadeye Bitte programmieren und ein pull-request senden. Viel Spaß ;)
