### ISSUE TITLE
Fix Valve servers

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#806]
The valve servers have some problems:
When the panel makes the link, it doesn't make the steamclient.so link, so I've found how to fix... (And I'm actually trying to make it in the panel)

```
mkdir /home/<userdir>/.steam/
mkdir /home/<userdir>/.steam/sdk32/
ln -s /home/<easywi-masteruser>/masterserver/steamCMD/linux32/steamclient.so /home/<userdir>/.steam/sdk32/steamclient.so
chmod -R 777 /home/<userdir>/.steam/
```

**Comment by ulrichblock** [comment]
I guess chmod 777 is way to much and also probably a security problem. Can you please check if 700 is sufficient?

Which files are placed in the folder by the lib itself?

**Comment by Pandry** [comment]
Maybe the 777 is too much, a 755 should be fine.
(anyway, talking about security, it's just a dlopen)

**Comment by Pandry** [comment]
Just checked...
With chmod 700 it gives:
/home/<userdir>/.steam/sdk32/steamclient.so: cannot open shared object file: Permission denied
But, once i try to do ls to list again the file, the sdk32 folder is empty...
I've tryed to copy it too... It get deleted anyway...

**Comment by ulrichblock** [comment]
I tried it myself. The server seeks the file in the home of the master server. Meaning following with the master account was sufficient:
```
mkdir -p ~/.steam/sdk32/
chmod 750 -R ~/.steam/
ln -s ~/masterserver/steamCMD/linux32/steamclient.so ~/.steam/sdk32/
```

**Comment by Pandry** [comment]
Hooh, thx for the fix <3

**Comment by ragnos** [comment]
Not fixed.

steamclient.so needs to be placed inside $USERs .steam/sdk32, not the one of $MASTERUSER.

So you need to place a symlink in $USERHOME/.steam/sdk32, but there it will be deleted at server restart.

[Forum Thread](https://easy-wi.com/forum/thread-7519-post-13831.html#pid13831)
