### ISSUE TITLE
Konsolen API

### ISSUE THREAD

**Issue by RicoswLive** [easy-wi/developer#807]
Könnt ihr bitte einbauen das man per API befehle in die Konsole schicken kann

**Comment by ulrichblock** [comment]
Das ist ein komplett asyncroner Prozess, bei dem die API keinerlei sinnreiche Rückgabe machen kann. Aus diesem Grund alleine macht es schon wenig Sinn.

Dann wäre da noch der Grund, dass ich keinen einzigen Usecase für dieses Feature sehe, jedoch ganz viele Risiken.
