### ISSUE TITLE
[enhancement] Server Monitoring

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#808]
It would be cool to have some information about the servers load and some other info (Like HDD usage, Net usage, CPU load and/or load average and the uptime) and this for the master servers too...
I know it's difficult, but it would be sooo cool :D.

**Comment by ulrichblock** [comment]
If you need a detailed monitoring, please use a specialized tool like Zabbix.

**Comment by Pandry** [comment]
Yeah, but It would be a nice thing for the users...
