### ISSUE TITLE
Fastdownload: Uploadgröße

### ISSUE THREAD

**Issue by LordRofl** [easy-wi/developer#810]
.bsp Dateien(Map für CSS/CSGO) die ungepackt größer als 150mb sind, dürfen nicht als .bz2 auf den FastDL gepackt werden. Gut wäre da ein Check, der sie dann unkomprimiert hochläd.

**Comment by MadMakz** [comment]
Ich schieß mal ins Blaue und sage das ist AFAIK ein Client~~problem~~ -feature https://forums.alliedmods.net/showpost.php?p=2132290&postcount=42

**Comment by Lacrimosa99** [comment]
für CS:GO zutreffend... CS:S kann größere Maps downloaden ;)
Würde es daher als "Handling Errors, won´t/can´t change/fix" deklarieren^^

**Comment by LordRofl** [comment]
Das Problem ist, das die fehlerhafte Datei im maps Ordner verbleibt und der Client nie wieder auf einen Server kommt wo die Map gerade läuft. Ich verlasse mich da ungern auf meine Mitstreiter die CSGO Server hosten und Easy-Wi nutzen, das sie es nicht verchecken diese Maps zu löschen und unkomprimiert anzubieten. Ist es da nicht genauso wie mit der Argumentation beim Upload aller Files auch wenn sie schon vorhanden sind. Hier werden auch einbußen im Komfort in Kauf genommen für die Sicherheit, alle Daten auch wirklich gleich zu haben. Die Einbuße wäre sogar relativ gering im Vergleich.
