### ISSUE TITLE
Skip creating backup if user is impatient

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#817]
Hi,

ich hab ein Fehler im Backup Modul, welcher sich wie folgt äußert:

- Einzel Server Backup (1 GS Backup) -> ok. Upload funktioniert problemlos.
- Multi Server Backup (mehrere GS Backups) -> Upload Schleife (Backup wird immer wieder neu hochgeladen und hat kein ende)
   - Shell Scripte im /home/webinterface/temp Ordners des GR WI´s wird teilweise nicht gelöscht (Ordner (770) sowie Dateirechte (750) sind ok)

Das einfachste wäre wenn ein check eingebaut wird welcher prüft, ob schon ein Prozess mit der IP und dem Port läuft, um doppelte Prozesse auszuschließen.

**Comment by ulrichblock** [comment]
Was meinst du mit "Multi Server Backup". Dies gibt es nirgends als Definition.
Ich habe gerade 3 Gameswitch auf einen Server gepackt und dann das Backup gestartet. Lief ohne Probleme durch.

**Comment by Lacrimosa99** [comment]
Sorry... hab das Thema ganz aus den Augen verloren..
Was ich mit "Multi Server Backup" meine ist, das wenn mehrere Instanzen parallel laufen, diese kein ende finden und der Upload immer wieder neu beginnt.
Hatte erst einen Festplatten defekt in Verdacht da uns eine Festplatte ausgestiegen ist... diese ist nun ersetzt aber das Problem mit dem Upload besteht weiterhin.
Der Prozess zum Backup erstellen und Upload läuft wie in einer Schleife.
