### ISSUE TITLE
Move Gameservers

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#827]
Maybe adding to move GS from one host to another (in admin panel)

**Comment by Pandry** [comment]
What do you mean?
Move Gameservers from one master server to another one?

**Comment by Qhiliqq** [comment]
Jep exactly.

Without the moving services.

I make this while copying all files per rsync to the other root, but this could be done smoother and simple with a included script

**Comment by Pandry** [comment]
Well...
It's a bit difficult...
A user could have some data in his server like maps or something else...
The panel should start a script that copy all the files in another server, creating the same user...
It's difficult..
It would be better (or at least I think) to make a new game server on another server and, after that, copy all the user data in the new server...

**Comment by ulrichblock** [comment]
Duplicate of #4
