### ISSUE TITLE
[enhancement] Keep signed-in checkbox

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#828]
What about put 2 checkbox in the login page referred to stay connected?
For example "Stay connected" or "Keep me signed-in" and "Keep the access in case of IP changed", (to save the access and keep signed-in a person if he have a different IP from the last time he did the access)

**Comment by ulrichblock** [comment]
Could lead to a huge security problem. Maybe an increased session life time on your server is what you actually need.
