### ISSUE TITLE
Easy-WI API FTP

### ISSUE THREAD

**Issue by RicoswLive** [easy-wi/developer#833]
Wenn man das FTP-Passwort per API ändert wird das im Frontend geupdated aber man kann nicht auf den FTP-Server mit dem neuem Passwort es wird scheinbar nicht geändert.

**Comment by Pandry** [comment]
Have you tryed to change it again?

**Comment by RicoswLive** [comment]
@Pandry Yes I have change it multiple times but it not working

**Comment by Pandry** [comment]
I've had the same issue the past week...
I've discovered that you HAVE to make a custom username (ex. customer_<customer_id>), or debian (In my case) will NOT create the user (maybe for a security problem it disallow numeric users only)

**Comment by RicoswLive** [comment]
I can create the user but if I change the initialpassword it will change it in frontend but in the Backend nothing happends

**Comment by Pandry** [comment]
That's weird...
It never happend to me...
I've tried on my VM but I can't reproduce the error :(
