### ISSUE TITLE
Restart Planer vereinfachen

### ISSUE THREAD

**Issue by Bara20** [easy-wi/developer#842]
Aktuell ist der Restart-Planer etwas sehr lastig. Man muss jeden Tag separat hinzufügen (was bei 6+ Servern sehr Zeitaufwendig werden kann). Gibt es eine Option bzw. Möglichkeit alle 7 Tage eine Option hinzufügen (mit einmal und nicht jede einzeln)?

**Comment by ulrichblock** [comment]
Zu viel Aufwand für zu wenig nutzen. Falls es fertig als Pull Request kommt, könnte man es einbinden.
