### ISSUE TITLE
Upgrade didn't upgraded the version in the DB

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#846]
In the DB, in the table `easywi_version`, is missing the version 5.30, so the panel continue to warn about the version 5.30, and it still continue to say that the current version is the 5.21, though the `version` field in the `settings` table is setted to 5.30

**Comment by ulrichblock** [comment]
Cannot reproduce this problem

**Comment by Pandry** [comment]
Okay, maybe that was just bad luck (And anyway I fixed it :D)
