### ISSUE TITLE
[enhancement] A normal user can edit a startcommand throught a textbox

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#848]
Watch the title xD

**Comment by ulrichblock** [comment]
This does not help at all. You need to provide specifics.

**Comment by Pandry** [comment]
I'm using the panel with a community...
One user asked me to give him an ArmA3 server, so I gave it to him, but now he would like to add some mods, but, to add them he sould edit the start command, so it would be cool to add some parameters from the panel, usgin it as user

**Comment by ulrichblock** [comment]
Freetext on the startcommand is a huge security risk. It is better that you configure addons and or mods.

If it ist just some commands check out the CS:GO Template.
If it is additional files + more parameters, solve it, by adding an additional start command at the addon.
