### ISSUE TITLE
Passwörter per Button ändern

### ISSUE THREAD

**Issue by Bara20** [easy-wi/developer#858]
Mir fehlt ein Button wo man bestimmt Passwörter für FTP's, etc. neu setzen kann (z.B. neben der Zeile Rechts) via. Webinterface. Man kann sich zwars ein setzen, aber ein Button wäre ebenso praktisch und "sicherer".

**Comment by ulrichblock** [comment]
Sicherer mit nichten. Ist doch schon in den Einstellungen möglich.
