### ISSUE TITLE
[5.30] - admin.php?w=se - Undefined index: favicon / Undefined index: login_header_text + Einstellungen nicht speicherbar

### ISSUE THREAD

**Issue by MadMakz** [easy-wi/developer#860]
Nach update auf 5.30 gibt es unter "Einstellungen"

`Undefined index: favicon in stuff/admin/panel_settings.php Zeile 179 (referer: /admin.php?w=sc)`
`Undefined index: login_header_text in stuff/admin/panel_settings.php Zeile 208 (referer: /admin.php?w=se&r=se)`

Sowie lassen sich Einstellungen dort nicht mehr speichern:
> Fehler: konnte die Tabelle nicht aktualisieren, oder es gab keine Neuerung!

Desweiteren wurde das Theme auf default zurückgesetzt soweit ich das sehe.

![ewi530](https://cloud.githubusercontent.com/assets/3930214/15391797/971fde10-1dc3-11e6-86fd-cb3da8cacc60.png)

**Comment by TR-Host** [comment]
Bitte mehr Details nennen! Wie z.b. Welches Betriebssystem, Welche Version hattest du vorher? Wie hast du das Update gestartet? usw. ;)

**Comment by MadMakz** [comment]
Dateien ersetzt, install/update.php ausgeführt.

Debian Jessie, PHP 5.6.21 (FPM), Apache 2.4.10

Alt EWI dürfe 5.21 gewesen sein. Müsste ich im Backup nachschauen wenn es wichtig ist.

**Comment by TR-Host** [comment]
Bitte die repair Funktion mal manuell benutzen ;) evtl. werden dann fehlende Tabellen hinzugefügt.

**Comment by MadMakz** [comment]
Fixed.

Dann stimmt aber etwas mit dem Updatescript nicht. Es wurde definitiv mitgeteilt das Änderungen an der DB ausgeführt wurden.

5.21 -> 5.22
5.22 -> 5.30
