### ISSUE TITLE
Allow special char to folder path field in the addons section

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#862]
I'va a folder called "@Ryanzombies", but I can't inserit in the folder path filed...
When I try to click the save button I got the same message as I haven't changed any file (so the folder path field stay empty)...
Can someone find how to fix it?
P.S. (I should add some semicolums too )

**Comment by Pandry** [comment]
(I've already tried to put a backslash (\) before the at)

**Comment by ulrichblock** [comment]
Such a foldername is bad practise. Please explain, why this should be allowed and why you cannot use a good practise name.

**Comment by Pandry** [comment]
Because the arma mods needs some folders in the path which name starts with the at
