### ISSUE TITLE
"ini" wird abgeschnitten, wenn über x Zeilen

### ISSUE THREAD

**Issue by Donzii** [easy-wi/developer#863]
GameTemplate
Wenn in "Cvars, die unveränderbar sein sollen" ein Eintrag steht, wie z.B.:

```
[LinuxServer/UnrealTournament/Saved/Config/LinuxServer/Rules.ini] ini
MaxPlayers=5
```

wird die Originaldatei (Rules.ini mit 676 Zeilen) abgeschnitten. Mal oben, mal mittig, mal unten, beliebig gekürzt.
Wird der obrige Eintrag entfernt, bleibt die Datei bestehen.

Original-Datei: http://my.despe.de/np/index.php?id=2a26af1fe9
Die abgeschnittene Datei: http://my.despe.de/np/index.php?id=d1d96c9344

Ebenso ist mir aufgefallen, dass das Editieren (full) über easy-wi bei dieser Dateigrösse/Zeilenanzahl zwischen jeder Zeile eine Leerzeile hinzufügt

**Comment by Pandry** [comment]
If u can translate in English I would try to help you :) (Already tried with Google Translate, it sucks)

**Comment by ulrichblock** [comment]
Könntest du bitte ein zwei komplette Config Beispiele per Mail schicken?

**Comment by ulrichblock** [comment]
Dass es mit der Länge zusammenhängt, war ja offensichtlich. Ich konnte zwei Fehler lösen:
- Beim Schreiben die new lines
- Beim Lesen das Abschneiden
