### ISSUE TITLE
Unlimited Slots for Gameserver

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#865]
Is there a way to disable maximum players?
Because in minecraft the maximum players are a litte bit useless :)

**Comment by Pandry** [comment]
You can edit the startcommand (if it countainsthe max players, I didn't checked)...
If it don't countains the max players ,there shouldn't be any limit to the players

**Comment by Qhiliqq** [comment]
I have this already, but on the dashboard of the webinterface the slots written there ;)

**Comment by Pandry** [comment]
Hooh..Well...
Just ignore it...
I'll try to do it when I'll have time (:

**Comment by ulrichblock** [comment]
There are many dependencies. Just set a very huge number.
