### ISSUE TITLE
SSH2 Keys bei Webspace Master

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#869]
Nutzt man Keys bei einem Webspace Master, so lassen sich keine VHosts erstellen.
In der Datenbank werden diese zwar angegeben, jedoch nicht auf dem Server erstellt.

Errorlogs gibt es dazu leider keine.

**Comment by Lacrimosa99** [comment]
Leider nicht nachvollziehbar.
Wir nutzen auf verschiedenen Systemen mit verschiedenen Betr.systemen das Webhosting Modul und bisher keine probleme damit bekommen.
Wird im Key ein PW verwendet?

**Comment by Qhiliqq** [comment]
Ja im Key wird selbstverständlich ein PW verwendet.

**Comment by Lacrimosa99** [comment]
Dann mal ohne PW versuchen... vill. liegt es daran.
Wir selbst nutzen Key´s allerdings ohne PW da dort die Übergabe des PW´s nicht richtig funktioniert^^

**Comment by Qhiliqq** [comment]
Daran kann es liegen, habe ich noch nicht anders getestet.

**Comment by ulrichblock** [comment]
Getestet und funktioniert bei mir. Der Dialog:
```
Found group www-data with group ID 33. Use as webservergroup?
1) Yes
2) No
3) Quit
#? 1
Please enter the name of the masteruser. If it does not exists, the installer will create it.
webmaster

Create key or set password for login?
Safest way of login is a password protected key.
1) Create key
2) Set password
3) Skip
4) Quit
#? 1

It is recommended but not required to set a password
Generating public/private rsa key pair.
Enter file in which to save the key (/home/webmaster/.ssh/id_rsa): /home/webmaster/.ssh/web_rsa
Created directory '/home/webmaster/.ssh'.
Enter passphrase (empty for no passphrase): **********
Enter same passphrase again: **********
Your identification has been saved in /home/webmaster/.ssh/web_rsa.
Your public key has been saved in /home/webmaster/.ssh/web_rsa.pub.
The key fingerprint is:
a3:b9:31:2c:f9:4d:15:46:df:3f:ab:d0:10:a3:f3:8f webmaster@Test
The key's randomart image is:
+---[RSA 2048]----+
|          .      |
|         . . .   |
|          oo. .  |
|         ...o  . |
|        So..   ..|
|     o o oo o   o|
|    o * .  o . . |
|     o *    + .  |
|      o .  E o   |
+-----------------+
```

Dann noch die web_rsa und web_rsa.pub hochgeladen und angegeben.
