### ISSUE TITLE
Webspace Quota

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#870]
WS Quota wird nicht richtig geprüft.

Belegung im WI liegt immer bei 0MB.

Die statuscheck.php spuckt folgendes aus:
`Checking webMaster xxx.xxx.xxx.xxx with webMasterID 3
Cannot find or no update for webhost with FTP user web-9, webVhostID 9 which has a usage of 0 MB
Cannot find or no update for webhost with FTP user web-10, webVhostID 10 which has a usage of 0 MB
Cannot find or no update for webhost with FTP user web-11, webVhostID 11 which has a usage of 0 MB
Found and updated webhost with FTP user web-9, webVhostID 9 and a usage of 7 MB
Found and updated webhost with FTP user web-10, webVhostID 10 and a usage of 602 MB
Found and updated webhost with FTP user web-11, webVhostID 11 and a usage of 7 MB
Found and updated webhost with FTP user web-9, webVhostID 9 and a usage of 0 MB
Found and updated webhost with FTP user web-10, webVhostID 10 and a usage of 0 MB
Found and updated webhost with FTP user web-11, webVhostID 11 and a usage of 0 MB
Cannot find or no update for webhost with FTP user web-9, webVhostID 9 which has a usage of 0 MB
Cannot find or no update for webhost with FTP user web-10, webVhostID 10 which has a usage of 0 MB
Cannot find or no update for webhost with FTP user web-11, webVhostID 11 which has a usage of 0 MB
`

**Comment by ulrichblock** [comment]
Kann viele Ursachen haben. Wird journaled, oder normales quota verwendet? Kann man folgendes ausführen ohen passwort als web master ausführen:
```
REPQUOTA=`which repquota`
sudo $REPQUOTA /path/to/mountpoint
```

Mach auch mal den Debugger an. Der gibt dir das tatsächlich ausgeführte shell script wider.

**Comment by Qhiliqq** [comment]
> REPQUOTA=`which repquota`
sudo $REPQUOTA /path/to/mountpoint

Geht ohne Passwort nicht.

Ich habe den Installer genutzt um alles zu installieren.

**Comment by ulrichblock** [comment]
Was passiert denn, wenn du den absoluten Pfad benutzt? Gab es ein Upgrade von Debian 7 auf 8 oder ähnliches? Stimmt der absolute Pfad in der suduers noch? Gehen die anderen Befehle? Wurde /usr/sbin/repquota genau so in der Konfiguration des Masterservers eingetragen? Wie sieht das generierte Skript bei aktivem Debugger aus?

**Comment by Qhiliqq** [comment]
> Was passiert denn, wenn du den absoluten Pfad benutzt?
/usr/sbin/ ist alles der absolute Pfad.

> Gab es ein Upgrade von Debian 7 auf 8 oder ähnliches?
Nein cleane Debian 8.0.3 netinst

> Gehen die anderen Befehle?
Useradd, mod, dek und apache restart laufen problemlos

> Wurde /usr/sbin/repquota genau so in der Konfiguration des Masterservers eingetragen?
Ja vom Installer herauskopiert, wird ja nach der Installation angezeigt

> Wie sieht das generierte Skript bei aktivem Debugger aus?
Ich verstehe gerade nich genau was du meinst.

**Comment by ulrichblock** [comment]
Wenn man den Debugger aktiviert, wird auf der Konsole das Shell Skript ausgegeben, dass auf deinem Web Master ausgeführt wird. Dies könnte so aussehen:
```
for DIR in `grep -E 'usrjquota=|usrquota' /etc/fstab | awk '{print $2}'`; do for USER in `sudo /usr/sbin/repquota  -u -v -s $DIR 2>/dev/null | grep 'web-' | awk '{print $1":"$3}'`; do USERS="$USERS;$USER"; done; done; echo "$USERS;"
```
Ich habe eben mal den Installer auf einem Minimal System durchlaufen lassen auch mit Key + Passwort und das System eingebunden. Dort kann ich das oben genannt Skritp unter dem angelegten master ausführen. Auch der Befehl bezüglich requota läuft:
```
webmaster@Test:~$ sudo /usr/sbin/repquota  -u -v -s /
*** Report for user quotas on device /dev/sda1
Block grace time: 7days; Inode grace time: 7days
                        Space limits                File limits
User            used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
root      --   1400M      0K      0K          37604     0     0
daemon    --     68K      0K      0K              4     0     0
man       --   1028K      0K      0K             98     0     0
www-data  --      4K      0K      0K              1     0     0
Debian-exim --     28K      0K      0K              7     0     0
statd     --     12K      0K      0K              3     0     0
karotte   --     20K      0K      0K              5     0     0
webmaster --     56K      0K      0K             14     0     0
mysql     --  29956K      0K      0K            100     0     0
ftp       --      4K      0K      0K              1     0     0

Statistics:
Total blocks: 7
Data blocks: 1
Entries: 10
Used average: 10.000000
```

Ich gehe deswegen davon aus, dass es ein lokale Problem mit Sudo bei dir ist.
