### ISSUE TITLE
[enhancement] Cronjobs

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#872]
Usually plesk don't execute the cronjobs, so I get this idea:
If a cronjob activity is missing, there could be a button to manually execute the task (just to fix temporarily) :D

**Comment by ulrichblock** [comment]
We do not support Plesk, as they tell everybody not to mix with other panels.

**Comment by Pandry** [comment]
Maybe I wasn't explicit...
It's happend more then once that a cronjob didn't started (Debian 8), and that's happend to plesk TOO...

**Comment by ulrichblock** [comment]
And once again no need. The admin needs to configure his system properly. If we would add such a thing people will never learn.

Oh and by the way you still can whitelist your PCs IP and call the files in the browser.
