### ISSUE TITLE
Rcon Konsole erweitern

### ISSUE THREAD

**Issue by FV-Chris** [easy-wi/developer#873]
Da einige Spiele die aktuelle Konsole nicht unterstützen, da Sie selbst keine Konsole mitliefern, muss eine zweite Konsole die über RCON läuft implementiert werden.
Mit einem Swtich im Gameserver Template wo man entscheiden kann welche Konsole genutzt werden soll, im Kundenbereich muss dan in den Einstellungen ein feld erstellt werden wo der Kunde das RCON Passwort hinterlegen kann.
https://developer.valvesoftware.com/wiki/Source_RCON_Protocol

**Comment by Pandry** [comment]
So...
I've used Google traslate, so I'm not sure to got the message, but, IF I've understood (it's a big if :P) 
Anyway, when you're creating a new game template, you can select if it needs the console or not...

**Comment by ragnos** [comment]
Darf ich vorschlagen statt exklusiv zwischen screenlog oder rcon zu entscheiden, beides gleichzeitig zuzulassen? Im Template festlegen welche Lösungen verfügbar sind (Jeweils ja/nein), dann Kundenseitig entweder zwei seperate Links zu den Konsolen oder umschaltbar in der LiveKonsole selbst.
