### ISSUE TITLE
minecraft_server.jar darf kein Symlink sein

### ISSUE THREAD

**Issue by florian96** [easy-wi/developer#878]
Hallo,

Ich hätte gerne, dass die nutzer die Minecraft_server.jar nach belieben Verändern dürfen. Leider ist dies aufgrund eines Symlinks nicht möglich.

**Comment by ulrichblock** [comment]
Dann willst du also dein System für Hacker weit auf machen? Wenn du dieses enorme Sicherheitsrisiko eingehen willst (frage ist nicht ob, sondern nur wann du gehackt wirst), dann konfiguriere das Minecraft Template so um, dass die Datei kopiert wird und deaktivere die FTP Regeln, die dich schützen würden.

**Comment by florian96** [comment]
Ist gemacht. Danke.

Das Risiko, hierbei gehackt zu werden ist sehr gering. (Schließlich lassen dies ja auch alle Professionellen hoster (Nitrado, Zap hosting, etc...) zu.

Zumal der schaden ohnehin nicht Groß wäre. Selbst wenn jemand eine Java Schadware hoch lädt, hätte diese nicht automatisch gleich Root Rechte. 

Und es gibt nun mal auch nutzer, die gerne eine Eigene Version nutzen oder Mit Modifikationen (Vanilla, Spigot, Bukkit, MCPC+, Cauldron, KCauldron, Forge) Und meiner Erfahrung nach macht gerade MCPC+, Kcauldron und Cauldron Probleme, wenn diese nicht in der Richtigen Version vorhanden ist.

**Comment by florian96** [comment]
Solltest du dennoch der Meinung sein, dies sei ein Sicherheitsrisiko, dann kannst du mir mal bitte eine Anleitung schreiben, wie du vorgehen würdest, um einen Schaden anzurichten.

**Comment by Bara20** [comment]
[Hierbei ZAP-Hosting zu erwähnen ist nicht besonders klug.](http://www.ulrich-block.de/angriff-auf-zap-hosting-com/)

**Comment by florian96** [comment]
Ja natürlich wurden diese Gehackt. Aber dies ist eine Ganz andere Schwachstelle gewesen.

Zum einen Hätten sie diese Möglichkeit entfernt. Ist aber immer noch möglich. Bin dort im übrigen kunde seit 2 Jahren. Also nach diesem Vorfall.

Zum anderen wurde erwähnt, schwache Passwörter seien schuld. (Mein Root Password. Hat 20 Zeichen und hat Klein, Großbuchstaben, Zahlen und Sonderzeichen).

Und: Zap hosting wurde mit etwa 40.000 Kunden 1 mal in Jahren Gehackt. Angenommen dies würde Proportional sein, dann werde ich mit 8 Leuten 1 mal Gehackt in Jahrhunderten.

**Comment by sosi-deadeye** [comment]
Bis der erste einen Control-Server für Bots auf seinem Server laufen hat.

**Comment by ulrichblock** [comment]
Leg einfach für jede Version eine Image an und installiere alle über GameSwitch. Der User kann dann zwischen den ganzen Versionen wählen und muss gar nichts hochladen. Ist viel sicherer und der User kann dann auch weniger falsch machen.

Ich bin mir sicher, dass deine Security Einschätzung an der Realität vorbei geht. Ich kenne so einige ITler, die sich genau diese Schwachstelle bei diversen Hostern zu nutze gemacht haben und dann zum Gameserver noch ganz andere Sachen laufen haben lassen. Und genau das verhindert das Interface. Alle Sicherheitsroutinen auszubauen ist einfach unverantwortlich und werden wir niemals machen. Wenn du es machen magst, bitte. Aber Hilfe werden wir sicher dafür nicht geben,
