### ISSUE TITLE
Rsync Imageserver

### ISSUE THREAD

**Issue by ludgart** [easy-wi/developer#879]
Hallo,

nach einer **neuen** Installations auf die neuste DEV Version habe ich den Imageserver erneut getestet.
Leider funktioniert der Imageserver bei mir nicht richtig.
Wenn Ich eine neue Datei auf meinen Imageserver hinzufügen und dann im Panel manuel aktualisiere,
wird die Datei erfolgreich auf X-Gameserver hinzugefügt.
Lösche/Ändere ich die Datei und aktualisiere passiert nichts auf dem X-Gameserver.

### Der Log vom X-Gameserver:
----------------------------------------
receiving incremental file list
mc_bungeecord/

sent 32 bytes  received 109 bytes  282.00 bytes/sec
total size is 9,718,644  speedup is 68,926.55

Die Datei wird erst übertragen, wenn ich sie **manuel** vom X-Gameserver lösche.
Mfg

**Comment by ulrichblock** [comment]
X-Gameserver verwenden wir niergens als Begriff. Was meinst du damit?

Masterserver -> Hier liegen die Dateien des Programms
User Server -> Ordner, Configs und Links beim "User/Kunden"

**Comment by ludgart** [comment]
Ich habe das Problem selber behoben, in dem Ich in der Datei "class_masterserver" folgendes geändert habe:

$this->shellScript .= 'SYNCCMD="rsync -azuvx ' . $this->imageserver . '"' . "\n";
zu:
$this->shellScript .= 'SYNCCMD="rsync --delete -azuvx ' . $this->imageserver . '"' . "\n";

Dadurch werden geänderte oder gelöschte Datein gesynct.

**Comment by ulrichblock** [comment]
Deute ich dass nun richtig, dass es dir alleinig darum geht, dass auf dem MasterServer gelöschte Dateien entfernt werden?

Dieses Feature ist bewusst deaktiviert, weil ansonsten zu viele Leute manuell Templates erstellen ohne einen Imageserver zu haben. Dann wird die Einstellung vergessen, dass kein Imageserver benutzt werden soll und weg sind die Daten, weil sie auf unserem voreingestellen nicht vorhanden sind.

**Comment by ludgart** [comment]
Nein, das Problem war das der ImageServer auf dem GameServer root keine Datein ändert, wenn es auf dem Master ImageServer eine Veränderung gab.

**Comment by ulrichblock** [comment]
Ich kann das Problem mit Debian nicht reproduzieren. Auch ohne "--delete" werden Dateien am Game Root aktualisiert, wenn am Image Server ein Update einer Datei kommt. Das Löschen ist aus oben genannten Gründen nicht implementiert.
