### ISSUE TITLE
wput Upload Limit (Backups)

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#880]
Hi,

würde Vorschlagen das Upload Limit bei Backups auf 10kB zu setzen anstatt wie bisher 4kB.
Grund sind die großen ARK, Rust und andere Spiele Backup Größen.

Datei: stuff/methods/class_app.php
Zeile: 2113 --limit-rate=4096 -> 10240

$script .= 'wput -q --limit-rate=10240--basename="' . $backupDir . '" "' . $backUpFile . '" "' . $ftpUploadString . '"' . "\n";

**Comment by ulrichblock** [comment]
Und wenn jemand nur eine 100Mbit Anbindung hat? Dann werden 2 backups gestartet und nichts geht mehr....

**Comment by Lacrimosa99** [comment]
Sind ja kB Angaben... daher sind 10 gleichzeitige max. möglich und der Server/das System ist immer noch erreichbar.
Normal macht man ja 3 Backups gleichzeitig in Arbeit (so meine Berechnung).

**Comment by ulrichblock** [comment]
Eine 100Mbit Karte hat im Full Duplex Mode ca 10,9Megabyte/s Durchsatz. Also ca 11000kb. Starte 3 Uploads mit 4096 sind wir schon bei 12288. Und was ist dann für die Gameserver über?

Ein generelles Anheben ist also alles andere als clever.
