### ISSUE TITLE
API Addition & Additional Game Variables

### ISSUE THREAD

**Issue by metallicgloss** [easy-wi/developer#882]
Hello.
I would like to ask a couple things.

1. Could you develop a feature in Easy-Wi API where the game master server and any additional IP on that server can be selected when generating a game server?

2. How do I make additional variables for each game? An example of this would be adding a variable in the settings of Garry's Mod to be able to allow them to enter the tick rate. If you could allow us to specify variables which the server can enter, so we can either use them on the website or in the game commandline, that would also be amazing.

If you are willing to do these, that would be great. Otherwise, I would consider paying for them to be developed privately if you do not wish to do them publically as I need these to continue using the panel.

**Comment by ulrichblock** [comment]
You already can provide a list of master server ids to be used at the api. Selecting IPv4s in a world, where you should use only one IP per root server seems odd.

Have you tried the custom columns option? They can be defined at the settings menu group.

**Comment by metallicgloss** [comment]
For 1. Yes, it may seem odd, however, I currently have one servers where a client has a DDoS protected IP address, so that would make up that additional IP. As for master server ID's, you cannot pick a specific one I do believe.

I tried the custom columns, however, they did not show up in any game's settings to be edited.

**Comment by Pandry** [comment]
I don't know if I got the question, but when you create or edit a master server, you can put some extras IPs...

**Comment by metallicgloss** [comment]
Yes. I am aware. But with the IP and server selection, I need it to be selectable through thr API. Currently, it just creates the server on the least used server out of a list, I need it so individual servers are selectable.

The main issue I have is with the extra variavles, as the custom columns don't turn to game server settings which are changable by the user.

**Comment by ulrichblock** [comment]
The API allows you to use "master_server_id" N times:
```
...
<master_server_id>1</master_server_id>
<master_server_id>2</master_server_id>
<master_server_id>3</master_server_id>
<master_server_id>4</master_server_id>
```

I recommend to use one puplic IPv4 for GS. Here the DDOS hits and might be protected. Second you have some kind of intranet/DMZ IP for SSH connections. They cannot be reached from the internet. This is the IP the panel connects to.

Given you have only one NIC at your server with multiple IPs and a DDoS is executed, then all IPs will be affected, as the NIC cannot handle the attack.

**Comment by metallicgloss** [comment]
The DDoS protection and IP for my server is up to me, and I can handle, and is not an issue for you to worry about. I was just getting in touch due to First-Version saying it wasnt possible: 
Part 1 of ticket: http://elhs.host/images/1b1f991W7.png
Part 2 of ticket: http://elhs.host/images/5HL0c68x7.png

Could you assist me with the Variables?

**Comment by metallicgloss** [comment]
I can see the custom columns in the Admin settings of the server, but they aren't accessible to the user.
