### ISSUE TITLE
FTP Error

### ISSUE THREAD

**Issue by Mic9817** [easy-wi/developer#883]
I've been trying to work this out for some time, I keep getting FTP errors or can't connect to ftp and then the server goes offline and crashed. I'm slightly confused and any help would be great.

When trying to connect through console : http://prntscr.com/bkl5fn

Also when clicking link to go to webftp there is nothing.

This was the error log : http://pastebin.com/afhDbXKx

Thank you

**Comment by Pandry** [comment]
try to remove proftpd and reinstall it using the installer...
It should be:
`apt purge proftpd-basic`

**Comment by ulrichblock** [comment]
Could be a local firewall on the webspace host. Also PHP functions might be disabled for the webhost preventing you from doing connections to FTP servers, game server's  query ports and so on.
