### ISSUE TITLE
Vorschlag: Vertreter Gruppen

### ISSUE THREAD

**Issue by Larry-Lizard** [easy-wi/developer#884]
Ich würde gerne das Feature sehen, dass man Vertretern bestimme Gruppen bzw. Rechte zuweisen kann.

Beispiel:
Innerhalb eines Clans wird das Easy WI verwendet.
Man hat Admin Accounts die die Server verwalten. 
Man möchte z.B. Supportern die Möglichkeit geben, nur den Server neuzustarten, also einen Vertreter Account anzulegen.

Ich hoffe, dass es verständlich ist.

MFG
Larry

**Comment by chronicals** [comment]
Man könnte das ja auch über die API Anbindung regeln, bis es so ein Feature gibt.

**Comment by Lacrimosa99** [comment]
Schau mal im User-Bereich nach "Vertreter"... diese können die gewünschten Funktionen.
