### ISSUE TITLE
What about Ajax

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#890]
I was thinking, why not implementi AJAX (IN THE FUTURE, maybe Easy-Wi 8 :P), for example when you start a server you get a notify instead of do a submit...

**Comment by ulrichblock** [comment]
AJAX is already in many places.....

**Comment by Pandry** [comment]
Excuse me...
I wrote wrongly the sentence.
That was a request for implement AJAX more...
(Anyway I got a bit later that a server is restarted or whatever on a submit, so on another PHP page, so it would be so difficult to make an action like that in AJAX)
