### ISSUE TITLE
Minecraft startup file

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#892]
Some MC versions use a start.sh file for an ingame restart command.
Maybe its possible to generate a linked start.sh created on server specs from the user?

This would be very useful ;)

**Comment by Pandry** [comment]
For me it would be really useless... (Over be a HUUUUUGE possible vulnerability...)
Just copy the content of the .sh file and create a template...

**Comment by Qhiliqq** [comment]
In the .sh file is the startupcommand

And no there would be no vulnerability, because it's linked like the server jars...

**Comment by Pandry** [comment]
So you could create a game template...

**Comment by Qhiliqq** [comment]
This is too complicated for normal Minecraft Players ;)

I think it would be easier to use an other panel just for Minecraft...
Unfortunately many neccessary options still missing for hosting a good Minecraft Server...

**Comment by Pandry** [comment]
Is would be the same as a normal minecraft server...

**Comment by ulrichblock** [comment]
The words good and Minecraft in one sentence? Wow!
I cannot see us creating workarounds for every hurdles those many types of servers create as they ignore good practises.

statuscheck.php can already restart. If you need a kill script, you can easily can write it yourself. 

For reference: https://easy-wi.com/forum/thread-7271.html
I already prompted you with how to, if you want to create a possible security problem. Any progress on your own?

**Comment by ulrichblock** [comment]
No comits, no replies. Seams to be quite irrelevant...

**Comment by Qhiliqq** [comment]
Nope, but I changed with Minecraft to another panel, which is just for Minecraft ;) Its easier for me and faster... Also there are much more options.
I'll make a pull request, if I got time to implement all neccessary Minecraft options and so on, without getting trouble about the security things of ew.

**Comment by ulrichblock** [comment]
So if you do not want to commit your time and provide help, why should we? So far you seem to be the only one that wants this.

**Comment by Qhiliqq** [comment]
I still working on that and I'm maybe the only one who wants this, but its necessary for 95% of my customers.

I tested to write the startup command into the Cvars which users aren't able to modify, but this doesn't work...

**Comment by Qhiliqq** [comment]
Isn't necessary.

Just delete /third_party/gameq/GameQ/Protocols/Minecraft.php so EW use GameQv2 and everything is ok ;)
