### ISSUE TITLE
Slotanzeige im Adminbereich

### ISSUE THREAD

**Issue by KDBFame** [easy-wi/developer#896]
Wie wäre es mit einer Slotanzeige für die einzelnen Gameserver im Admin-Bereich ?

Also ich meine das die belgten und maximalen Slots angezeigt werden.

**Comment by Qhiliqq** [comment]
Dann haste ja ne XXXL Liste, finde ich daher etwas doof, wenn das drin ist...

**Comment by KDBFame** [comment]
Wieso eine XXXL Liste ?

Ich habe mir was in der Richtung vorgestellt:        Slots: 12/32
Also eher was einfaches für jeden Server und es würde nicht einmal viel Platz kosten.

**Comment by ulrichblock** [comment]
Weil zu viele Spalten das Ganz schnell unübersichtlich machen. Vor allem, wenn man mal mit dem Handy usw. reinschaut.
