### ISSUE TITLE
With local IP setted not all features works.

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#904]
In my panel I have just 1 master server and it's the same as the web host, so I put in the settings 2 IPs: 127.0.0.1 for the panel (I've put the option about administration IP only) and my public IP...
The result was that the webftp works, but the live console and the settings don't...
I did not figured out the reason (because I'm from my mobile phone too) but it is a bug I suppose...

**Comment by ulrichblock** [comment]
It is not clear for me, what you have configured...

**Comment by Pandry** [comment]
Okay...
I'll try to explain...
I installed the panel and configured the master on the same machine, so i put as IP the local IP (127.0.0.1) and as extra IP the public IP.
I setted that the first IP was used as administration IP only, and, some features didn't wored...

**Comment by ulrichblock** [comment]
Seems like your FTP Server does not listen on the public IP. This seems to be the case as userpanel_gserver.php uses the public at settings:
https://github.com/easy-wi/developer/blob/master/stuff/user/userpanel_gserver.php#L299
