### ISSUE TITLE
Improve the mobile theme

### ISSUE THREAD

**Issue by Pandry** [easy-wi/developer#905]
When I'm from my phone, it's almost impossible to log-out if the page is "shorter" than the menù (the menu get "cutted" so it's impossible to log-out nor edit the profile)
Also the links are invisible (in the menù).

**Comment by Pandry** [comment]
Image 1:
http://i.imgur.com/EE9eMDP.png
And ths is when the screen is bit, but when it's tiny and the page is short, I can't access to the logout button...
Image 2:
http://i.imgur.com/1UXRKkh.png

**Comment by Pandry** [comment]
To fix the navbar it could be implemented this code:
`max-height: calc(100vh - 210px);overflow-y: auto;`
To make it scrollable...
When, insted, to make the links visible, the default code is nice, but it should be applyed:
`.dropdown-menu>li>a {
    color: #777;
}
.dropdown-menu>li>a {
    display: block;
    padding: 3px 20px;
    clear: both;
    font-weight: 400;
    line-height: 1.42857143;
    color: #333;
    white-space: nowrap;
}`

**Comment by ulrichblock** [comment]
Please provide a pull request, as these snippets are out of context.

Thx..

**Comment by Pandry** [comment]
I promise I'll make a pull request as soon as I can, but you need to wait at least 1 or 2 weeks...
That's why I put some suggestion :P

**Comment by ulrichblock** [comment]
Any update on this?
