### ISSUE TITLE
*BUG* Permissions Loss

### ISSUE THREAD

**Issue by metallicgloss** [easy-wi/developer#906]
Hello.

I am finding a bug that has begun happening to a few of my customers. They have a game server, not dependant on the game, and, after a week or so, they suddenly cannot edit, or delete the files on their server. They can upload, edit and delete new ones, but the old ones are almost locked. I have attempted to run the re-synchronisation feature on their server when that didn't work after 10 minutes, I attempted to reinstall their server after making a backup. Even after re-installing it, if you upload the old files back through FTP, they get locked instantly. It turns out, the only way to unlock these files is to delete the server and re-make them for the user to be able to edit any of the game files or files they previously had.

If you could provide me with any sort of assistance to get this fixed, I would be grateful.

**Comment by Pandry** [comment]
Have u tried doing a chown to the respective owner?

**Comment by metallicgloss** [comment]
I haven't tried doing it, as I have never heard of a file suddenly losing its owner. I can try but the last time I messed with permissions I lost access to all files as root.

**Comment by Pandry** [comment]
Well, you have just to navigate to your clients server's path and do:
`chown -R <userx-x> <userx-x/>`
so, for example:
`chown -R <user5-3> <user5-3/>`

**Comment by metallicgloss** [comment]
I'll try that, and I'll report back if there is any more issues. Thank you very much @Pandry

**Comment by Pandry** [comment]
You're welcome!
I would suggest you to make a chgrp too, to be sure...
This time is different because the chgroup need the same user (this time the user that you use for the panel)
So, for example I use a user named gamess (GAMES Servers), let's call it the "main user", so you should do that:
'chgrp -R <your main user> <your default name for users>*'
So, for example:
'chgrp -R gamess user*'

**Comment by Pandry** [comment]
Wait, my phone deleted some thongs, wait a moment and don't do anything!

**Comment by Pandry** [comment]
Okay, I've edited the comment,you can do it now :smile:

**Comment by metallicgloss** [comment]
Ok, thanks! What would be the point/difference between just CHOWN and CHGRP when it comes to this issue?
