### ISSUE TITLE
Minecraft server.properities

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#908]
If mc server is created, the server.properities is created successful and without errors.
After a restart the file changes ther values to online-mode="true" or any other values.

If the server now start, he can't resolve the "true" and start the server in offline mode...

Normaly the values are given without the ""

Is this a fail from the wi?
This error is on every version of minecraft.

EW version is the git version downloaded at 19. July 2016

**Comment by Pandry** [comment]
Look at the settings of the server..
Online mode or Offline mode

**Comment by Qhiliqq** [comment]
Nice joke :D

The problem is the "" not the setting ;)
And after changing it, and start the server, it will be reset to "true".

**Comment by Pandry** [comment]
Yeah, but I think it don't mind...

**Comment by Qhiliqq** [comment]
Of course.

Also the worlds will be recreated to "world" as folder not world, without the " ". It looks that something was changed in the newer EW version.

**Comment by Pandry** [comment]
I think it was always like this..

**Comment by Qhiliqq** [comment]
Nope never ;)

This crushes every plugin and the whole server...

I don't know why this is. I can't change it, because it every time changes back automatically.

**Comment by Pandry** [comment]
You could change it...
Just edit the minecraft template...

**Comment by Qhiliqq** [comment]
There is no fail!

There wasn't any fail before updating, and I just want to report that.

The templates are still the same as before.

I have about 30 minecraft templates, after updating every template have this fail? Sure...

**Comment by Pandry** [comment]
So...
It's a problem of miecraft...
I suppose you can close the issue...

**Comment by Pandry** [comment]
Do you have a TS3 server, a mumble one or a discord one?
So I could help you...

**Comment by Qhiliqq** [comment]
I'll ask Ulrich or another dev for help.

**Comment by Pandry** [comment]
This isn't a EW problem:
The games weren't touched...
https://github.com/easy-wi/developer/commits/master

**Comment by Qhiliqq** [comment]
Of course it is an EW problem ;)

FV-Chris has got the same bug :P

I didn't say something about the games.
Just about the restart problem.

I hope Ulrich will fix that.

**Comment by ulrichblock** [comment]
And of course, this long conversation would not have happened, if the issue would have been reported properly.

Of course this is **not** a minecraft propblem. Minecraft is just a game that is affected by a problem. This problem affects any game with protected configs of the type ini.

**Comment by Qhiliqq** [comment]
Can be closed, works :+1:

**Comment by Qhiliqq** [comment]
Same problem on config.yml files at bungeecord servers for minecraft.

Adding after restart ' ' , " " or 0: 1: 2: 3:

Before:
`query_enabled: true
disabled_commands:
- disabledcommandhere
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
query_port: 27045
online_mode: true
host: 87.xxx.xxx.xxx
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  default_server: lobby
  bind_local_address: true
  fallback_server: lobby
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
stats: 49a0b716-ef9a-48ab-98da-eace8e34c51d
ip_forward: false
groups:
  md_5:
  - admin
connection_throttle: 4000
bind_local_address: true`

After restart:
`---
query_enabled: 'true'
disabled_commands: ""
0: disabledcommandhere
player_limit: -1
permissions:
  default: ""
  0: bungeecord.command.server
  1: bungeecord.command.list
  admin: ""
  2: bungeecord.command.alert
  3: bungeecord.command.end
  4: bungeecord.command.ip
  5: bungeecord.command.reload
timeout: 30000
query_port: "27045"
online_mode: true
host: 87.xxx.xxx.xxx
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
listeners: ""
1:
  query_port: "27045"
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: 'true'
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  default_server: lobby
  bind_local_address: 'true'
  fallback_server: lobby
  host: 87.xxx.xxx.xxx
  max_players: 1
  tab_size: 60
  force_default_server: false
stats: 49a0b716-ef9a-48ab-98da-eace8e34c51d
ip_forward: false
groups:
  md_5: ""
  0: admin
connection_throttle: 4000
bind_local_address: 'true'`

**Comment by ulrichblock** [comment]
Different problem and as such requires different ticket.

**Comment by hunternet** [comment]
It's very simple to do this in configurations.

Game server> game server template> (open your mc template in my case the bukkit and spigot)

Click modify search

Cvars which the user must not modify - she will be like this
[Server.properties] i ini
Server-port =% port%
Query.port =% port%
Enable-query = true
Rcon.port =% port2%
Server-ip =% ip%
Max-players =% slots%

Just delete the first line to make it so

Server-port =% port%
Query.port =% port%
Enable-query = true
Rcon.port =% port2%
Server-ip =% ip%
Max-players =% slots%

**Comment by Qhiliqq** [comment]
@hunternet doesn't work
