### ISSUE TITLE
Wrong password or user at fresh install

### ISSUE THREAD

**Issue by minikanyas** [easy-wi/developer#910]
I've did a fresh install of the panel using the script, and I can't log in because of this error, I've looked on the logs, and this errors appears
`[Wed Jul 27 20:00:05.180059 2016] [ssl:warn] [pid 11421] AH01906: 192.168.0.153:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Jul 27 20:00:05.268769 2016] [ssl:warn] [pid 11422] AH01906: 192.168.0.153:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Jul 27 20:00:28.314802 2016] [:error] [pid 11470] [client 192.168.0.31:18423] PHP Warning:  include(/home/easywi_web/htdocs/stuff/config.php): failed to open stream: No such file or directory in /home/easywi_web/htdocs/stuff/settings.php on line 53
[Wed Jul 27 20:00:28.315007 2016] [:error] [pid 11470] [client 192.168.0.31:18423] PHP Warning:  include(): Failed opening '/home/easywi_web/htdocs/stuff/config.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /home/easywi_web/htdocs/stuff/settings.php on line 53
[Wed Jul 27 20:00:28.315115 2016] [:error] [pid 11470] [client 192.168.0.31:18423] PHP Notice:  Undefined variable: captcha in /home/easywi_web/htdocs/stuff/settings.php on line 55
[Wed Jul 27 20:00:28.315194 2016] [:error] [pid 11470] [client 192.168.0.31:18423] PHP Notice:  Undefined variable: title in /home/easywi_web/htdocs/stuff/settings.php on line 56
[Wed Jul 27 20:00:28.315274 2016] [:error] [pid 11470] [client 192.168.0.31:18423] PHP Notice:  Undefined variable: host in /home/easywi_web/htdocs/stuff/settings.php on line 59
[Wed Jul 27 20:00:28.315348 2016] [:error] [pid 11470] [client 192.168.0.31:18423] PHP Notice:  Undefined variable: user in /home/easywi_web/htdocs/stuff/settings.php on line 60
[Wed Jul 27 20:00:28.315421 2016] [:error] [pid 11470] [client 192.168.0.31:18423] PHP Notice:  Undefined variable: pwd in /home/easywi_web/htdocs/stuff/settings.php on line 61
[Wed Jul 27 20:00:28.315493 2016] [:error] [pid 11470] [client 192.168.0.31:18423] PHP Notice:  Undefined variable: db in /home/easywi_web/htdocs/stuff/settings.php on line 62
`

**Comment by ulrichblock** [comment]
https://easy-wi.com/forum/thread-7726.html
