### ISSUE TITLE
Making custom columns editable by client.

### ISSUE THREAD

**Issue by metallicgloss** [easy-wi/developer#912]
Hello.

I am looking for a solution or modification on how to make the custom columns editable by clients so that they can create custom command line variables. I created this on the forums, but Ulrich refused to help me and others solve this issue. Currently, clients can't make custom variables or set things like RCon passwords. Myself and others need this fixed, or a solution found. If ANYONE can assist me with this, I would be VERY grateful.

**Comment by Pandry** [comment]
i don't feel that need...
if u want u can do it yourself and do a pull request :wink:

**Comment by metallicgloss** [comment]
So you are Ulrich? I'm surprised as you were incredibly helpful on my last submission but not now. And it isn't you don't feel the need. You just cant be asked to do it. As I messaged Ulrich. I would pay to get this solved. Or move panel.

**Comment by Pandry** [comment]
As you can see I'm not Ulrich, and, beeing a open source software I'm trying to see how can I help this panel to improve (as much as I can...).
But, a request like this would modify a lot the base of the panel structure (al least i think), and it would be hard to do...
So it's a very big request (even it don't looks like...)
So, kidding, I said u that you could try doing it yourself...

**Comment by metallicgloss** [comment]
Sorry, I know that Ulrich has it out for me, and seems to be the only developer. I thought he might have used a different account. I do apologise. I didn't realise it is a big request, I'll continue trying with the API, I just made it as there are multiple people using this panel wanting it. And I could do it, but, after looking at the code already, it is quite messy, and, not well documented at all in English.

**Comment by Pandry** [comment]
Yeah, it could be cool, but it wouldn't be easy to do...

**Comment by metallicgloss** [comment]
That is a huge shame. It would be nice if Ulrich continued developing the panel and adding this. I even offered to pay him just for support after he refused to help after I bumped a post after 3 weeks, and he just ignored me. Shame, ill have a mess around with the API as I hope it could do it.

**Comment by ulrichblock** [comment]
I am always continuing. Just look at the amount of commits this month...

I do not think it is that complicated. But currently it is summer. So my priorities are way different than helping a business for free.

Plus I am not interested in doing payed work.

Also tickets like this, where you put it, like I have to help you, do not increase my motivation to look at this at all.

So either this comes as pull request, or it will not come in the near future.

**Comment by metallicgloss** [comment]
I appreciate that your priorities aren't with Easy-Wi and making requests from random users. And I did not know you didn't do paid work, as you ignored me on the forum and via email. And it isn't my fault that it doesn't increase your motivation, as other people are trying to help you deal with someone who isn't German so has difficulties using the panel or developing it further for person use.

I also am aware you aren't keen on assisting myself in general, as you seem to have had it out for me ever since I bumped a post twice after 2/3 weeks, as it was ignored. When people truly help, as @Pandry has done multiple times, I do appreciate it FULLY. I know this isn't a paid for service, but just assistance from the person developing it would have been nice, or AT LEAST saying - No, you can't do it, we haven't added it yet.

Either way. Thank you again, Pandry, ill try to develop it myself or move panel.

**Comment by ulrichblock** [comment]
Its just the way how you put it. Playing with accusations and guilt. 

If you would have put it like: #913 the reaction probably would have been way different.
