### ISSUE TITLE
Versioning with Github

### ISSUE THREAD

**Issue by ulrichblock** [easy-wi/developer#915]
Add the option dev/stable at the settings.

If stable check the releases api: https://api.github.com/repos/easy-wi/developer/releases/latest
If dev check the tags api https://api.github.com/repos/easy-wi/developer/tags

Updater should use the same apis to get the most recent zipfile.

**Comment by Lacrimosa99** [comment]
Versions Update von 5.32 -> 5.34 Fehler.
Die Version in der DB wurde nicht auf die Version 5.34 umgeschrieben und steht aktuell noch bei 5.33.
Daher weiterhin die Meldung, das ein Update des DEV´s verfügbar wäre.
