### ISSUE TITLE
Restart Counter to Screen (Gameserver)

### ISSUE THREAD

**Issue by Lacrimosa99** [easy-wi/developer#918]
Hy,

its possible to make a restart counter, where send a counter message when a server reboot is coming?

---

Deutsch

Ist es möglich, einen Restart Counter zu bauen, welcher eine Nachricht an den Screen des Servers sendet, wenn ein Reboot ansteht?

Gruß

**Comment by Pandry** [comment]
Wait...
I know what a counter is, and a restart counter would be useless...
What would you do with the number of times you re-started a server?
I don't got the part where the panel should " send a counter message", can you explain it to a perfect dumb like me?

**Comment by Lacrimosa99** [comment]
My Idea is, send a Message to screen with the info, that the server will be restart in x minutes.
Like... the Panel registered a Update from Valve... he´s downloading the Update and send a message into the screen (Gameserver Screen) with following text "Server restart in X Minutes".
Can you follow me?

**Comment by Pandry** [comment]
So...
You want to send a command to the console and delay the restart.
For me is useless...

**Comment by Lacrimosa99** [comment]
For ARK players is this the best way to safe her animals.
For other games is this a good way to see, when a gameserver becomes a restart.
Many peoples write me, what with the server is.. i only "server restart".

**Comment by Pandry** [comment]
So before restart warn about it, wait 5 mins and restart...

**Comment by Nexus633** [comment]
Not every game supports sending a message to the screen. Minecraft, for example, does not support the cs / css / csgo series. Since it is controlled by the source btw by the metamod. 

You would have to filter the games that support it. Generally not an issue but whether the effort is useful is the question.
