### ISSUE TITLE
Restarts infolge Webserver-Timeouts verhindern

### ISSUE THREAD

**Issue by LordRofl** [easy-wi/developer#922]
Hallo,
leider kommt es manchmal dazu, das unser Webserver (nicht die Roots mit den Gameservern) paketverlust hat.
Das verleitet Easy-Wi sofort dazu sogut wie alle Gameserver neu zu starten, sehr zum Ärger der Leute die auf den Gameservern unterwegs sind.

Ja, natürlich ist das unser Problem, das unser Webpart von Easy-Wi paketverlust hat, klar.
Aber dennoch denke ich, das es eine Verbesserung im Falle der Fälle ist. So profitiert irgendwann bestimmt jeder mal davon.

Ich stelle mir das so vor: Easy-Wi merkt das nicht nur ein Server down ist, sondern viele. Daraufhin kommt ein Sicherheitscheck an eine Vergleichsadresse (Google, Amazon, etc.) Sollte die dann auch nicht erreichbar sein, dann setzt Easy-Wi die Neustarts der Gameserver aus.

Meinungen?

Gruß,
LordRofl

**Comment by ulrichblock** [comment]
Meine Meinung; Wenn man defekte Webserver hat, austauschen!
Wenn es zu false positives kommt: Retries hochsetzen!

**Comment by LordRofl** [comment]
Der Anbieter ist dran, solange quälen wir unsere User.

Kurze Frage, wie setze ich die Retries hoch?
(Found offline since 965 checks) wie viel Sekunden sind 965 checks?
