### ISSUE TITLE
yml files change their content

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#923]
Almost the same as https://github.com/easy-wi/developer/issues/908

Problem on config.yml files at bungeecord servers for minecraft.
Before restart there are no problems, but after clicking restart the values of the content from yml files changed and servers can't startup correctly.

Adding after restart ' ' , " " or 0: 1: 2: 3:

Before restart:
http://pastebin.com/p4KW2GA6

After restart:
http://pastebin.com/0gafn0J1

**Comment by ulrichblock** [comment]
Completely different problem...

**Comment by Qhiliqq** [comment]
Okay, thought its almost the same, sorry for that.

Do you need more informations?

**Comment by Qhiliqq** [comment]
Where I can fix that?
Can't find the right files...

I need this again, losing many customers...

**Comment by Lacrimosa99** [comment]
Have you saved in Unix/Linux Format or in Windows?
Check if your Config in Linux Format...

**Comment by Qhiliqq** [comment]
No I didn't change anything.
Just started Bungeecord form its jar without any other files.
After first start the yml is correct but if you click restart without changing something my problem occurs.

**Comment by ulrichblock** [comment]
Its a Bug in the third party lib "Spyc -- A Simple PHP YAML Class"

**Comment by Qhiliqq** [comment]
And how I can fix that? Spyc was last edited five months ago.

**Comment by ulrichblock** [comment]
Well either you fix it, or we can change to a different lib. Problem is, that there are not many, Symfony has one but will dump like`query_enabled: true
disabled_commands:
    - disabledcommandhere
player_limit: -1
permissions:
    default: [bungeecord.command.server, bungeecord.command.list]
    admin: [bungeecord.command.alert, bungeecord.command.end, bungeecord.command.ip, bungeecord.command.reload]
timeout: 30000
query_port: 27045
online_mode: true
host: 87.xxx.xxx.xxx
servers:
    lobby: { motd: '&1Just another BungeeCord - Forced Host', address: 'localhost:25565', restricted: false }
listeners:
    - { query_port: 25577, motd: '&1Another Bungee server', tab_list: GLOBAL_PING, query_enabled: false, forced_hosts: { pvp.md-5.net: pvp }, ping_passthrough: false, default_server: lobby, bind_local_address: true, fallback_server: lobby, host: '0.0.0.0:25577', max_players: 1, tab_size: 60, force_default_server: false }
stats: 49a0b716-ef9a-48ab-98da-eace8e34c51d
ip_forward: false
groups:
    md_5: [admin]
connection_throttle: 4000
bind_local_address: true`

I don't know how good MC servers are. But my guess is, that this valid format will not be accepted. If a CFG like my example works I could change...

**Comment by Qhiliqq** [comment]
Tested and it seem to be working fine.

Thank you if you change it :) :+1:

**Comment by ulrichblock** [comment]
Note: In case the to be replaced value is a nested one, the file configuration should be nested as well:
```
[test.yml] yml
host: %ip%
query_port: %port2%
listeners:
- query_port: 1000
max-players: %slots%
enable-rcon : true
```
