### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by metallicgloss** [easy-wi/developer#929]
Hello.

I am currently experiencing 2 weird bugs, and if you have the time, assistance would be appreciated.
1. When I set a Master game server to have 6 cores, in the game core bind menu it shows double that which I entered. 
2. If I attempt to core bind a game, it doesnt actually bind them. I attempted to bind a game server to core 5 and 6, yet it still runs off of core 1 & 2. Would you know how I could fix this?

**Comment by ulrichblock** [comment]
My guess: You have ticked hyperthreading, while your CPU does not supports it.

**Comment by metallicgloss** [comment]
Thank you very much.
