### ISSUE TITLE
Add possibility to choose the CS:GO Beta as a server

### ISSUE THREAD

**Issue by shnytzl** [easy-wi/developer#930]
Hi,
Valve released a betaversion for clients and servers for CS:GO tonight, will this embedded in Easy-WI to choose from?
-http://blog.counter-strike.net/index.php/2016/09/15820/
-to opt in for servers: run "+app_update 740 -beta 1.35.4.7rc" in SteamCMD
Thanks!

**Comment by ulrichblock** [comment]
Change or create a new template for this regard. No need to change the code.

**Comment by cytec** [comment]
@ulrichblock maybe im blind but where should the template be changed to include the additional parameters?

the steamID field is an int only field so it doesn't take `-beta 1.35.4.7rc` as addition and i can't find any other place where one could put this in
