### ISSUE TITLE
TS3 Master Instances Down after Upgrade to 5.33

### ISSUE THREAD

**Issue by n3xt-systems** [easy-wi/developer#935]
After upgrading successfully to 5.33 all TS3 Instances are shown as down, instead servers are running. Had to stop reboot and statusupdates cron to prevent failure restarts:

Connecting to TS3 server 46.165.237.***
error id=1024 msg=invalid serverID

TS3 46.165.237.88 down but no Restart triggert
Connecting to TS3 server 178.162.194.***
error id=1024 msg=invalid serverID

TS3 178.162.194.193 down but no Restart triggert
Connecting to TS3 server 85.214.208.***
error id=1024 msg=invalid serverID

TS3 85.214.208.182 down but no Restart triggert
Connecting to TS3 server 185.19.216.***
error id=1024 msg=invalid serverID

TS3 185.19.216.103 down but no Restart triggert
Connecting to TS3 server 31.172.88.***
error id=1024 msg=invalid serverID

TS3 31.172.88.*** down but no Restart triggert

Please help. THX in advance!
Best
Alex

**Comment by ulrichblock** [comment]
Check #932
