### ISSUE TITLE
Getting kicked out of server often

### ISSUE THREAD

**Issue by UberNoel** [easy-wi/developer#940]
Hi , 
Internal Exception : io.netty.handler.codec.DecoderException:java.lang.IndexOutOfBoundsException: readerIndex(1068) + length(1) exceeds writerIndex(1068): UnpooledHeapByTeBuf(ridx: 1068,widx: 1068, cap:1068/1068)

Everyone in the server gets kicked like once or twice every few minutes and give this error. Fyi , the server isnt off , everyone has to just rejoin the server again. Is there a solution to fix this problem?

**Comment by ulrichblock** [comment]
From Easy-Wi side? Not at all. Neither do we know what server you are using, nor does Easy-Wi kick any players at any point.

**Comment by UberNoel** [comment]
Oh sorry , can you move it to minecraft servers side ? Im quite new to this site all i did was click New issue and started writing . My bad

**Comment by FV-Chris** [comment]
This Problem come from a corupted Plugin and not from Easy-WI!

**Comment by UberNoel** [comment]
can i have the link to that Corupted Plugin side?

**Comment by FV-Chris** [comment]
Please use google... with "Internal Exception : io.netty.handler.codec.DecoderException:java.lang.IndexOutOfBoundsException:"
