### ISSUE TITLE
User erstellen nicht möglich

### ISSUE THREAD

**Issue by Blacktiger21** [easy-wi/developer#945]
Bei der Version 5.30 ist das erstellen eines neuen User nicht möglich der debug modus sagt nur

Fatal error: Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1969-12-31' for column 'birthday' at row 1 in /var/www/html/Web/stuff/admin/user.php:337 Stack trace: #0 /var/www/html/Web/stuff/admin/user.php(337): PDOStatement->execute(Array) #1 /var/www/html/Web/admin.php(53): include('/var/www/html/W...') #2 {main} thrown in /var/www/html/Web/stuff/admin/user.php on line 337

**Comment by gOOvER** [comment]
Ich kann diesen Fehler definitiv nicht bestätigen.  bei mir gehts ohne Probleme.  Ubuntu 16.04.1

**Comment by Blacktiger21** [comment]
ist beim testen aufgefallen habe das runtergeladen installiert und dann konnte ich keine user erstellen habe auch ubuntu16.04 wenn ich aber ein datum von heute oder so nehme gehts komischerweise

**Comment by PitbullOL** [comment]
Kann auch ich nicht bestätigen gerade auf einer Lokalen VM getestet, von wo benutzt du dein Installations Medium von Ubuntu?

**Comment by Blacktiger21** [comment]
also das einzige was ich sagen kann ist das ich den easy-wi aktuell runtergeladen habe und es nicht geht ich habe ubuntu 16.04 mit mysql und apache2 und php 7 und alles was dazu gehört

**Comment by ulrichblock** [comment]
Stell mal die CFG von deinem SQL Server um:
http://dba.stackexchange.com/questions/48704/mysql-5-6-datetime-incorrect-datetime-value-2013-08-25t1700000000-with-er

**Comment by ulrichblock** [comment]
Grund ist  #840
