### ISSUE TITLE
Sourcemod and Metmod not working in correct branch

### ISSUE THREAD

**Issue by TandelK** [easy-wi/developer#946]
Recently i was trying to add Sourcemod and Metamod to one of my server. What i saw was that the current Metamod and Sourcemod running on the server is actually Dev version of 1.17 and currently the sourcemod is 1.18 stable branch. I had installed Sourcemod and Metamod normal version. After that i took root access and went in that specific folder and uploaded new version of Metamod and Sourcemod and later on found that Addons no longer have all 4 Mods available for CS GO.

**Comment by ulrichblock** [comment]
This is not an Easy-Wi issue. Keep your Image Server up to date and do not rely on ours.
