### ISSUE TITLE
Minecraft ingame restart

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#951]
Ist es möglich über eine while do Schleife, den Screenlog bei Minecraftservern abzurufen, wenn im Log folgendes erscheint
`INFO]: Startup script './start.sh' does not exist! Stopping server`
soll der Screen, bzw. Server einfach restarten.

Wenn
`INFO]: Stopping the server`
im Log auftaucht soll der Screen terminated, bzw. der Server gestoppt werden.

Allerdings muss die Abfrage "INFO]: Startup script './start.sh' does not exist! Stopping server" vor "INFO]: Stopping the server" kommen, da der Restart command von Minecraft folgendes bei einem Restart ausgibt:

`[11:51:09 INFO]: Startup script './start.sh' does not exist! Stopping server.
>
[11:51:09 INFO]: Stopping server`

Die Zeichenkette "INFO]: " ist hierbei als Missbrauchsschutz bzgl. Spielerchats o.ä. angehängt.

Ich hab das ganze mal in einer Shell (sollte PHP sein um es mit EW auszuführen) geschrieben, wo es so auch funktionieren würde:
http://pastebin.com/eHQkpQZR

Vielen Dank und noch einen frohen letzten Weihnachtstag.

**Comment by ulrichblock** [comment]
Try deleting the screenlog, while running and see what happens to this type of code. My guess: Fail.

There is a cron which wipes the logs in case they get to big. This has been added specifically for minecraft, where they get to sizes above 1gb within a couple of hours:
https://github.com/easy-wi/installer/blob/master/easy-wi_install.sh#L1234

**Comment by ulrichblock** [comment]
Sorry cannot be implemented this way...
