### ISSUE TITLE
MySQL RestAPI

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#965]
Ich würde gerne auswählen auf welchen Master die DB erstellt wird, füge ich jedoch bei <server_local_id> meine Masterid ein, so wird dort die DB nicht erstellt, sondern auf dem Server mit der geringsten Auslastung.
Bei <identify_server_by> ist natürlich server_local_id eingetragen.

Das hinzufügen an sich geht, nur würde ich gerne das ganze auf einen speziellen Master adden.

Kann mir jemand helfen, oder ist diese Funktion so nicht gedacht, sondern nur bei del/mod?

**Comment by ulrichblock** [comment]
Die Felder, die du suchst sind master_server_id und master_server_external_id siehe https://github.com/easy-wi/developer/blob/master/stuff/api/api_mysql.php#L89
