### ISSUE TITLE
bug? [Lendserver - Module]

### ISSUE THREAD

**Issue by MikkelDK** [easy-wi/developer#967]
if i trying enable "Lendserver" there is no way (where you can lend gameservers)

(Only, if i make extra page with this link: **index.php?site=lendserver&d=gs**

_Module deactivated_ < The lendserver module is actived. (what can i do?)

**Comment by MikkelDK** [comment]
@ulrichblock - do you know about there is something fix?

**Comment by ulrichblock** [comment]
You need to configure your lend module.
