### ISSUE TITLE
Classic Offensive support

### ISSUE THREAD

**Issue by Bara** [easy-wi/developer#975]
Habe vorhin mit ZooL geschrieben, wie man einen Server installieren kann mit der Steam-Version die hoffentlich bald erscheinen wird.

Zur Installation:
- Man installiert zuerst einen normalen CSGO Server (appid 740)
- Danach installiert man den Classic Offensive Server (force_install_dir bleibt gleich - allerdings ändert sich die appid zu 600380 (ob es die sein wird steht allerdings noch nicht fest))
- Der Startparameter bleibt eigentlich wie bei CSGO nur das der Server nicht mit "-game csgo" gestartet wird sondern mit "-game csco)

Hoffe man könnte vorher schon was provisorisches einbauen, damit man später "weniger" Arbeit hat.

Habe soeben auch Zugang zur Beta bekommen, wenn es zu testen gibt kann ich es jetzt auch testen.

**Comment by Bara20** [comment]
Hab soeben wie folgt ein Server installiert:
- login XXX (mit mein Account wegen Beta)
- force_install_dir /home/cscoTest/
- app_update 740
- app_update 600380
das war es auch eigentlich schon.

**Comment by ulrichblock** [comment]
Also bräuchte man die Option, dass man N AppIDs in ein Verzeichnis installieren kann?

**Comment by Bara20** [comment]
Theoretisch müsste man Support für eine 2. AppID einfügen und ggf. ein Verzeichnis dafür. Allerdings muss hier (bei CSGO+CO) beides in ein Verzeichnis installiert werden (CSGO erstellt den Server und CO packt sozusagen nur seine Dateien rein). 
![co](https://cloud.githubusercontent.com/assets/17928280/24586395/266d37d0-17a0-11e7-9cc9-dc2a16c6363d.png)
(der markierte Ordner ist das was CO herunterlädt.

Hab das ganze [im LGSM bereits umgesetzt](https://github.com/GameServerManagers/LinuxGSM/pull/1384)
) und funktioniert einwandfrei.

**Comment by Nexus633** [comment]
Ist dieser Wunsch noch offen? Da dieser Beitrag 3 Jahre alt ist und ich kein Spiel kenne was sich auf dieser Art installiert, ist nun die Frage ob eine implementierung noch sinnvoll ist.

Bitte um Antwort!

**Comment by Bara** [comment]
Aktuell nicht, das Spiel bzw. die Mod wird aktuell zwar noch weiter entwickelt aber das nur nebenbei. Wird also noch etwas dauern. Und ja die Installation ist sehr speziell gewesen, aber so hatten ZooL und ich es zum laufen bekommen auf ein automatisierten Weg.

Werde mich melden, sollte das Spiel wieder relevant sein. Bis dahin schließe ich das hier mal.
