### ISSUE TITLE
Teamspeak 3 Serverviewer

### ISSUE THREAD

**Issue by ulrichblock** [easy-wi/developer#98]
In addition to view add menu with whom the user can kick/bann users from the server

**Comment by Pandry** [comment]
If you want to save time, you could integrate the psycokiller interface :)
https://github.com/maxlin1990/ts3web/blob/master/site/serverview.php

**Comment by ulrichblock** [comment]
Most definitely not. Differrent concept and code structure will not allow this.

**Comment by Pandry** [comment]
Okay...
After added the WebFTP to the WebSpace (admitted that I'll succeed), I'll try to add it making it from 0 :)
