### ISSUE TITLE
YAML Error Reporting

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#983]
Wenn es einen Fehler in einer YAML Datei gibt, z.B. falscher Absatz, so erscheint beim starten eines Servers ein PHP Error Code und die Seite lädt nicht.

PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Yaml\\Exception\\ParseException' with message 'Malformed inline YAML string ('

Wäre es möglich einen Error einzubauen, welcher bei einer solchen oder ähnlichen Meldung dem User angezeigt wird?

**Comment by ulrichblock** [comment]
Wenn die Datei kaputt ist, lässt sich der Server wohl eh nicht starten. Deswegen sollte man sie ersetzen.
Dies kann still im Hintergrund geschehen. Die Exception wird abgefangen die werte durch ein leeres array/object ersetzt und weiter gemacht. Der Server bekommt dann eine minimale Datei vorgesetzt und der User muss sie ggf. wieder anpassen.

**Comment by Qhiliqq** [comment]
Dass sich der Server dann nicht starten lässt ist klar, jedoch wäre es optisch und für den User informativ, dass in der Datei ein Fehler ist. Eine weiße PHP Error Page hilft ihm dabei nicht.

**Comment by ulrichblock** [comment]
Der Commit behandelt die Fehler, wie andere Fehler auch behandelt werden: Sie werden NICHT angezeigt, es gibt aber auch keine Exception.
