### ISSUE TITLE
Cannot exec './hlds_run': No such file or directory

### ISSUE THREAD

**Issue by Eiskaltereistee** [easy-wi/developer#988]
Hi,
I have installed the newest version of easy-wi.

After adding CSGO to my game master server I cant start the Gameserver.

From the Logs I get the following error:
`Cannot exec './hlds_run': No such file or directory`

Also I cant open the manual (404) to check if I did all right for the installation:
https://easy-wi.com/de/gameserver-admin-game-rootserver-installation/

**Comment by MikkelDK** [comment]
You write: After adding CSGO to my game master server I cant start the Gameserver.

But the ./hlds_run is CS 1.6 :)

**Comment by Eiskaltereistee** [comment]
@MikkelDK
yes, but I got these error.

But now I know why. It is beacuse the default image server ist not accessable so there are no games in my masterserver folder

**Comment by MikkelDK** [comment]
Normal you need to install the "masterserver" via panel :)
