### ISSUE TITLE
Vertreter: Schon existierende Benutzer authorisieren

### ISSUE THREAD

**Issue by Nollig** [easy-wi/developer#990]
Hallo,

leider kann man nur Vertreter eintragen die noch nicht in der Datenbank vorhanden sind.

Meine Idee:
- Funktion zum hinzufügen eines Vertreters, der bereits existiert, evtl. schon eigene Server hat.

Ich hoffe das ist machbar.

**Comment by ulrichblock** [comment]
Dann dürfte ein Kunde als Konsequenz alle Vertreter von anderen Kunden erfragen können. Durch dieses Proben kann man dann bequem Startpunkte für Brut Force finden.
