### ISSUE TITLE
Fehler beim Update (6.00)

### ISSUE THREAD

**Issue by Bara20** [easy-wi/developer#995]
Easy-WI Version laut Webinterface: 5.30
PHP Version: 7.1.4
MariaDB Version: 10.1

Bekomme beim Update diesen SQL Fehler:
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'serverID' in 'where clause' in install/update_530-600.php:59`

**Comment by Bara20** [comment]
Gleicher Fehler:
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'serverID' in 'where clause' in install/update_530-600.php:64`


---
Allerdings existiert `serverID` in der `settings` table.

**Comment by ulrichblock** [comment]
Argh. Heute ist echt nicht mein Tag...
