### ISSUE TITLE
Mobile Version Captcha Issue

### ISSUE THREAD

**Issue by TandelK** [easy-wi/developer#996]
I am using Google Chrome on my android browser and it does not shows me Captcha on mobile phone. you can have a look at panel.itgc.ga

**Comment by ulrichblock** [comment]
I don't have/use Chrome so I cannot debug and fix this. Help would be apprichiated.

**Comment by TandelK** [comment]
I am closing this issue as i found why it was not showing up properly , It was due to my Chrome was Auto Data Saver Mode so it never displayed that images. Now it seems to work fine.
