### ISSUE TITLE
Reseller Voiceserver

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/developer#997]
Wenn ein Voiceserver Master einem Reseller zugeteilt wird, so werden Onlinezeit, Onlineuser etc nicht angezeigt und bleiben immer auf 0. 

Der erstellte Voiceserver wird als online angezeigt:
![92b0bd02158c4602a1f00fc157dfd6ff](https://cloud.githubusercontent.com/assets/16845703/26493546/8ab52028-421a-11e7-9298-512f58059140.png)

Dies ist bei allen Resellern, bei normalen Kunden funktioniert dies Problemlos.
EW 6.0.0

**Comment by ulrichblock** [comment]
Guck mal, ob https://github.com/easy-wi/developer/commit/d93dcd3d70c661ea473b04eb324b30778648abdc das Problem bei dir behebt.

**Comment by DAThosting** [comment]
:+1: 

Funktioniert
