### ISSUE TITLE
Facebook Auth not working after new update

### ISSUE THREAD

**Issue by TandelK** [easy-wi/developer#999]
After recent update we are unable to log in via Facebook anymore. The reason i get in Apache2 error Log is 

[:error] [pid 30418] [client 162.158.154.252:12961] PHP Fatal error:  Class 'Facebook\\Facebook' not found in /var/www/panel.sitename/public_html/third_party/hybridauth/Hybrid/Providers/Facebook.php on line 71, referer: http://panel.sitename/login.php

**Comment by ulrichblock** [comment]
Looks like it tries to do some reflection loading while the class names are actually Hybrid_Providers_Facebook
